#!/usr/bin/env python3
"""
Realistic Wiring Diagram Generator - Professional Quality
Uses realistic component SVG graphics instead of colored rectangles
"""

from pathlib import Path
from typing import List, Dict, Tuple
import json


class RealisticDiagramGenerator:
    """Generates professional-quality SVG breadboard diagrams"""

    def __init__(self):
        self.breadboard_width = 900
        self.breadboard_height = 600
        self.hole_spacing = 10

        # Professional colors
        self.colors = {
            'breadboard_bg': '#F4E4C1',
            'breadboard_edge': '#8B7355',
            'power_pos': '#CC0000',
            'power_neg': '#0066CC',
            'wire_5v': '#FF0000',
            'wire_gnd': '#000000',
            'wire_signal': '#22AA22',
            'wire_i2c_sda': '#FFCC00',
            'wire_i2c_scl': '#FF6600',
            'component_shadow': 'rgba(0,0,0,0.2)'
        }

    def generate_diagram(self, design: Dict, output_path: str) -> str:
        """Generate professional wiring diagram"""
        svg = []

        # SVG header with defs for reusable elements
        svg.append(f'''<svg width="{self.breadboard_width + 500}" height="{self.breadboard_height + 300}"
            xmlns="http://www.w3.org/2000/svg">
            <defs>
                <!-- Shadow filter -->
                <filter id="shadow" x="-50%" y="-50%" width="200%" height="200%">
                    <feGaussianBlur in="SourceAlpha" stdDeviation="3"/>
                    <feOffset dx="2" dy="2" result="offsetblur"/>
                    <feComponentTransfer>
                        <feFuncA type="linear" slope="0.3"/>
                    </feComponentTransfer>
                    <feMerge>
                        <feMergeNode/>
                        <feMergeNode in="SourceGraphic"/>
                    </feMerge>
                </filter>

                <!-- Gradient for 3D effect -->
                <linearGradient id="boardGradient" x1="0%" y1="0%" x2="0%" y2="100%">
                    <stop offset="0%" style="stop-color:#F8ECD4;stop-opacity:1" />
                    <stop offset="100%" style="stop-color:#E8D4B4;stop-opacity:1" />
                </linearGradient>
            </defs>''')

        # Title and description
        project_name = design.get('project_name', 'Circuit Diagram')
        svg.append(f'''
            <rect x="0" y="0" width="{self.breadboard_width + 500}" height="80" fill="#2C3E50"/>
            <text x="20" y="45" font-size="32" font-weight="bold" fill="white">
                {project_name.replace('_', ' ').title()}
            </text>
            <text x="20" y="68" font-size="14" fill="#ECF0F1">
                Professional Wiring Diagram • Circuit-AI
            </text>''')

        # Draw realistic breadboard
        svg.append(self._draw_realistic_breadboard(50, 120))

        # Draw microcontroller
        mcu_type = design.get('microcontroller', 'arduino_uno')
        mcu_pos = (1000, 200)
        svg.append(self._draw_realistic_microcontroller(mcu_type, mcu_pos))

        # Draw components
        component_positions = {}
        components = design.get('components', [])

        # Position components on breadboard
        start_x = 150
        y_pos = 250
        for i, comp in enumerate(components):
            x_pos = start_x + (i * 180)
            if x_pos > 700:  # Wrap to second row
                x_pos = start_x + ((i - 4) * 180)
                y_pos = 450

            pos = (x_pos, y_pos)
            component_positions[comp.get('id', f'comp_{i}')] = pos
            svg.append(self._draw_realistic_component(comp, pos))

        # Draw wiring with better routing
        connections = self._generate_realistic_connections(design, mcu_pos, component_positions)
        svg.append('\n'.join(connections))

        # Professional legend
        svg.append(self._draw_professional_legend(50, self.breadboard_height + 180))

        # Footer
        svg.append('''
            <text x="20" y="''' + str(self.breadboard_height + 280) + '''" font-size="10" fill="#7F8C8D">
                Generated by Circuit-AI • Open source component data from Fritzing & Arduino community
            </text>
        </svg>''')

        # Save
        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)
        output_file.write_text('\n'.join(svg))

        return str(output_file)

    def _draw_realistic_breadboard(self, x: int, y: int) -> str:
        """Draw realistic breadboard with holes"""
        svg = []

        # Shadow
        svg.append(f'''<rect x="{x+5}" y="{y+5}" width="{self.breadboard_width}"
            height="{self.breadboard_height}" fill="{self.colors['component_shadow']}" rx="8"/>''')

        # Main board with gradient
        svg.append(f'''<rect x="{x}" y="{y}" width="{self.breadboard_width}"
            height="{self.breadboard_height}" fill="url(#boardGradient)"
            stroke="{self.colors['breadboard_edge']}" stroke-width="3" rx="8"/>''')

        # Mounting holes (4 corners)
        for corner_x, corner_y in [(x+20, y+20), (x+self.breadboard_width-20, y+20),
                                     (x+20, y+self.breadboard_height-20),
                                     (x+self.breadboard_width-20, y+self.breadboard_height-20)]:
            svg.append(f'''<circle cx="{corner_x}" cy="{corner_y}" r="6"
                fill="#666" stroke="#333" stroke-width="1"/>
                <circle cx="{corner_x}" cy="{corner_y}" r="3" fill="#333"/>''')

        # Power rails (top) with labels
        rail_y_top = y + 50
        svg.append(f'''
            <!-- Top power rails -->
            <rect x="{x+40}" y="{rail_y_top-4}" width="{self.breadboard_width-80}" height="8"
                fill="{self.colors['power_pos']}" rx="2"/>
            <rect x="{x+40}" y="{rail_y_top+12}" width="{self.breadboard_width-80}" height="8"
                fill="{self.colors['power_neg']}" rx="2"/>
            <text x="{x+30}" y="{rail_y_top+3}" font-size="12" font-weight="bold" fill="{self.colors['power_pos']}">+</text>
            <text x="{x+30}" y="{rail_y_top+19}" font-size="12" font-weight="bold" fill="{self.colors['power_neg']}">−</text>
        ''')

        # Power rails (bottom)
        rail_y_bottom = y + self.breadboard_height - 50
        svg.append(f'''
            <!-- Bottom power rails -->
            <rect x="{x+40}" y="{rail_y_bottom-4}" width="{self.breadboard_width-80}" height="8"
                fill="{self.colors['power_pos']}" rx="2"/>
            <rect x="{x+40}" y="{rail_y_bottom+12}" width="{self.breadboard_width-80}" height="8"
                fill="{self.colors['power_neg']}" rx="2"/>
            <text x="{x+30}" y="{rail_y_bottom+3}" font-size="12" font-weight="bold" fill="{self.colors['power_pos']}">+</text>
            <text x="{x+30}" y="{rail_y_bottom+19}" font-size="12" font-weight="bold" fill="{self.colors['power_neg']}">−</text>
        ''')

        # Breadboard holes (just show a grid pattern, not all 830 holes)
        hole_start_y = y + 100
        hole_end_y = y + self.breadboard_height - 100

        for row in range(0, 40, 2):  # Simplified grid
            row_y = hole_start_y + (row * 12)
            if row_y > hole_end_y:
                break
            for col in range(0, 60, 2):
                hole_x = x + 100 + (col * 12)
                if hole_x > x + self.breadboard_width - 100:
                    break
                svg.append(f'<circle cx="{hole_x}" cy="{row_y}" r="2.5" fill="#666" opacity="0.3"/>')

        # Row labels (A-J)
        for i, label in enumerate(['A', 'B', 'C', 'D', 'E', '', 'F', 'G', 'H', 'I', 'J']):
            if label:
                label_y = hole_start_y + (i * 45)
                if label_y < hole_end_y:
                    svg.append(f'''<text x="{x+75}" y="{label_y+5}" font-size="14"
                        font-weight="bold" fill="#666">{label}</text>''')

        return '\n'.join(svg)

    def _draw_realistic_microcontroller(self, mcu_type: str, pos: Tuple[int, int]) -> str:
        """Draw realistic microcontroller with proper details"""
        x, y = pos
        svg = []

        if 'arduino' in mcu_type.lower():
            # Arduino Uno style
            width, height = 70, 85

            # Shadow
            svg.append(f'<rect x="{x+3}" y="{y+3}" width="{width}" height="{height}" fill="{self.colors["component_shadow"]}" rx="3"/>')

            # Main PCB (teal color for Arduino)
            svg.append(f'''<rect x="{x}" y="{y}" width="{width}" height="{height}"
                fill="#008B8B" stroke="#006666" stroke-width="2" rx="3" filter="url(#shadow)"/>''')

            # USB connector (silver)
            svg.append(f'''<rect x="{x+width-8}" y="{y+25}" width="8" height="16"
                fill="#C0C0C0" stroke="#888" stroke-width="1"/>
                <rect x="{x+width-6}" y="{y+27}" width="4" height="12" fill="#333"/>''')

            # Power jack (black)
            svg.append(f'''<circle cx="{x+10}" cy="{y+12}" r="6" fill="#222" stroke="#000" stroke-width="1"/>
                <circle cx="{x+10}" cy="{y+12}" r="3" fill="#444"/>''')

            # ATmega chip (black rectangle)
            svg.append(f'''<rect x="{x+20}" y="{y+30}" width="30" height="30"
                fill="#111" stroke="#000" stroke-width="1" rx="2"/>
                <circle cx="{x+23}" cy="{y+33}" r="1.5" fill="#666"/>
                <text x="{x+35}" y="{y+48}" font-size="6" fill="#FFF" text-anchor="middle">ATmega</text>
                <text x="{x+35}" y="{y+55}" font-size="5" fill="#FFF" text-anchor="middle">328P</text>''')

            # Pin headers (gold)
            for i in range(14):
                pin_x = x + 5 + (i * 4.5)
                # Top header
                svg.append(f'<rect x="{pin_x}" y="{y}" width="2" height="4" fill="#FFD700" stroke="#CC9900" stroke-width="0.3"/>')
                # Bottom header
                svg.append(f'<rect x="{pin_x}" y="{y+height-4}" width="2" height="4" fill="#FFD700" stroke="#CC9900" stroke-width="0.3"/>')

            # Reset button (red)
            svg.append(f'<circle cx="{x+55}" cy="{y+15}" r="4" fill="#CC0000" stroke="#990000" stroke-width="1"/>')

            # LED (usually near pin 13)
            svg.append(f'<circle cx="{x+58}" cy="{y+70}" r="2" fill="#00FF00"/>')

            # Label
            svg.append(f'''<text x="{x+35}" y="{y+73}" font-size="8" fill="#FFF"
                text-anchor="middle" font-weight="bold">ARDUINO</text>''')

        elif 'esp32' in mcu_type.lower():
            # ESP32 DevKit
            width, height = 60, 35

            # Shadow
            svg.append(f'<rect x="{x+3}" y="{y+3}" width="{width}" height="{height}" fill="{self.colors["component_shadow"]}" rx="2"/>')

            # Main PCB (black for ESP32)
            svg.append(f'''<rect x="{x}" y="{y}" width="{width}" height="{height}"
                fill="#1a1a1a" stroke="#000" stroke-width="2" rx="2" filter="url(#shadow)"/>''')

            # ESP32 chip (silver metal can)
            svg.append(f'''<rect x="{x+8}" y="{y+5}" width="25" height="25"
                fill="#C0C0C0" stroke="#999" stroke-width="1" rx="1"/>
                <text x="{x+20.5}" y="{y+18}" font-size="6" fill="#333" text-anchor="middle">ESP32</text>''')

            # Antenna (gold zigzag pattern)
            svg.append(f'''<path d="M {x+38} {y+8} L {x+43} {y+8} L {x+43} {y+12} L {x+48} {y+12}
                L {x+48} {y+8} L {x+53} {y+8} L {x+53} {y+27} L {x+48} {y+27} L {x+48} {y+23}
                L {x+43} {y+23} L {x+43} {y+27} L {x+38} {y+27} Z"
                fill="#FFD700" stroke="#CC9900" stroke-width="0.5"/>''')

            # USB micro (silver)
            svg.append(f'''<rect x="{x-3}" y="{y+12}" width="3" height="11"
                fill="#C0C0C0" stroke="#888" stroke-width="0.5"/>''')

            # Pin headers
            for i in range(15):
                pin_x = x + 2 + (i * 3.8)
                svg.append(f'<rect x="{pin_x}" y="{y}" width="1.5" height="3" fill="#FFD700" stroke="#CC9900" stroke-width="0.2"/>')
                svg.append(f'<rect x="{pin_x}" y="{y+height-3}" width="1.5" height="3" fill="#FFD700" stroke="#CC9900" stroke-width="0.2"/>')

            # Label
            svg.append(f'''<text x="{x+30}" y="{y+33}" font-size="6" fill="#FFF"
                text-anchor="middle" font-weight="bold">ESP32 DevKit</text>''')

        # Board label above
        svg.append(f'''<text x="{x}" y="{y-8}" font-size="14" font-weight="bold" fill="#2C3E50">
            {mcu_type.upper().replace('_', ' ')}</text>''')

        return '\n'.join(svg)

    def _draw_realistic_component(self, component: Dict, pos: Tuple[int, int]) -> str:
        """Draw realistic component with proper graphics"""
        x, y = pos
        svg = []

        comp_name = component.get('name', 'Component').lower()
        comp_id = component.get('id', 'comp')

        # BME280 / BMP280 sensor module
        if 'bme' in comp_name or 'bmp' in comp_name:
            width, height = 25, 25
            # Shadow
            svg.append(f'<rect x="{x+2}" y="{y+2}" width="{width}" height="{height}" fill="{self.colors["component_shadow"]}" rx="2"/>')
            # Purple PCB
            svg.append(f'<rect x="{x}" y="{y}" width="{width}" height="{height}" fill="#663399" stroke="#4B0082" stroke-width="1.5" rx="2" filter="url(#shadow)"/>')
            # Sensor chip (silver)
            svg.append(f'<rect x="{x+5}" y="{y+5}" width="15" height="15" fill="#C0C0C0" stroke="#999" stroke-width="1" rx="1"/>')
            svg.append(f'<circle cx="{x+12.5}" cy="{y+12.5}" r="4" fill="#666"/>')
            # Pin headers (4 pins)
            for i in range(4):
                pin_x = x + 4 + (i * 5.5)
                svg.append(f'<line x1="{pin_x}" y1="{y+height}" x2="{pin_x}" y2="{y+height+8}" stroke="#FFD700" stroke-width="2"/>')
                svg.append(f'<circle cx="{pin_x}" cy="{y+height+10}" r="2" fill="#FFD700" stroke="#CC9900" stroke-width="0.5"/>')
            svg.append(f'<text x="{x+12.5}" y="{y+height-2}" font-size="5" fill="#FFF" text-anchor="middle">BME280</text>')

        # DHT22 sensor
        elif 'dht' in comp_name:
            width, height = 18, 28
            # Shadow
            svg.append(f'<rect x="{x+2}" y="{y+2}" width="{width}" height="{height}" fill="{self.colors["component_shadow"]}" rx="1"/>')
            # Blue body
            svg.append(f'<rect x="{x}" y="{y}" width="{width}" height="{height}" fill="#4169E1" stroke="#2850B1" stroke-width="1.5" rx="1" filter="url(#shadow)"/>')
            # Sensor grill (white)
            svg.append(f'<rect x="{x+3}" y="{y+3}" width="{width-6}" height="{height-12}" fill="#FFF" stroke="#DDD" stroke-width="0.5" rx="1"/>')
            # Grill lines
            for i in range(1, 5):
                grill_y = y + 5 + (i * 3)
                svg.append(f'<line x1="{x+4}" y1="{grill_y}" x2="{x+width-4}" y2="{grill_y}" stroke="#CCC" stroke-width="0.5"/>')
            # 3 pins
            for i in range(3):
                pin_x = x + 4 + (i * 5)
                svg.append(f'<line x1="{pin_x}" y1="{y+height}" x2="{pin_x}" y2="{y+height+10}" stroke="#FFD700" stroke-width="2"/>')
                svg.append(f'<circle cx="{pin_x}" cy="{y+height+12}" r="2" fill="#FFD700" stroke="#CC9900" stroke-width="0.5"/>')
            svg.append(f'<text x="{x+9}" y="{y+25}" font-size="5" fill="#FFF" font-weight="bold">DHT22</text>')

        # OLED display
        elif 'oled' in comp_name:
            width, height = 35, 35
            # Shadow
            svg.append(f'<rect x="{x+2}" y="{y+2}" width="{width}" height="{height}" fill="{self.colors["component_shadow"]}" rx="2"/>')
            # Blue PCB
            svg.append(f'<rect x="{x}" y="{y}" width="{width}" height="{height}" fill="#000080" stroke="#000050" stroke-width="1.5" rx="2" filter="url(#shadow)"/>')
            # Screen (black with slight glow)
            svg.append(f'<rect x="{x+3}" y="{y+3}" width="{width-6}" height="{height-12}" fill="#000" stroke="#333" stroke-width="1" rx="1"/>')
            # Simulated display content
            svg.append(f'<text x="{x+17.5}" y="{y+16}" font-size="6" fill="#00FFFF" text-anchor="middle">OLED</text>')
            svg.append(f'<text x="{x+17.5}" y="{y+22}" font-size="4" fill="#00FFFF" text-anchor="middle">128x64</text>')
            # 4 pins
            for i in range(4):
                pin_x = x + 6 + (i * 7)
                svg.append(f'<line x1="{pin_x}" y1="{y+height}" x2="{pin_x}" y2="{y+height+8}" stroke="#FFD700" stroke-width="2"/>')
                svg.append(f'<circle cx="{pin_x}" cy="{y+height+10}" r="2" fill="#FFD700" stroke="#CC9900" stroke-width="0.5"/>')

        # HC-SR04 Ultrasonic sensor
        elif 'hc' in comp_name or 'sr04' in comp_name:
            width, height = 45, 22
            # Shadow
            svg.append(f'<rect x="{x+2}" y="{y+2}" width="{width}" height="{height}" fill="{self.colors["component_shadow"]}" rx="2"/>')
            # Green PCB
            svg.append(f'<rect x="{x}" y="{y}" width="{width}" height="{height}" fill="#228B22" stroke="#1a6e1a" stroke-width="1.5" rx="2" filter="url(#shadow)"/>')
            # Two ultrasonic "eyes" (silver cylinders)
            for eye_x in [x+10, x+35]:
                svg.append(f'<circle cx="{eye_x}" cy="{y+11}" r="8" fill="#C0C0C0" stroke="#999" stroke-width="1"/>')
                svg.append(f'<circle cx="{eye_x}" cy="{y+11}" r="6" fill="#888"/>')
                svg.append(f'<circle cx="{eye_x}" cy="{y+11}" r="4" fill="#555"/>')
            # 4 pins at bottom
            for i in range(4):
                pin_x = x + 8 + (i * 10)
                svg.append(f'<line x1="{pin_x}" y1="{y+height}" x2="{pin_x}" y2="{y+height+8}" stroke="#FFD700" stroke-width="2"/>')
                svg.append(f'<circle cx="{pin_x}" cy="{y+height+10}" r="2" fill="#FFD700" stroke="#CC9900" stroke-width="0.5"/>')
            svg.append(f'<text x="{x+22.5}" y="{y+8}" font-size="5" fill="#FFF" text-anchor="middle">HC-SR04</text>')

        # Generic sensor (fallback)
        else:
            width, height = 20, 20
            svg.append(f'<rect x="{x+2}" y="{y+2}" width="{width}" height="{height}" fill="{self.colors["component_shadow"]}" rx="2"/>')
            svg.append(f'<rect x="{x}" y="{y}" width="{width}" height="{height}" fill="#4169E1" stroke="#2850B1" stroke-width="1.5" rx="2" filter="url(#shadow)"/>')
            # 4 pins
            for i in range(4):
                pin_x = x + 3 + (i * 5)
                svg.append(f'<line x1="{pin_x}" y1="{y+height}" x2="{pin_x}" y2="{y+height+8}" stroke="#FFD700" stroke-width="2"/>')
                svg.append(f'<circle cx="{pin_x}" cy="{y+height+10}" r="2" fill="#FFD700" stroke="#CC9900" stroke-width="0.5"/>')

        # Component label above
        label_text = component.get('name', 'Component')[:20]
        svg.append(f'''<text x="{x}" y="{y-8}" font-size="12" font-weight="bold" fill="#2C3E50">
            {label_text}</text>''')

        return '\n'.join(svg)

    def _generate_realistic_connections(self, design: Dict, mcu_pos: Tuple[int, int],
                                       comp_positions: Dict) -> List[str]:
        """Generate realistic wire routing"""
        wires = []
        mcu_x, mcu_y = mcu_pos

        for comp_id, (comp_x, comp_y) in comp_positions.items():
            # Power wire (red)
            wires.append(self._draw_realistic_wire(
                (comp_x + 10, comp_y + 35),
                (mcu_x + 10, mcu_y),
                self.colors['wire_5v'],
                "3.3V"
            ))

            # Ground wire (black)
            wires.append(self._draw_realistic_wire(
                (comp_x + 20, comp_y + 35),
                (mcu_x + 20, mcu_y),
                self.colors['wire_gnd'],
                "GND"
            ))

            # Signal wire (green)
            wires.append(self._draw_realistic_wire(
                (comp_x + 30, comp_y + 35),
                (mcu_x + 35, mcu_y + 15),
                self.colors['wire_signal'],
                "D2"
            ))

        return wires

    def _draw_realistic_wire(self, start: Tuple[int, int], end: Tuple[int, int],
                            color: str, label: str = "") -> str:
        """Draw realistic wire with proper routing"""
        x1, y1 = start
        x2, y2 = end

        # Calculate better control points for realistic routing
        mid_x = (x1 + x2) / 2
        mid_y = min(y1, y2) - 50

        # Draw wire with slight thickness and shadow
        svg = []

        # Wire shadow
        svg.append(f'''<path d="M {x1+1},{y1+1} Q {mid_x+1},{mid_y+1} {x2+1},{y2+1}"
            stroke="rgba(0,0,0,0.2)" stroke-width="4" fill="none"/>''')

        # Main wire
        svg.append(f'''<path d="M {x1},{y1} Q {mid_x},{mid_y} {x2},{y2}"
            stroke="{color}" stroke-width="3" fill="none" stroke-linecap="round"/>''')

        # Wire label with background
        if label:
            label_x = mid_x
            label_y = mid_y - 8
            svg.append(f'''<rect x="{label_x-15}" y="{label_y-10}" width="30" height="14"
                fill="white" stroke="{color}" stroke-width="1" rx="2" opacity="0.9"/>
                <text x="{label_x}" y="{label_y}" font-size="9" font-weight="bold"
                text-anchor="middle" fill="{color}">{label}</text>''')

        return '\n'.join(svg)

    def _draw_professional_legend(self, x: int, y: int) -> str:
        """Draw professional legend with icon"""
        svg = []

        # Legend box
        svg.append(f'''<rect x="{x}" y="{y}" width="500" height="100"
            fill="#ECF0F1" stroke="#2C3E50" stroke-width="2" rx="5"/>''')

        svg.append(f'''<text x="{x+10}" y="{y+25}" font-size="16" font-weight="bold" fill="#2C3E50">
            Wire Color Reference</text>''')

        # Wire examples with descriptions
        legends = [
            (self.colors['wire_5v'], "Red", "Power (3.3V/5V)"),
            (self.colors['wire_gnd'], "Black", "Ground (GND)"),
            (self.colors['wire_signal'], "Green", "Digital Signal"),
            (self.colors['wire_i2c_sda'], "Yellow", "I2C SDA (Data)"),
            (self.colors['wire_i2c_scl'], "Orange", "I2C SCL (Clock)")
        ]

        for i, (color, name, desc) in enumerate(legends):
            legend_x = x + 15 + (i % 3) * 160
            legend_y = y + 45 + (i // 3) * 30

            # Wire sample
            svg.append(f'''<line x1="{legend_x}" y1="{legend_y}" x2="{legend_x+40}" y2="{legend_y}"
                stroke="{color}" stroke-width="4" stroke-linecap="round"/>''')

            # Description
            svg.append(f'''<text x="{legend_x+50}" y="{legend_y+2}" font-size="11" fill="#34495E">
                <tspan font-weight="bold">{name}:</tspan> {desc}</text>''')

        return '\n'.join(svg)


def main():
    """Demo realistic diagram generator"""
    gen = RealisticDiagramGenerator()

    design = {
        'project_name': 'environmental_monitor',
        'microcontroller': 'arduino_uno',
        'components': [
            {'id': 'bme280', 'name': 'BME280', 'pins': 4},
            {'id': 'dht22', 'name': 'DHT22', 'pins': 3},
            {'id': 'oled', 'name': 'OLED 0.96"', 'pins': 4}
        ]
    }

    output = gen.generate_diagram(design, 'output/realistic_test.svg')
    print(f"✓ Generated realistic diagram: {output}")


if __name__ == '__main__':
    main()
