// High-leverage modules curated to fill gaps found by a gap-audit against
// common hobby parts. Each entry cites a datasheet/product URL.
//
// Provenance: entries marked WEB-VERIFIED were fetched and confirmed via
// Adafruit/Pololu/SparkFun product pages during this curation pass.
// Entries marked SPEC-CURATED were hand-written from stable, well-known
// pinouts (TI/Microchip/Sensirion/Infineon parts whose pinouts have been
// stable for years) and carry a datasheetUrl for verification.

import type { ModuleSpec } from "./module-library";

export const CURATED_EXTENDED: ModuleSpec[] = [
  // ---- WEB-VERIFIED (Adafruit/Pololu/SparkFun product pages) ----
  {
    id: "ina219-current",
    label: "INA219 current sensor",
    category: "sensor",
    summary: "I2C bidirectional current/voltage sensor, ±3.2A, up to 26V bus.",
    logicVoltage: 3.3,
    inputVoltageRange: [2.7, 5.5],
    manufacturer: "Texas Instruments",
    partNumber: "INA219",
    datasheetUrl: "https://learn.adafruit.com/adafruit-ina219-current-sensor-breakout/pinouts",
    priceUsd: 5,
    source: "curated",
    pins: [
      { id: "VIN", label: "VIN", role: "power_in", voltage: "2.7-5.5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SCL", label: "SCL", role: "i2c_scl", voltage: "3.3V or 5V" },
      { id: "SDA", label: "SDA", role: "i2c_sda", voltage: "3.3V or 5V" },
      { id: "VIN+", label: "Vin+", role: "analog_in", voltage: "0-26V", notes: "High-side current sense input" },
      { id: "VIN-", label: "Vin-", role: "analog_in", voltage: "0-26V", notes: "Low-side current sense input" },
    ],
    warnings: ["Default I2C address 0x40; jumpers A0/A1 select 0x41/0x44/0x45."],
  },
  {
    id: "pca9685-pwm",
    label: "PCA9685 16-channel PWM/servo driver",
    category: "interface",
    summary: "I2C-controlled 16 PWM outputs @ up to 1.6kHz, 12-bit; common for servos.",
    logicVoltage: 5,
    inputVoltageRange: [3, 5.5],
    manufacturer: "NXP",
    partNumber: "PCA9685",
    datasheetUrl: "https://learn.adafruit.com/16-channel-pwm-servo-driver/pinouts",
    priceUsd: 14,
    source: "curated",
    pins: [
      { id: "GND", label: "GND", role: "gnd" },
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3-5V" },
      { id: "V+", label: "V+", role: "power_in", voltage: "5-6V", notes: "Servo rail; up to 12V absolute max" },
      { id: "SCL", label: "SCL", role: "i2c_scl", voltage: "3.3V or 5V" },
      { id: "SDA", label: "SDA", role: "i2c_sda", voltage: "3.3V or 5V" },
      { id: "OE", label: "OE", role: "digital_in", voltage: "logic level", notes: "Low: outputs active; high: outputs disabled" },
      { id: "PWM0", label: "PWM0", role: "pwm" },
      { id: "PWM1", label: "PWM1", role: "pwm" },
      { id: "PWM2", label: "PWM2", role: "pwm" },
      { id: "PWM3", label: "PWM3", role: "pwm" },
      { id: "PWM4", label: "PWM4", role: "pwm" },
      { id: "PWM5", label: "PWM5", role: "pwm" },
      { id: "PWM6", label: "PWM6", role: "pwm" },
      { id: "PWM7", label: "PWM7", role: "pwm" },
      { id: "PWM8", label: "PWM8", role: "pwm" },
      { id: "PWM9", label: "PWM9", role: "pwm" },
      { id: "PWM10", label: "PWM10", role: "pwm" },
      { id: "PWM11", label: "PWM11", role: "pwm" },
      { id: "PWM12", label: "PWM12", role: "pwm" },
      { id: "PWM13", label: "PWM13", role: "pwm" },
      { id: "PWM14", label: "PWM14", role: "pwm" },
      { id: "PWM15", label: "PWM15", role: "pwm" },
    ],
    warnings: ["Power servos from V+ on a separate supply, never the logic VCC."],
  },
  {
    id: "a4988-stepper",
    label: "A4988 stepper driver carrier",
    category: "actuator",
    summary: "Bipolar stepper driver, up to 2A/coil with adequate cooling; 8-35V motor.",
    inputVoltageRange: [3, 5.5],
    manufacturer: "Allegro Microsystems / Pololu carrier",
    partNumber: "A4988",
    datasheetUrl: "https://www.pololu.com/product/1182",
    priceUsd: 6,
    source: "curated",
    pins: [
      { id: "VDD", label: "VDD", role: "power_in", voltage: "3-5.5V", notes: "Logic supply" },
      { id: "VMOT", label: "VMOT", role: "power_in", voltage: "8-35V", notes: "Motor supply" },
      { id: "GND_LOGIC", label: "GND", role: "gnd" },
      { id: "GND_MOTOR", label: "GND (motor)", role: "gnd" },
      { id: "STEP", label: "STEP", role: "digital_in", voltage: "logic level" },
      { id: "DIR", label: "DIR", role: "digital_in", voltage: "logic level" },
      { id: "MS1", label: "MS1", role: "digital_in", voltage: "logic level" },
      { id: "MS2", label: "MS2", role: "digital_in", voltage: "logic level" },
      { id: "MS3", label: "MS3", role: "digital_in", voltage: "logic level" },
      { id: "RST", label: "RST", role: "reset", voltage: "logic level" },
      { id: "SLP", label: "SLP", role: "digital_in", voltage: "logic level" },
      { id: "EN", label: "EN", role: "digital_in", voltage: "logic level", notes: "Active-low enable" },
      { id: "1A", label: "1A", role: "power_out", notes: "Coil 1" },
      { id: "1B", label: "1B", role: "power_out", notes: "Coil 1" },
      { id: "2A", label: "2A", role: "power_out", notes: "Coil 2" },
      { id: "2B", label: "2B", role: "power_out", notes: "Coil 2" },
    ],
    warnings: [
      "Set the VREF current limit BEFORE connecting the motor.",
      "RST and SLP must be tied together if SLP isn't used (datasheet requirement).",
    ],
  },
  {
    id: "pcf8574-ioexp",
    label: "PCF8574 I2C GPIO expander",
    category: "interface",
    summary: "Adds 8 quasi-bidirectional GPIO pins over I2C; useful for buttons/LEDs.",
    logicVoltage: 3.3,
    inputVoltageRange: [3, 5],
    manufacturer: "NXP",
    partNumber: "PCF8574",
    datasheetUrl: "https://learn.adafruit.com/adafruit-pcf8574/pinouts",
    priceUsd: 4,
    source: "curated",
    pins: [
      { id: "VIN", label: "VIN", role: "power_in", voltage: "3-5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SCL", label: "SCL", role: "i2c_scl", voltage: "3.3V or 5V" },
      { id: "SDA", label: "SDA", role: "i2c_sda", voltage: "3.3V or 5V" },
      { id: "INT", label: "INT", role: "digital_out", voltage: "logic level", notes: "Open-drain interrupt on pin change" },
      { id: "P0", label: "P0", role: "digital_io" },
      { id: "P1", label: "P1", role: "digital_io" },
      { id: "P2", label: "P2", role: "digital_io" },
      { id: "P3", label: "P3", role: "digital_io" },
      { id: "P4", label: "P4", role: "digital_io" },
      { id: "P5", label: "P5", role: "digital_io" },
      { id: "P6", label: "P6", role: "digital_io" },
      { id: "P7", label: "P7", role: "digital_io" },
    ],
    warnings: ["Quasi-bidirectional outputs are weak high-side — use external pull-up for clean reads."],
  },
  {
    id: "max31855-thermocouple",
    label: "MAX31855 K-type thermocouple amplifier",
    category: "sensor",
    summary: "SPI cold-junction-compensated K-type thermocouple-to-digital converter.",
    logicVoltage: 3.3,
    inputVoltageRange: [3, 5.5],
    manufacturer: "Maxim Integrated",
    partNumber: "MAX31855",
    datasheetUrl: "https://www.adafruit.com/product/269",
    priceUsd: 15,
    source: "curated",
    pins: [
      { id: "VIN", label: "VIN", role: "power_in", voltage: "3-5V" },
      { id: "3V3", label: "3Vo", role: "power_out", voltage: "3.3V", currentMaxMa: 100 },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "DO", label: "DO", role: "spi_miso", voltage: "3.3V" },
      { id: "CS", label: "CS", role: "spi_cs", voltage: "3.3V" },
      { id: "CLK", label: "CLK", role: "spi_sck", voltage: "3.3V" },
      { id: "T+", label: "T+", role: "analog_in", notes: "Thermocouple positive (yellow)" },
      { id: "T-", label: "T-", role: "analog_in", notes: "Thermocouple negative (red)" },
    ],
    warnings: [
      "Read-only SPI device — DI line not used.",
      "Cold-junction compensation requires the IC sees ambient temperature; don't enclose it.",
    ],
  },
  {
    id: "hx711-loadcell",
    label: "HX711 24-bit ADC for load cells",
    category: "sensor",
    summary: "24-bit ΔΣ ADC with built-in PGA for strain-gauge load cells; up to 80SPS.",
    inputVoltageRange: [2.7, 5],
    manufacturer: "Avia Semiconductor",
    partNumber: "HX711",
    datasheetUrl: "https://www.sparkfun.com/products/13879",
    priceUsd: 3,
    source: "curated",
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "2.7-5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "DT", label: "DT", role: "digital_out", voltage: "logic level", notes: "Data out to MCU" },
      { id: "SCK", label: "SCK", role: "digital_in", voltage: "logic level", notes: "Clock from MCU" },
      { id: "E+", label: "E+", role: "power_out", voltage: "5V", notes: "Excitation+ for load cell (red wire)" },
      { id: "E-", label: "E-", role: "gnd", notes: "Excitation- (black wire)" },
      { id: "A+", label: "A+", role: "analog_in", notes: "Signal+ from load cell (white wire)" },
      { id: "A-", label: "A-", role: "analog_in", notes: "Signal- (green wire)" },
      { id: "B+", label: "B+", role: "analog_in", notes: "Optional channel B" },
      { id: "B-", label: "B-", role: "analog_in", notes: "Optional channel B" },
    ],
    warnings: ["Channel A gain is 128 or 64; channel B is fixed at 32."],
  },

  // ---- SPEC-CURATED (well-known stable pinouts; datasheet URLs verify) ----
  {
    id: "74hc595-shift-reg",
    label: "74HC595 8-bit shift register",
    category: "interface",
    summary: "Serial-in/parallel-out shift register, daisy-chainable via Q7'.",
    logicVoltage: 5,
    inputVoltageRange: [2, 6],
    manufacturer: "Texas Instruments",
    partNumber: "SN74HC595",
    datasheetUrl: "https://www.ti.com/lit/ds/symlink/sn74hc595.pdf",
    priceUsd: 1,
    source: "curated",
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "2-6V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SER", label: "SER", role: "digital_in", voltage: "logic level", notes: "Serial data in" },
      { id: "SRCLK", label: "SRCLK", role: "digital_in", voltage: "logic level", notes: "Shift-register clock" },
      { id: "RCLK", label: "RCLK", role: "digital_in", voltage: "logic level", notes: "Storage (latch) clock" },
      { id: "SRCLR", label: "SRCLR", role: "reset", voltage: "logic level", notes: "Active-low shift-register clear" },
      { id: "OE", label: "OE", role: "digital_in", voltage: "logic level", notes: "Active-low output enable" },
      { id: "QA", label: "QA", role: "digital_out", voltage: "logic level" },
      { id: "QB", label: "QB", role: "digital_out", voltage: "logic level" },
      { id: "QC", label: "QC", role: "digital_out", voltage: "logic level" },
      { id: "QD", label: "QD", role: "digital_out", voltage: "logic level" },
      { id: "QE", label: "QE", role: "digital_out", voltage: "logic level" },
      { id: "QF", label: "QF", role: "digital_out", voltage: "logic level" },
      { id: "QG", label: "QG", role: "digital_out", voltage: "logic level" },
      { id: "QH", label: "QH", role: "digital_out", voltage: "logic level" },
      { id: "QH'", label: "QH'", role: "digital_out", voltage: "logic level", notes: "Cascade out to next 595's SER" },
    ],
  },
  {
    id: "mcp4725-dac",
    label: "MCP4725 12-bit I2C DAC",
    category: "interface",
    summary: "12-bit DAC with internal EEPROM; ratiometric to VDD.",
    logicVoltage: 3.3,
    inputVoltageRange: [2.7, 5.5],
    manufacturer: "Microchip",
    partNumber: "MCP4725",
    datasheetUrl: "https://www.microchip.com/en-us/product/MCP4725",
    priceUsd: 5,
    source: "curated",
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "2.7-5.5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SCL", label: "SCL", role: "i2c_scl", voltage: "logic level" },
      { id: "SDA", label: "SDA", role: "i2c_sda", voltage: "logic level" },
      { id: "A0", label: "A0", role: "digital_in", voltage: "logic level", notes: "Sets I2C address LSB (0x60/0x61)" },
      { id: "VOUT", label: "VOUT", role: "analog_in", notes: "Analog output 0..VDD; treated as analog_in for safety-rules" },
    ],
  },
  {
    id: "drv8833-motor",
    label: "DRV8833 dual H-bridge motor driver",
    category: "actuator",
    summary: "Low-cost dual H-bridge, up to 1.5A/ch (2.5A peak); 2.7-10.8V motor.",
    inputVoltageRange: [2.7, 10.8],
    manufacturer: "Texas Instruments",
    partNumber: "DRV8833",
    datasheetUrl: "https://www.ti.com/product/DRV8833",
    priceUsd: 5,
    source: "curated",
    pins: [
      { id: "VM", label: "VM", role: "power_in", voltage: "2.7-10.8V", notes: "Motor power" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "AIN1", label: "AIN1", role: "digital_in", voltage: "logic level" },
      { id: "AIN2", label: "AIN2", role: "digital_in", voltage: "logic level" },
      { id: "BIN1", label: "BIN1", role: "digital_in", voltage: "logic level" },
      { id: "BIN2", label: "BIN2", role: "digital_in", voltage: "logic level" },
      { id: "AOUT1", label: "AOUT1", role: "power_out" },
      { id: "AOUT2", label: "AOUT2", role: "power_out" },
      { id: "BOUT1", label: "BOUT1", role: "power_out" },
      { id: "BOUT2", label: "BOUT2", role: "power_out" },
      { id: "SLEEP", label: "nSLEEP", role: "digital_in", voltage: "logic level", notes: "Pull high to enable" },
      { id: "FAULT", label: "nFAULT", role: "digital_out", voltage: "logic level", notes: "Open-drain fault flag" },
    ],
    warnings: ["Includes thermal protection; large heat-sink for >1A continuous."],
  },
  {
    id: "l9110-motor",
    label: "L9110S dual motor driver",
    category: "actuator",
    summary: "Cheap dual brushed-motor driver, 0.8A/ch continuous, 2.5-12V.",
    inputVoltageRange: [2.5, 12],
    manufacturer: "Various (clones of L9110S)",
    partNumber: "L9110S",
    datasheetUrl: "https://www.elecrow.com/download/datasheet-l9110.pdf",
    priceUsd: 2,
    source: "curated",
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "2.5-12V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "A-IA", label: "A-IA", role: "digital_in", voltage: "logic level" },
      { id: "A-IB", label: "A-IB", role: "digital_in", voltage: "logic level" },
      { id: "B-IA", label: "B-IA", role: "digital_in", voltage: "logic level" },
      { id: "B-IB", label: "B-IB", role: "digital_in", voltage: "logic level" },
      { id: "MOTOR-A1", label: "Motor A+", role: "power_out" },
      { id: "MOTOR-A2", label: "Motor A-", role: "power_out" },
      { id: "MOTOR-B1", label: "Motor B+", role: "power_out" },
      { id: "MOTOR-B2", label: "Motor B-", role: "power_out" },
    ],
    warnings: ["Cheaper but lossy (~1V drop). Prefer DRV8833 for >0.5A or efficiency-sensitive builds."],
  },
  {
    id: "scd30-co2",
    label: "SCD30 NDIR CO2 / temp / humidity sensor",
    category: "sensor",
    summary: "True NDIR CO2 (400-10000ppm) with temperature and humidity; I2C or UART.",
    logicVoltage: 3.3,
    inputVoltageRange: [3.3, 5.5],
    manufacturer: "Sensirion",
    partNumber: "SCD30",
    datasheetUrl: "https://sensirion.com/products/catalog/SCD30/",
    priceUsd: 50,
    source: "curated",
    pins: [
      { id: "VDD", label: "VDD", role: "power_in", voltage: "3.3-5.5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SCL", label: "SCL", role: "i2c_scl", voltage: "3.3V" },
      { id: "SDA", label: "SDA", role: "i2c_sda", voltage: "3.3V" },
      { id: "RDY", label: "RDY", role: "digital_out", voltage: "3.3V", notes: "Data-ready interrupt" },
      { id: "SEL", label: "SEL", role: "digital_in", voltage: "3.3V", notes: "Interface select: float=I2C, GND=UART" },
    ],
    warnings: ["Self-heats; place away from MCU and other heat sources for accurate readings."],
  },
  {
    id: "ens160-airquality",
    label: "ENS160 multi-gas air-quality sensor",
    category: "sensor",
    summary: "TVOC/eCO2/AQI (UBA, BME) over I2C; modern CCS811 replacement.",
    logicVoltage: 3.3,
    inputVoltageRange: [1.71, 3.6],
    manufacturer: "ScioSense",
    partNumber: "ENS160",
    datasheetUrl: "https://www.sciosense.com/products/environmental-sensors/ens160-digital-metal-oxide-multi-gas-sensor/",
    priceUsd: 18,
    source: "curated",
    pins: [
      { id: "VDD", label: "VDD", role: "power_in", voltage: "1.71-3.6V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SCL", label: "SCL", role: "i2c_scl", voltage: "3.3V" },
      { id: "SDA", label: "SDA", role: "i2c_sda", voltage: "3.3V" },
      { id: "INT", label: "INT", role: "digital_out", voltage: "3.3V" },
      { id: "ADDR", label: "ADDR", role: "digital_in", voltage: "3.3V", notes: "Sets I2C address (0x52/0x53)" },
    ],
  },
  {
    id: "bts7960-motor",
    label: "BTS7960 high-current half-bridge driver",
    category: "actuator",
    summary: "43A peak half-bridge (common on robotics); built-in current sense.",
    inputVoltageRange: [5.5, 27],
    manufacturer: "Infineon",
    partNumber: "BTS7960",
    datasheetUrl: "https://www.infineon.com/dgdl/Infineon-BTS7960-DS-v01_00-EN.pdf",
    priceUsd: 8,
    source: "curated",
    pins: [
      { id: "VCC", label: "VCC (logic)", role: "power_in", voltage: "5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "B+", label: "B+", role: "power_in", voltage: "5.5-27V", notes: "Motor supply +" },
      { id: "B-", label: "B-", role: "gnd", notes: "Motor supply return" },
      { id: "RPWM", label: "RPWM", role: "pwm", voltage: "logic level" },
      { id: "LPWM", label: "LPWM", role: "pwm", voltage: "logic level" },
      { id: "R_EN", label: "R_EN", role: "digital_in", voltage: "logic level" },
      { id: "L_EN", label: "L_EN", role: "digital_in", voltage: "logic level" },
      { id: "R_IS", label: "R_IS", role: "analog_in", notes: "Right half-bridge current sense" },
      { id: "L_IS", label: "L_IS", role: "analog_in", notes: "Left half-bridge current sense" },
      { id: "M+", label: "M+", role: "power_out" },
      { id: "M-", label: "M-", role: "power_out" },
    ],
    warnings: [
      "Heatsink mandatory above ~10A continuous.",
      "Two BTS7960 paired form a full H-bridge for bidirectional drive.",
    ],
  },

  // ---- WAVE 2: more web-verified + spec-curated entries ----
  {
    id: "max98357a-i2s-amp",
    label: "MAX98357A I2S Class-D mono amp",
    category: "actuator",
    summary: "I2S audio input, Class-D 3.2W into 4Ω; no DAC needed.",
    inputVoltageRange: [2.5, 5.5],
    manufacturer: "Maxim Integrated",
    partNumber: "MAX98357A",
    datasheetUrl: "https://learn.adafruit.com/adafruit-max98357-i2s-class-d-mono-amp/pinouts",
    priceUsd: 6,
    source: "curated",
    pins: [
      { id: "VIN", label: "VIN", role: "power_in", voltage: "2.5-5.5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "LRC", label: "LRC", role: "digital_in", voltage: "3.3-5V", notes: "I2S left/right clock (word select)" },
      { id: "BCLK", label: "BCLK", role: "digital_in", voltage: "3.3-5V", notes: "I2S bit clock" },
      { id: "DIN", label: "DIN", role: "digital_in", voltage: "3.3-5V", notes: "I2S data" },
      { id: "GAIN", label: "GAIN", role: "digital_in", notes: "Sets amplification via resistor to GND or VIN" },
      { id: "SD", label: "SD", role: "digital_in", notes: "Shutdown + channel selection" },
      { id: "SPK+", label: "SPK+", role: "power_out", notes: "Bridge-tied speaker output" },
      { id: "SPK-", label: "SPK-", role: "power_out", notes: "Bridge-tied speaker output" },
    ],
    warnings: ["Min 4Ω speaker. SD has internal 100K pulldown — float gives left channel."],
  },
  {
    id: "bno055-imu",
    label: "BNO055 9-DOF orientation sensor",
    category: "sensor",
    summary: "Accelerometer + gyro + magnetometer + on-chip sensor fusion; absolute orientation.",
    logicVoltage: 3.3,
    inputVoltageRange: [3.3, 5],
    manufacturer: "Bosch",
    partNumber: "BNO055",
    datasheetUrl: "https://learn.adafruit.com/adafruit-bno055-absolute-orientation-sensor/pinouts",
    priceUsd: 30,
    source: "curated",
    pins: [
      { id: "VIN", label: "VIN", role: "power_in", voltage: "3.3-5V" },
      { id: "3VO", label: "3VO", role: "power_out", voltage: "3.3V", notes: "On-board LDO output" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SCL", label: "SCL", role: "i2c_scl", voltage: "3.3V or 5V" },
      { id: "SDA", label: "SDA", role: "i2c_sda", voltage: "3.3V or 5V" },
      { id: "RST", label: "RST", role: "reset", notes: "Pull low then high to reset" },
      { id: "INT", label: "INT", role: "digital_out", voltage: "3.3V" },
      { id: "ADR", label: "ADR", role: "digital_in", notes: "I2C address select" },
      { id: "PS0", label: "PS0", role: "digital_in", notes: "Protocol select (typically float for I2C)" },
      { id: "PS1", label: "PS1", role: "digital_in", notes: "Protocol select" },
    ],
    warnings: ["Fusion mode requires calibration — gyro/accel/mag stable for accurate orientation."],
  },
  {
    id: "mcp23017-ioexp",
    label: "MCP23017 16-channel I2C GPIO expander",
    category: "interface",
    summary: "16 GPIO over I2C with per-bank interrupts; up to 25mA per pin.",
    logicVoltage: 5,
    inputVoltageRange: [1.8, 5.5],
    manufacturer: "Microchip",
    partNumber: "MCP23017",
    datasheetUrl: "https://learn.adafruit.com/adafruit-mcp23017-i2c-gpio-expander/pinouts",
    priceUsd: 4,
    source: "curated",
    pins: [
      { id: "VIN", label: "VIN", role: "power_in", voltage: "1.8-5.5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SCL", label: "SCL", role: "i2c_scl", voltage: "3.3V or 5V" },
      { id: "SDA", label: "SDA", role: "i2c_sda", voltage: "3.3V or 5V" },
      { id: "RST", label: "RST", role: "reset", notes: "Active-low; ground to reset" },
      { id: "INTA", label: "INTA", role: "digital_out", notes: "Interrupt for PORTA pin changes" },
      { id: "INTB", label: "INTB", role: "digital_out", notes: "Interrupt for PORTB pin changes" },
      { id: "A0", label: "A0", role: "digital_in", notes: "I2C address bit 0" },
      { id: "A1", label: "A1", role: "digital_in", notes: "I2C address bit 1" },
      { id: "A2", label: "A2", role: "digital_in", notes: "I2C address bit 2" },
      ...Array.from({ length: 8 }, (_, i) => ({ id: `GPA${i}`, label: `GPA${i}`, role: "digital_io" as const, notes: "PORTA pin" })),
      ...Array.from({ length: 8 }, (_, i) => ({ id: `GPB${i}`, label: `GPB${i}`, role: "digital_io" as const, notes: "PORTB pin" })),
    ],
  },
  {
    id: "vl6180x-tof",
    label: "VL6180X short-range ToF + ambient light",
    category: "sensor",
    summary: "Time-of-flight ranging up to 10cm + lux measurement; I2C @ fixed 0x29.",
    logicVoltage: 3.3,
    inputVoltageRange: [3, 5],
    manufacturer: "STMicroelectronics",
    partNumber: "VL6180X",
    datasheetUrl: "https://learn.adafruit.com/adafruit-vl6180x-time-of-flight-micro-lidar-distance-sensor-breakout/pinouts",
    priceUsd: 12,
    source: "curated",
    pins: [
      { id: "VIN", label: "VIN", role: "power_in", voltage: "3-5V" },
      { id: "2V8", label: "2V8", role: "power_out", voltage: "2.8V", currentMaxMa: 100 },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SCL", label: "SCL", role: "i2c_scl" },
      { id: "SDA", label: "SDA", role: "i2c_sda" },
      { id: "GPIO", label: "GPIO", role: "digital_out", voltage: "2.8V", notes: "Data-ready signal; may not be readable on 5V MCUs" },
      { id: "XSHUT", label: "XSHUT", role: "digital_in", notes: "Pull low to shut down; level-shifted for 3-5V" },
    ],
    warnings: ["Fixed I2C address 0x29 — can't change. Use XSHUT for multi-sensor boards."],
  },
  {
    id: "tb6612fng-motor",
    label: "TB6612FNG dual H-bridge motor driver",
    category: "actuator",
    summary: "Modern dual H-bridge replacement for L298N; 1.2A/ch continuous, 3.2A peak.",
    inputVoltageRange: [2.7, 13.5],
    manufacturer: "Toshiba",
    partNumber: "TB6612FNG",
    datasheetUrl: "https://www.sparkfun.com/products/14450",
    priceUsd: 4,
    source: "curated",
    pins: [
      { id: "VM", label: "VM", role: "power_in", voltage: "2.5-13.5V", notes: "Motor supply" },
      { id: "VCC", label: "VCC", role: "power_in", voltage: "2.7-5.5V", notes: "Logic supply" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "AIN1", label: "AIN1", role: "digital_in", voltage: "logic level" },
      { id: "AIN2", label: "AIN2", role: "digital_in", voltage: "logic level" },
      { id: "BIN1", label: "BIN1", role: "digital_in", voltage: "logic level" },
      { id: "BIN2", label: "BIN2", role: "digital_in", voltage: "logic level" },
      { id: "PWMA", label: "PWMA", role: "pwm", voltage: "logic level" },
      { id: "PWMB", label: "PWMB", role: "pwm", voltage: "logic level" },
      { id: "STBY", label: "STBY", role: "digital_in", voltage: "logic level", notes: "Pull high to enable; low standby" },
      { id: "AO1", label: "AO1", role: "power_out" },
      { id: "AO2", label: "AO2", role: "power_out" },
      { id: "BO1", label: "BO1", role: "power_out" },
      { id: "BO2", label: "BO2", role: "power_out" },
    ],
    warnings: ["Much more efficient than L298N — prefer for any new build under 1A continuous."],
  },
  {
    id: "lc709203f-fuel-gauge",
    label: "LC709203F LiPo battery fuel gauge",
    category: "power",
    summary: "I2C single-cell LiPo state-of-charge tracking; with temperature input.",
    logicVoltage: 3.3,
    inputVoltageRange: [3, 5],
    manufacturer: "ON Semiconductor",
    partNumber: "LC709203F",
    datasheetUrl: "https://learn.adafruit.com/adafruit-lc709203f-lipo-lipoly-battery-monitor/pinouts",
    priceUsd: 8,
    source: "curated",
    pins: [
      { id: "VIN", label: "VIN", role: "power_in", voltage: "3-5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SCL", label: "SCL", role: "i2c_scl" },
      { id: "SDA", label: "SDA", role: "i2c_sda" },
      { id: "INT", label: "INT", role: "digital_out", notes: "Low when below threshold; pulled up to VIN" },
      { id: "THERM", label: "THERM", role: "analog_in", notes: "Connect a 10K thermistor for pack temperature" },
      { id: "BAT", label: "BAT", role: "power_in", voltage: "Li-cell voltage", notes: "JST: cell positive" },
      { id: "BAT-", label: "BAT-", role: "gnd", notes: "JST: cell negative" },
    ],
    warnings: ["Single-cell LiPo only. Disable on-board LED to extend battery life."],
  },
  {
    id: "qtpy-esp32s3",
    label: "Adafruit QT Py ESP32-S3",
    category: "mcu",
    summary: "Tiny ESP32-S3 dev board (Seeed Xiao footprint); WiFi+BT, 13 GPIO, STEMMA QT.",
    logicVoltage: 3.3,
    inputVoltageRange: [3, 5],
    manufacturer: "Adafruit / Espressif ESP32-S3",
    partNumber: "ESP32-S3",
    datasheetUrl: "https://www.adafruit.com/product/5426",
    priceUsd: 15,
    source: "curated",
    pins: [
      { id: "VBUS", label: "VBUS", role: "power_in", voltage: "5V (USB)" },
      { id: "3V3", label: "3V3", role: "power_out", voltage: "3.3V", currentMaxMa: 600 },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "TX", label: "TX", role: "uart_tx", voltage: "3.3V" },
      { id: "RX", label: "RX", role: "uart_rx", voltage: "3.3V" },
      { id: "SCL", label: "SCL", role: "i2c_scl", voltage: "3.3V" },
      { id: "SDA", label: "SDA", role: "i2c_sda", voltage: "3.3V" },
      { id: "MOSI", label: "MOSI", role: "spi_mosi", voltage: "3.3V" },
      { id: "MISO", label: "MISO", role: "spi_miso", voltage: "3.3V" },
      { id: "SCK", label: "SCK", role: "spi_sck", voltage: "3.3V" },
      { id: "A0", label: "A0", role: "analog_in", voltage: "0-3.3V" },
      { id: "A1", label: "A1", role: "analog_in", voltage: "0-3.3V" },
      { id: "A2", label: "A2", role: "analog_in", voltage: "0-3.3V" },
      { id: "A3", label: "A3", role: "analog_in", voltage: "0-3.3V" },
    ],
  },

  // ---- SPEC-CURATED (well-known stable parts) ----
  {
    id: "max30102-pulse-ox",
    label: "MAX30102 pulse oximeter / heart-rate",
    category: "sensor",
    summary: "Integrated red + IR LEDs + photodetector for SpO2 and heart-rate; I2C.",
    logicVoltage: 3.3,
    inputVoltageRange: [1.7, 2.0],
    manufacturer: "Maxim Integrated",
    partNumber: "MAX30102",
    datasheetUrl: "https://www.analog.com/en/products/max30102.html",
    priceUsd: 8,
    source: "curated",
    pins: [
      { id: "VIN", label: "VIN", role: "power_in", voltage: "1.8-5V (most breakouts have 5V-tolerant LDO)" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SCL", label: "SCL", role: "i2c_scl" },
      { id: "SDA", label: "SDA", role: "i2c_sda" },
      { id: "INT", label: "INT", role: "digital_out", notes: "FIFO almost-full or new-sample interrupt" },
      { id: "RD", label: "RD", role: "other", notes: "Red LED cathode return — typically internal on breakouts" },
      { id: "IRD", label: "IRD", role: "other", notes: "IR LED cathode return — typically internal" },
    ],
    warnings: ["Skin contact and stillness required for SpO2; algorithm matters more than the sensor."],
  },
  {
    id: "tmc2209-stepper",
    label: "TMC2209 silent stepper driver",
    category: "actuator",
    summary: "256-microstep StealthChop driver; quiet vs A4988/DRV8825; UART tuning.",
    inputVoltageRange: [4.75, 29],
    manufacturer: "Trinamic",
    partNumber: "TMC2209",
    datasheetUrl: "https://www.trinamic.com/products/integrated-circuits/details/tmc2209-la/",
    priceUsd: 6,
    source: "curated",
    pins: [
      { id: "VM", label: "VM", role: "power_in", voltage: "4.75-29V", notes: "Motor supply" },
      { id: "VIO", label: "VIO", role: "power_in", voltage: "3-5V", notes: "Logic supply" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "EN", label: "EN", role: "digital_in", notes: "Active-low enable" },
      { id: "STEP", label: "STEP", role: "digital_in" },
      { id: "DIR", label: "DIR", role: "digital_in" },
      { id: "MS1", label: "MS1", role: "digital_in", notes: "Microstep / UART address" },
      { id: "MS2", label: "MS2", role: "digital_in", notes: "Microstep / UART address" },
      { id: "PDN_UART", label: "PDN/UART", role: "uart_rx", notes: "Half-duplex UART for runtime tuning" },
      { id: "DIAG", label: "DIAG", role: "digital_out", notes: "StallGuard / fault" },
      { id: "INDEX", label: "INDEX", role: "digital_out", notes: "Full-step indicator" },
      { id: "M1A", label: "M1A", role: "power_out", notes: "Coil 1" },
      { id: "M1B", label: "M1B", role: "power_out", notes: "Coil 1" },
      { id: "M2A", label: "M2A", role: "power_out", notes: "Coil 2" },
      { id: "M2B", label: "M2B", role: "power_out", notes: "Coil 2" },
      { id: "VREF", label: "VREF", role: "analog_in", notes: "Current limit reference (or set via UART)" },
    ],
    warnings: ["Always power VM before sending STEP pulses. Set VREF for your motor BEFORE running."],
  },
  {
    id: "scd41-co2",
    label: "SCD41 photoacoustic CO2 sensor",
    category: "sensor",
    summary: "True NDIR-grade CO2 (400-5000ppm) + temp + RH in a small SMD package; I2C.",
    logicVoltage: 3.3,
    inputVoltageRange: [2.4, 5.5],
    manufacturer: "Sensirion",
    partNumber: "SCD41",
    datasheetUrl: "https://sensirion.com/products/catalog/SCD41/",
    priceUsd: 35,
    source: "curated",
    pins: [
      { id: "VDD", label: "VDD", role: "power_in", voltage: "2.4-5.5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SCL", label: "SCL", role: "i2c_scl", voltage: "3.3V" },
      { id: "SDA", label: "SDA", role: "i2c_sda", voltage: "3.3V" },
    ],
    warnings: ["Self-calibrates via periodic ambient exposure; ventilate occasionally for accuracy."],
  },
  {
    id: "limit-switch-3pin",
    label: "3-pin mechanical limit switch",
    category: "sensor",
    summary: "NC/NO endstop with common — typical printer/CNC limit switch.",
    logicVoltage: 5,
    inputVoltageRange: [3.3, 5],
    manufacturer: "Generic",
    partNumber: "KW12-3",
    priceUsd: 1,
    source: "curated",
    capabilityTags: ["switch_or_button", "sensor_or_adc", "mechanical_motion"],
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3-5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SIG", label: "SIG", role: "digital_out", voltage: "logic level", notes: "Active when triggered (module-dependent)" },
    ],
  },
  {
    id: "esp32-cam-module",
    label: "ESP32-CAM (OV2640)",
    category: "mcu",
    summary: "ESP32-S with OV2640 camera — 5V in, 3.3V logic, Wi-Fi capture module.",
    logicVoltage: 3.3,
    inputVoltageRange: [5, 5],
    manufacturer: "Espressif / AI-Thinker",
    partNumber: "ESP32-CAM",
    datasheetUrl: "https://github.com/espressif/esp32-camera",
    priceUsd: 10,
    source: "curated",
    capabilityTags: ["controller", "camera_or_vision", "wireless", "network_interface"],
    pins: [
      { id: "5V", label: "5V", role: "power_in", voltage: "5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "U0T", label: "U0T", role: "uart_tx", voltage: "3.3V", notes: "GPIO1 — programming UART" },
      { id: "U0R", label: "U0R", role: "uart_rx", voltage: "3.3V", notes: "GPIO3" },
      { id: "GPIO4", label: "GPIO4", role: "digital_io", voltage: "3.3V", notes: "Flash LED / aux" },
      { id: "GPIO12", label: "GPIO12", role: "digital_io", voltage: "3.3V" },
      { id: "GPIO13", label: "GPIO13", role: "digital_io", voltage: "3.3V" },
    ],
    warnings: ["GPIO0 must be held correctly for flashing. Use separate 5V supply ≥500mA for stable capture."],
  },
];
