// AUTO-GENERATED from knowledge_base/{boards,components}/*.json by
// scripts/ingest_knowledge_base.py — adds full-board pinouts (Arduino Uno,
// Nano V3, ESP32 DevKit V1, RPi 4B) and the common-IC catalog (NE555, LM317,
// LM7805). Re-run to refresh.

import type { ModuleSpec } from "./module-library";

export const INGESTED_KB: ModuleSpec[] = [
  {
    id: "arduino_nano_v3_board",
    label: "Arduino Nano V3",
    category: "mcu",
    summary: "Arduino Nano V3 pinout — 30 GPIO, 5V logic",
    inputVoltageRange: [7, 12],
    logicVoltage: 5,
    pins: [
      { id: "D1/TX", label: "D1/TX", role: "uart_tx" },
      { id: "D0/RX", label: "D0/RX", role: "uart_rx" },
      { id: "RST", label: "RST", role: "reset" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "D2", label: "D2", role: "digital_io" },
      { id: "D3", label: "D3", role: "digital_io" },
      { id: "D4", label: "D4", role: "digital_io" },
      { id: "D5", label: "D5", role: "digital_io" },
      { id: "D6", label: "D6", role: "digital_io" },
      { id: "D7", label: "D7", role: "digital_io" },
      { id: "D8", label: "D8", role: "digital_io" },
      { id: "D9", label: "D9", role: "digital_io" },
      { id: "D10", label: "D10", role: "digital_io" },
      { id: "D11", label: "D11", role: "digital_io" },
      { id: "D12", label: "D12", role: "digital_io" },
      { id: "D13", label: "D13", role: "digital_io" },
      { id: "3V3", label: "3V3", role: "power_out" },
      { id: "AREF", label: "AREF", role: "analog_in" },
      { id: "A0", label: "A0", role: "analog_in" },
      { id: "A1", label: "A1", role: "analog_in" },
      { id: "A2", label: "A2", role: "analog_in" },
      { id: "A3", label: "A3", role: "analog_in" },
      { id: "A4", label: "A4", role: "analog_in" },
      { id: "A5", label: "A5", role: "analog_in" },
      { id: "A6", label: "A6", role: "analog_in" },
      { id: "A7", label: "A7", role: "analog_in" },
      { id: "5V", label: "5V", role: "power_out" },
      { id: "VIN", label: "VIN", role: "power_in" },
    ],
    source: "ingested-kb-board",
  },
  {
    id: "arduino_uno_r3_board",
    label: "Arduino Uno R3",
    category: "mcu",
    summary: "Arduino Uno R3 pinout — ? GPIO, 5V logic",
    logicVoltage: 5,
    pins: [
      { id: "D13", label: "D13", role: "digital_io" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "AREF", label: "AREF", role: "analog_in" },
      { id: "SDA", label: "SDA", role: "i2c_sda" },
      { id: "SCL", label: "SCL", role: "i2c_scl" },
      { id: "D12", label: "D12", role: "digital_io" },
      { id: "D11", label: "D11", role: "digital_io" },
      { id: "D10", label: "D10", role: "digital_io" },
      { id: "D9", label: "D9", role: "digital_io" },
      { id: "D8", label: "D8", role: "digital_io" },
      { id: "D0", label: "D0", role: "digital_io" },
      { id: "D1", label: "D1", role: "digital_io" },
      { id: "D2", label: "D2", role: "digital_io" },
      { id: "D3", label: "D3", role: "digital_io" },
      { id: "D4", label: "D4", role: "digital_io" },
      { id: "D5", label: "D5", role: "digital_io" },
      { id: "D6", label: "D6", role: "digital_io" },
      { id: "D7", label: "D7", role: "digital_io" },
      { id: "A0", label: "A0", role: "analog_in" },
      { id: "A1", label: "A1", role: "analog_in" },
      { id: "A2", label: "A2", role: "analog_in" },
      { id: "A3", label: "A3", role: "analog_in" },
      { id: "A4", label: "A4", role: "analog_in" },
      { id: "A5", label: "A5", role: "analog_in" },
      { id: "IOREF", label: "IOREF", role: "power_out" },
      { id: "RESET", label: "RESET", role: "reset" },
      { id: "3V3", label: "3V3", role: "power_out" },
      { id: "5V", label: "5V", role: "power_out" },
      { id: "GND_1", label: "GND_1", role: "other" },
      { id: "GND_2", label: "GND_2", role: "other" },
      { id: "VIN", label: "VIN", role: "power_in" },
    ],
    source: "ingested-kb-board",
  },
  {
    id: "esp32_devkit_v1_board",
    label: "ESP32 DevKit V1",
    category: "mcu",
    summary: "ESP32 DevKit V1 pinout — 30 GPIO, 3.3V logic",
    logicVoltage: 3.3,
    pins: [
      { id: "EN", label: "EN", role: "reset" },
      { id: "VP", label: "VP", role: "other" },
      { id: "VN", label: "VN", role: "other" },
      { id: "D34", label: "D34", role: "digital_io" },
      { id: "D35", label: "D35", role: "digital_io" },
      { id: "D32", label: "D32", role: "digital_io" },
      { id: "D33", label: "D33", role: "digital_io" },
      { id: "D25", label: "D25", role: "digital_io" },
      { id: "D26", label: "D26", role: "digital_io" },
      { id: "D27", label: "D27", role: "digital_io" },
      { id: "D14", label: "D14", role: "digital_io" },
      { id: "D12", label: "D12", role: "digital_io" },
      { id: "D13", label: "D13", role: "digital_io" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "VIN", label: "VIN", role: "power_in" },
      { id: "D23", label: "D23", role: "digital_io" },
      { id: "D22", label: "D22", role: "digital_io" },
      { id: "TX0", label: "TX0", role: "uart_tx" },
      { id: "RX0", label: "RX0", role: "uart_rx" },
      { id: "D21", label: "D21", role: "digital_io" },
      { id: "D19", label: "D19", role: "digital_io" },
      { id: "D18", label: "D18", role: "digital_io" },
      { id: "D5", label: "D5", role: "digital_io" },
      { id: "D17", label: "D17", role: "digital_io" },
      { id: "D16", label: "D16", role: "digital_io" },
      { id: "D4", label: "D4", role: "digital_io" },
      { id: "D0", label: "D0", role: "digital_io" },
      { id: "D2", label: "D2", role: "digital_io" },
      { id: "D15", label: "D15", role: "digital_io" },
    ],
    source: "ingested-kb-board",
  },
  {
    id: "raspberry_pi_4b_board",
    label: "Raspberry Pi 4 Model B",
    category: "mcu",
    summary: "Raspberry Pi 4 Model B pinout — 40 GPIO, 3.3V logic",
    logicVoltage: 3.3,
    pins: [
      { id: "3V3", label: "3V3", role: "power_out" },
      { id: "5V", label: "5V", role: "power_out" },
      { id: "GPIO2", label: "GPIO2", role: "digital_io" },
      { id: "GPIO3", label: "GPIO3", role: "digital_io" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "GPIO4", label: "GPIO4", role: "digital_io" },
      { id: "TXD", label: "TXD", role: "uart_tx" },
      { id: "RXD", label: "RXD", role: "uart_rx" },
      { id: "GPIO17", label: "GPIO17", role: "digital_io" },
      { id: "GPIO18", label: "GPIO18", role: "digital_io" },
      { id: "GPIO27", label: "GPIO27", role: "digital_io" },
      { id: "GPIO22", label: "GPIO22", role: "digital_io" },
      { id: "GPIO23", label: "GPIO23", role: "digital_io" },
      { id: "GPIO24", label: "GPIO24", role: "digital_io" },
      { id: "GPIO10", label: "GPIO10", role: "digital_io" },
      { id: "GPIO9", label: "GPIO9", role: "digital_io" },
      { id: "GPIO25", label: "GPIO25", role: "digital_io" },
      { id: "GPIO11", label: "GPIO11", role: "digital_io" },
      { id: "GPIO8", label: "GPIO8", role: "digital_io" },
      { id: "GPIO7", label: "GPIO7", role: "digital_io" },
      { id: "ID_SD", label: "ID_SD", role: "other" },
      { id: "ID_SC", label: "ID_SC", role: "other" },
      { id: "GPIO5", label: "GPIO5", role: "digital_io" },
      { id: "GPIO6", label: "GPIO6", role: "digital_io" },
      { id: "GPIO12", label: "GPIO12", role: "digital_io" },
      { id: "GPIO13", label: "GPIO13", role: "digital_io" },
      { id: "GPIO19", label: "GPIO19", role: "digital_io" },
      { id: "GPIO16", label: "GPIO16", role: "digital_io" },
      { id: "GPIO26", label: "GPIO26", role: "digital_io" },
      { id: "GPIO20", label: "GPIO20", role: "digital_io" },
      { id: "GPIO21", label: "GPIO21", role: "digital_io" },
    ],
    source: "ingested-kb-board",
  },
  {
    id: "ne555",
    label: "Precision Timer IC",
    category: "interface",
    summary: "Precision timer IC, DIP-8.",
    inputVoltageRange: [4.5, 16.0],
    manufacturer: "Texas Instruments",
    partNumber: "NE555",
    datasheetUrl: "https://www.ti.com/product/NE555",
    pins: [
      { id: "GND", label: "GND", role: "gnd", notes: "Pin 1: Ground" },
      { id: "TRIG", label: "TRIG", role: "digital_in", notes: "Pin 2: Trigger input (active low, below 1/3 VCC)" },
      { id: "OUT", label: "OUT", role: "digital_out", notes: "Pin 3: Timer output" },
      { id: "RESET", label: "RESET", role: "reset", notes: "Pin 4: Active-low reset" },
      { id: "CTRL", label: "CTRL", role: "analog_in", notes: "Pin 5: Control voltage (typically bypassed)" },
      { id: "THRES", label: "THRES", role: "analog_in", notes: "Pin 6: Threshold input" },
      { id: "DISCH", label: "DISCH", role: "digital_out", notes: "Pin 7: Discharge — open collector to GND" },
      { id: "VCC", label: "VCC", role: "power_in", notes: "Pin 8: Supply 4.5-16V" },
    ],
    source: "ingested-kb-ic",
  },
  {
    id: "lm317",
    label: "Adjustable Voltage Regulator",
    category: "power",
    summary: "Adjustable linear voltage regulator, 1.5A.",
    inputVoltageRange: [3.0, 40.0],
    manufacturer: "Texas Instruments",
    partNumber: "LM317",
    datasheetUrl: "https://www.ti.com/product/LM317",
    pins: [
      { id: "ADJ", label: "ADJ", role: "analog_in", notes: "Adjust pin (resistor divider sets VOUT)" },
      { id: "VOUT", label: "VOUT", role: "power_out", notes: "Regulated output (1.25-37V)" },
      { id: "VIN", label: "VIN", role: "power_in", notes: "Unregulated input" },
    ],
    source: "ingested-kb-ic",
  },
];
