// Ingested from data/datasheets/*.pdf via pdftotext + manual cleanup.
// Five common discrete parts not covered by earlier ingest passes.

import type { ModuleSpec } from "./module-library";

export const INGESTED_DATASHEETS: ModuleSpec[] = [
  {
    id: "2n2222-bjt",
    label: "2N2222 NPN BJT",
    category: "actuator",
    summary: "General-purpose NPN bipolar transistor, TO-92, ~800mA collector current.",
    manufacturer: "ON Semiconductor / various",
    partNumber: "2N2222",
    datasheetUrl: "https://www.onsemi.com/pdf/datasheet/2n2222-d.pdf",
    source: "ingested-datasheet-pdf",
    pins: [
      { id: "E", label: "Emitter", role: "gnd", notes: "TO-92 pin 1 (flat side facing, leftmost). Typically to GND in NPN low-side switching." },
      { id: "B", label: "Base", role: "digital_in", notes: "Pin 2 (middle). Drive through ~1k resistor from MCU GPIO." },
      { id: "C", label: "Collector", role: "power_out", notes: "Pin 3 (rightmost). Connect to load; load other end to VCC." },
    ],
    warnings: [
      "Pinout differs by manufacturer/case — verify against your specific part's datasheet.",
      "Not a logic-level part; for direct 3.3V/5V drive of large loads prefer a MOSFET.",
    ],
  },
  {
    id: "bc547-bjt",
    label: "BC547 NPN BJT",
    category: "actuator",
    summary: "Common European general-purpose NPN BJT, TO-92, ~100mA collector current.",
    manufacturer: "ON Semiconductor / NXP / various",
    partNumber: "BC547",
    datasheetUrl: "https://www.onsemi.com/pdf/datasheet/bc550-d.pdf",
    source: "ingested-datasheet-pdf",
    pins: [
      { id: "C", label: "Collector", role: "power_out", notes: "TO-92 pin 1 (flat side facing, leftmost). NOTE: BC547 pinout is C-B-E, not E-B-C like 2N2222." },
      { id: "B", label: "Base", role: "digital_in", notes: "Pin 2 (middle)." },
      { id: "E", label: "Emitter", role: "gnd", notes: "Pin 3 (rightmost)." },
    ],
    warnings: ["BC547 pinout is C-B-E — opposite of 2N2222. Double-check before populating a board."],
  },
  {
    id: "4n35-optocoupler",
    label: "4N35 phototransistor optocoupler",
    category: "interface",
    summary: "Logic isolation between two circuits; DIP-6; 5300V isolation.",
    manufacturer: "Vishay / Fairchild / various",
    partNumber: "4N35",
    datasheetUrl: "https://www.vishay.com/docs/81181/4n35.pdf",
    source: "ingested-datasheet-pdf",
    pins: [
      { id: "ANODE", label: "Anode (1)", role: "digital_in", notes: "Input-side LED anode; drive via current-limit resistor from source MCU." },
      { id: "CATHODE", label: "Cathode (2)", role: "gnd", notes: "Input-side LED cathode; tie to input-circuit ground." },
      { id: "NC", label: "NC (3)", role: "other", notes: "Not internally connected." },
      { id: "EMITTER", label: "Emitter (4)", role: "gnd", notes: "Output-side transistor emitter; tie to output-circuit ground." },
      { id: "COLLECTOR", label: "Collector (5)", role: "power_out", notes: "Output-side transistor collector; pulled high through external resistor." },
      { id: "BASE", label: "Base (6)", role: "other", notes: "Usually left floating in basic on/off isolation." },
    ],
    warnings: ["Provides galvanic isolation — never share grounds between input and output sides."],
  },
  {
    id: "at24c32-eeprom",
    label: "AT24C32 32Kbit I2C EEPROM",
    category: "interface",
    summary: "I2C serial EEPROM, 4096 x 8-bit, DIP-8 / TSSOP-8.",
    manufacturer: "Microchip / Atmel",
    partNumber: "AT24C32",
    datasheetUrl: "https://ww1.microchip.com/downloads/en/devicedoc/doc0336.pdf",
    inputVoltageRange: [1.8, 5.5],
    source: "ingested-datasheet-pdf",
    pins: [
      { id: "A0", label: "A0", role: "digital_in", notes: "Address input bit 0 — sets I2C address (0x50-0x57)." },
      { id: "A1", label: "A1", role: "digital_in", notes: "Address input bit 1." },
      { id: "A2", label: "A2", role: "digital_in", notes: "Address input bit 2." },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SDA", label: "SDA", role: "i2c_sda", voltage: "1.8-5.5V" },
      { id: "SCL", label: "SCL", role: "i2c_scl", voltage: "1.8-5.5V" },
      { id: "WP", label: "WP", role: "digital_in", notes: "Write-protect; tie to VCC to make the chip read-only." },
      { id: "VCC", label: "VCC", role: "power_in", voltage: "1.8-5.5V" },
    ],
  },
  {
    id: "atmega328p-mcu",
    label: "ATmega328P (Arduino Uno/Nano core)",
    category: "mcu",
    summary: "8-bit AVR MCU, 32KB flash, 2KB SRAM, 23 GPIO, PDIP-28 or TQFP-32.",
    manufacturer: "Microchip / Atmel",
    partNumber: "ATmega328P",
    datasheetUrl: "https://ww1.microchip.com/downloads/aemDocuments/documents/MCU08/ProductDocuments/DataSheets/ATmega48A-PA-88A-PA-168A-PA-328-P-DS-DS40002061B.pdf",
    inputVoltageRange: [1.8, 5.5],
    logicVoltage: 5,
    source: "ingested-datasheet-pdf",
    pins: [
      { id: "PD0", label: "PD0/RXD", role: "uart_rx", voltage: "logic level" },
      { id: "PD1", label: "PD1/TXD", role: "uart_tx", voltage: "logic level" },
      { id: "PD2", label: "PD2/INT0", role: "digital_io", voltage: "logic level" },
      { id: "PD3", label: "PD3/INT1/OC2B", role: "digital_io", voltage: "logic level", notes: "PWM-capable" },
      { id: "PD4", label: "PD4/T0/XCK", role: "digital_io", voltage: "logic level" },
      { id: "PD5", label: "PD5/T1/OC0B", role: "digital_io", voltage: "logic level", notes: "PWM-capable" },
      { id: "PD6", label: "PD6/AIN0/OC0A", role: "digital_io", voltage: "logic level", notes: "PWM-capable" },
      { id: "PD7", label: "PD7/AIN1", role: "digital_io", voltage: "logic level" },
      { id: "PB0", label: "PB0/ICP1", role: "digital_io", voltage: "logic level" },
      { id: "PB1", label: "PB1/OC1A", role: "digital_io", voltage: "logic level", notes: "PWM-capable" },
      { id: "PB2", label: "PB2/SS/OC1B", role: "digital_io", voltage: "logic level", notes: "SPI SS / PWM-capable" },
      { id: "PB3", label: "PB3/MOSI/OC2A", role: "spi_mosi", voltage: "logic level" },
      { id: "PB4", label: "PB4/MISO", role: "spi_miso", voltage: "logic level" },
      { id: "PB5", label: "PB5/SCK", role: "spi_sck", voltage: "logic level" },
      { id: "PB6", label: "PB6/XTAL1", role: "other", notes: "Crystal input — or PB6 GPIO if internal RC clock used." },
      { id: "PB7", label: "PB7/XTAL2", role: "other", notes: "Crystal output." },
      { id: "PC0", label: "PC0/ADC0", role: "analog_in", voltage: "0-VCC" },
      { id: "PC1", label: "PC1/ADC1", role: "analog_in", voltage: "0-VCC" },
      { id: "PC2", label: "PC2/ADC2", role: "analog_in", voltage: "0-VCC" },
      { id: "PC3", label: "PC3/ADC3", role: "analog_in", voltage: "0-VCC" },
      { id: "PC4", label: "PC4/ADC4/SDA", role: "i2c_sda", voltage: "logic level" },
      { id: "PC5", label: "PC5/ADC5/SCL", role: "i2c_scl", voltage: "logic level" },
      { id: "PC6", label: "PC6/RESET", role: "reset", voltage: "logic level", notes: "Active-low reset." },
      { id: "VCC", label: "VCC", role: "power_in", voltage: "1.8-5.5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "AVCC", label: "AVCC", role: "power_in", voltage: "VCC", notes: "Analog supply — tie to VCC with bead/filter." },
      { id: "AREF", label: "AREF", role: "analog_in", voltage: "0-VCC", notes: "External ADC reference (optional)." },
    ],
    warnings: ["This is the bare IC — for hands-on use the Arduino Nano/Uno boards (already in the library) instead."],
  },
];
