from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Mapping


def attach_robotics_platform_geometry(payload: Mapping[str, Any] | Any, *, engineering: Dict[str, Any], out_dir: Path) -> Dict[str, Any]:
    """Generate small robotics platform geometry supplements and attach them to engineering evidence."""

    body = _to_dict(payload)
    project = _first_dict(body.get("robotics_project"), body.get("mechatronics_project"))
    platform = _first_dict(body.get("robotics_platform"), project.get("platform"))
    mobility = _first_dict(platform.get("mobility"), project.get("mobility"))
    robot_class = str(project.get("robot_class") or platform.get("type") or "").lower()
    mobility_type = str(mobility.get("type") or platform.get("type") or "").lower()
    if not any(token in " ".join([robot_class, mobility_type]) for token in ["wheeled", "rover", "differential_drive", "differential drive"]):
        return {"generated": False, "artifacts": {}, "outputs": []}

    mechanism = _dict(body.get("mechanism"))
    drive_base = _first_dict(mechanism.get("drive_base"), platform.get("drive_base"))
    dimensions = _drive_base_dimensions(drive_base, project, mobility)
    target_dir = out_dir / "robotics_platform"
    target_dir.mkdir(parents=True, exist_ok=True)
    scad_path = target_dir / "drive_base.scad"
    scad_path.write_text(_drive_base_scad(dimensions), encoding="utf-8")

    analysis = engineering.setdefault("analysis", {})
    if not isinstance(analysis, dict):
        engineering["analysis"] = analysis = {}
    mechanism_analysis = analysis.setdefault("mechanism", {})
    if not isinstance(mechanism_analysis, dict):
        analysis["mechanism"] = mechanism_analysis = {}

    output_name = "robotics_platform/drive_base.scad"
    mechanism_analysis["outputs"] = _dedupe_strings(_string_list(mechanism_analysis.get("outputs")) + [output_name])
    mechanism_analysis["parts"] = _list_dicts(mechanism_analysis.get("parts")) + [
        {
            "file": output_name,
            "module": "drive_base",
            "kind": "drive_base",
            "notes": "Differential-drive platform deck and motor mount reference geometry generated by Hardware-Splicer.",
        }
    ]
    mechanism_analysis["dfm"] = _list_dicts(mechanism_analysis.get("dfm")) + [
        {
            "severity": "info",
            "domain": "drive_base",
            "message": "Drive base reference geometry generated with printable deck, wheel clearance, and motor mount markers.",
        }
    ]
    mechanism_analysis["simulation"] = _list_dicts(mechanism_analysis.get("simulation")) + [
        {
            "severity": "info",
            "domain": "drive_base",
            "model": "geometry_budget",
            "message": "Differential drive base geometry has wheel clearance and actuator spacing evidence for first-motion bench validation.",
            "metrics": dimensions,
        }
    ]
    mechanism_analysis["safety"] = _list_dicts(mechanism_analysis.get("safety")) + [
        {
            "severity": "info",
            "domain": "drive_base",
            "message": "Keep rover on current-limited marked-boundary bench/floor tests until drivetrain guards and fasteners are physically reviewed.",
        }
    ]

    return {
        "generated": True,
        "artifacts": {"robotics_platform_drive_base": str(scad_path)},
        "outputs": [output_name],
        "dimensions": dimensions,
    }


def _drive_base_dimensions(drive_base: Dict[str, Any], project: Dict[str, Any], mobility: Dict[str, Any]) -> Dict[str, float]:
    constraints = _dict(project.get("constraints"))
    length = _float(drive_base.get("length_mm") or drive_base.get("deck_l_mm"), 180.0)
    width = _float(drive_base.get("width_mm") or drive_base.get("deck_w_mm"), 120.0)
    thickness = _float(drive_base.get("thickness_mm") or drive_base.get("deck_t_mm"), 3.0)
    wheel_d = _float(drive_base.get("wheel_d_mm") or mobility.get("wheel_d_mm"), 65.0)
    motor_spacing = _float(drive_base.get("motor_spacing_mm") or drive_base.get("track_width_mm"), max(width - 24.0, 60.0))
    payload = _float(drive_base.get("payload_kg") or constraints.get("payload_kg"), 0.2)
    speed = _float(drive_base.get("max_speed_mps") or constraints.get("max_speed_mps"), 0.6)
    return {
        "deck_l_mm": round(length, 3),
        "deck_w_mm": round(width, 3),
        "deck_t_mm": round(thickness, 3),
        "wheel_d_mm": round(wheel_d, 3),
        "motor_spacing_mm": round(motor_spacing, 3),
        "payload_kg": round(payload, 3),
        "max_speed_mps": round(speed, 3),
    }


def _drive_base_scad(dim: Dict[str, float]) -> str:
    l = dim["deck_l_mm"]
    w = dim["deck_w_mm"]
    t = dim["deck_t_mm"]
    wheel = dim["wheel_d_mm"]
    spacing = dim["motor_spacing_mm"]
    motor_block_l = 28.0
    motor_block_w = 18.0
    motor_block_h = 12.0
    return f"""// Hardware-Splicer robotics platform supplement
// primitive=drive_base
// type=differential_drive_reference

deck_l = {l:.3f};
deck_w = {w:.3f};
deck_t = {t:.3f};
wheel_d = {wheel:.3f};
motor_spacing = {spacing:.3f};

module motor_mount_marker(x, y) {{
  translate([x, y, deck_t])
    difference() {{
      cube([{motor_block_l:.3f}, {motor_block_w:.3f}, {motor_block_h:.3f}], center=true);
      rotate([90, 0, 0]) cylinder(h={motor_block_w + 2:.3f}, d=3.2, center=true, $fn=24);
    }}
}}

module wheel_clearance_marker(x, y) {{
  translate([x, y, wheel_d / 2])
    rotate([90, 0, 0])
      cylinder(h=8, d=wheel_d, center=true, $fn=48);
}}

module drive_base() {{
  difference() {{
    translate([0, 0, deck_t / 2]) cube([deck_l, deck_w, deck_t], center=true);
    for (x = [-deck_l / 2 + 18, deck_l / 2 - 18])
      for (y = [-deck_w / 2 + 18, deck_w / 2 - 18])
        translate([x, y, -1]) cylinder(h=deck_t + 2, d=3.2, $fn=24);
  }}
  motor_mount_marker(0, -motor_spacing / 2);
  motor_mount_marker(0, motor_spacing / 2);
  %wheel_clearance_marker(0, -deck_w / 2 - 4);
  %wheel_clearance_marker(0, deck_w / 2 + 4);
}}

drive_base();
"""


def _to_dict(value: Mapping[str, Any] | Any) -> Dict[str, Any]:
    return dict(value) if isinstance(value, Mapping) else {}


def _dict(value: Any) -> Dict[str, Any]:
    return dict(value) if isinstance(value, Mapping) else {}


def _first_dict(*values: Any) -> Dict[str, Any]:
    for value in values:
        if isinstance(value, Mapping) and value:
            return dict(value)
    return {}


def _list_dicts(value: Any) -> List[Dict[str, Any]]:
    if not isinstance(value, list):
        return []
    return [dict(item) for item in value if isinstance(item, Mapping)]


def _string_list(value: Any) -> List[str]:
    if not isinstance(value, list):
        return []
    return [str(item).strip() for item in value if str(item).strip()]


def _dedupe_strings(values: List[str]) -> List[str]:
    seen = set()
    out = []
    for value in values:
        if value and value not in seen:
            seen.add(value)
            out.append(value)
    return out


def _float(value: Any, default: float) -> float:
    try:
        return float(value)
    except Exception:
        return default
