// High-leverage modules curated to fill gaps found by a gap-audit against
// common hobby parts. Each entry cites a datasheet/product URL.
//
// Provenance: entries marked WEB-VERIFIED were fetched and confirmed via
// Adafruit/Pololu/SparkFun product pages during this curation pass.
// Entries marked SPEC-CURATED were hand-written from stable, well-known
// pinouts (TI/Microchip/Sensirion/Infineon parts whose pinouts have been
// stable for years) and carry a datasheetUrl for verification.

import type { ModuleSpec } from "./module-library";

export const CURATED_EXTENDED: ModuleSpec[] = [
  // ---- WEB-VERIFIED (Adafruit/Pololu/SparkFun product pages) ----
  {
    id: "ina219-current",
    label: "INA219 current sensor",
    category: "sensor",
    summary: "I2C bidirectional current/voltage sensor, ±3.2A, up to 26V bus.",
    logicVoltage: 3.3,
    inputVoltageRange: [2.7, 5.5],
    manufacturer: "Texas Instruments",
    partNumber: "INA219",
    datasheetUrl: "https://learn.adafruit.com/adafruit-ina219-current-sensor-breakout/pinouts",
    priceUsd: 5,
    source: "curated",
    pins: [
      { id: "VIN", label: "VIN", role: "power_in", voltage: "2.7-5.5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SCL", label: "SCL", role: "i2c_scl", voltage: "3.3V or 5V" },
      { id: "SDA", label: "SDA", role: "i2c_sda", voltage: "3.3V or 5V" },
      { id: "VIN+", label: "Vin+", role: "analog_in", voltage: "0-26V", notes: "High-side current sense input" },
      { id: "VIN-", label: "Vin-", role: "analog_in", voltage: "0-26V", notes: "Low-side current sense input" },
    ],
    warnings: ["Default I2C address 0x40; jumpers A0/A1 select 0x41/0x44/0x45."],
  },
  {
    id: "pca9685-pwm",
    label: "PCA9685 16-channel PWM/servo driver",
    category: "interface",
    summary: "I2C-controlled 16 PWM outputs @ up to 1.6kHz, 12-bit; common for servos.",
    logicVoltage: 5,
    inputVoltageRange: [3, 5.5],
    manufacturer: "NXP",
    partNumber: "PCA9685",
    datasheetUrl: "https://learn.adafruit.com/16-channel-pwm-servo-driver/pinouts",
    priceUsd: 14,
    source: "curated",
    pins: [
      { id: "GND", label: "GND", role: "gnd" },
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3-5V" },
      { id: "V+", label: "V+", role: "power_in", voltage: "5-6V", notes: "Servo rail; up to 12V absolute max" },
      { id: "SCL", label: "SCL", role: "i2c_scl", voltage: "3.3V or 5V" },
      { id: "SDA", label: "SDA", role: "i2c_sda", voltage: "3.3V or 5V" },
      { id: "OE", label: "OE", role: "digital_in", voltage: "logic level", notes: "Low: outputs active; high: outputs disabled" },
      { id: "PWM0", label: "PWM0", role: "pwm" },
      { id: "PWM1", label: "PWM1", role: "pwm" },
      { id: "PWM2", label: "PWM2", role: "pwm" },
      { id: "PWM3", label: "PWM3", role: "pwm" },
      { id: "PWM4", label: "PWM4", role: "pwm" },
      { id: "PWM5", label: "PWM5", role: "pwm" },
      { id: "PWM6", label: "PWM6", role: "pwm" },
      { id: "PWM7", label: "PWM7", role: "pwm" },
      { id: "PWM8", label: "PWM8", role: "pwm" },
      { id: "PWM9", label: "PWM9", role: "pwm" },
      { id: "PWM10", label: "PWM10", role: "pwm" },
      { id: "PWM11", label: "PWM11", role: "pwm" },
      { id: "PWM12", label: "PWM12", role: "pwm" },
      { id: "PWM13", label: "PWM13", role: "pwm" },
      { id: "PWM14", label: "PWM14", role: "pwm" },
      { id: "PWM15", label: "PWM15", role: "pwm" },
    ],
    warnings: ["Power servos from V+ on a separate supply, never the logic VCC."],
  },
  {
    id: "a4988-stepper",
    label: "A4988 stepper driver carrier",
    category: "actuator",
    summary: "Bipolar stepper driver, up to 2A/coil with adequate cooling; 8-35V motor.",
    inputVoltageRange: [3, 5.5],
    manufacturer: "Allegro Microsystems / Pololu carrier",
    partNumber: "A4988",
    datasheetUrl: "https://www.pololu.com/product/1182",
    priceUsd: 6,
    source: "curated",
    pins: [
      { id: "VDD", label: "VDD", role: "power_in", voltage: "3-5.5V", notes: "Logic supply" },
      { id: "VMOT", label: "VMOT", role: "power_in", voltage: "8-35V", notes: "Motor supply" },
      { id: "GND_LOGIC", label: "GND", role: "gnd" },
      { id: "GND_MOTOR", label: "GND (motor)", role: "gnd" },
      { id: "STEP", label: "STEP", role: "digital_in", voltage: "logic level" },
      { id: "DIR", label: "DIR", role: "digital_in", voltage: "logic level" },
      { id: "MS1", label: "MS1", role: "digital_in", voltage: "logic level" },
      { id: "MS2", label: "MS2", role: "digital_in", voltage: "logic level" },
      { id: "MS3", label: "MS3", role: "digital_in", voltage: "logic level" },
      { id: "RST", label: "RST", role: "reset", voltage: "logic level" },
      { id: "SLP", label: "SLP", role: "digital_in", voltage: "logic level" },
      { id: "EN", label: "EN", role: "digital_in", voltage: "logic level", notes: "Active-low enable" },
      { id: "1A", label: "1A", role: "power_out", notes: "Coil 1" },
      { id: "1B", label: "1B", role: "power_out", notes: "Coil 1" },
      { id: "2A", label: "2A", role: "power_out", notes: "Coil 2" },
      { id: "2B", label: "2B", role: "power_out", notes: "Coil 2" },
    ],
    warnings: [
      "Set the VREF current limit BEFORE connecting the motor.",
      "RST and SLP must be tied together if SLP isn't used (datasheet requirement).",
    ],
  },
  {
    id: "pcf8574-ioexp",
    label: "PCF8574 I2C GPIO expander",
    category: "interface",
    summary: "Adds 8 quasi-bidirectional GPIO pins over I2C; useful for buttons/LEDs.",
    logicVoltage: 3.3,
    inputVoltageRange: [3, 5],
    manufacturer: "NXP",
    partNumber: "PCF8574",
    datasheetUrl: "https://learn.adafruit.com/adafruit-pcf8574/pinouts",
    priceUsd: 4,
    source: "curated",
    pins: [
      { id: "VIN", label: "VIN", role: "power_in", voltage: "3-5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SCL", label: "SCL", role: "i2c_scl", voltage: "3.3V or 5V" },
      { id: "SDA", label: "SDA", role: "i2c_sda", voltage: "3.3V or 5V" },
      { id: "INT", label: "INT", role: "digital_out", voltage: "logic level", notes: "Open-drain interrupt on pin change" },
      { id: "P0", label: "P0", role: "digital_io" },
      { id: "P1", label: "P1", role: "digital_io" },
      { id: "P2", label: "P2", role: "digital_io" },
      { id: "P3", label: "P3", role: "digital_io" },
      { id: "P4", label: "P4", role: "digital_io" },
      { id: "P5", label: "P5", role: "digital_io" },
      { id: "P6", label: "P6", role: "digital_io" },
      { id: "P7", label: "P7", role: "digital_io" },
    ],
    warnings: ["Quasi-bidirectional outputs are weak high-side — use external pull-up for clean reads."],
  },
  {
    id: "max31855-thermocouple",
    label: "MAX31855 K-type thermocouple amplifier",
    category: "sensor",
    summary: "SPI cold-junction-compensated K-type thermocouple-to-digital converter.",
    logicVoltage: 3.3,
    inputVoltageRange: [3, 5.5],
    manufacturer: "Maxim Integrated",
    partNumber: "MAX31855",
    datasheetUrl: "https://www.adafruit.com/product/269",
    priceUsd: 15,
    source: "curated",
    pins: [
      { id: "VIN", label: "VIN", role: "power_in", voltage: "3-5V" },
      { id: "3V3", label: "3Vo", role: "power_out", voltage: "3.3V", currentMaxMa: 100 },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "DO", label: "DO", role: "spi_miso", voltage: "3.3V" },
      { id: "CS", label: "CS", role: "spi_cs", voltage: "3.3V" },
      { id: "CLK", label: "CLK", role: "spi_sck", voltage: "3.3V" },
      { id: "T+", label: "T+", role: "analog_in", notes: "Thermocouple positive (yellow)" },
      { id: "T-", label: "T-", role: "analog_in", notes: "Thermocouple negative (red)" },
    ],
    warnings: [
      "Read-only SPI device — DI line not used.",
      "Cold-junction compensation requires the IC sees ambient temperature; don't enclose it.",
    ],
  },
  {
    id: "hx711-loadcell",
    label: "HX711 24-bit ADC for load cells",
    category: "sensor",
    summary: "24-bit ΔΣ ADC with built-in PGA for strain-gauge load cells; up to 80SPS.",
    inputVoltageRange: [2.7, 5],
    manufacturer: "Avia Semiconductor",
    partNumber: "HX711",
    datasheetUrl: "https://www.sparkfun.com/products/13879",
    priceUsd: 3,
    source: "curated",
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "2.7-5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "DT", label: "DT", role: "digital_out", voltage: "logic level", notes: "Data out to MCU" },
      { id: "SCK", label: "SCK", role: "digital_in", voltage: "logic level", notes: "Clock from MCU" },
      { id: "E+", label: "E+", role: "power_out", voltage: "5V", notes: "Excitation+ for load cell (red wire)" },
      { id: "E-", label: "E-", role: "gnd", notes: "Excitation- (black wire)" },
      { id: "A+", label: "A+", role: "analog_in", notes: "Signal+ from load cell (white wire)" },
      { id: "A-", label: "A-", role: "analog_in", notes: "Signal- (green wire)" },
      { id: "B+", label: "B+", role: "analog_in", notes: "Optional channel B" },
      { id: "B-", label: "B-", role: "analog_in", notes: "Optional channel B" },
    ],
    warnings: ["Channel A gain is 128 or 64; channel B is fixed at 32."],
  },

  // ---- SPEC-CURATED (well-known stable pinouts; datasheet URLs verify) ----
  {
    id: "74hc595-shift-reg",
    label: "74HC595 8-bit shift register",
    category: "interface",
    summary: "Serial-in/parallel-out shift register, daisy-chainable via Q7'.",
    logicVoltage: 5,
    inputVoltageRange: [2, 6],
    manufacturer: "Texas Instruments",
    partNumber: "SN74HC595",
    datasheetUrl: "https://www.ti.com/lit/ds/symlink/sn74hc595.pdf",
    priceUsd: 1,
    source: "curated",
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "2-6V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SER", label: "SER", role: "digital_in", voltage: "logic level", notes: "Serial data in" },
      { id: "SRCLK", label: "SRCLK", role: "digital_in", voltage: "logic level", notes: "Shift-register clock" },
      { id: "RCLK", label: "RCLK", role: "digital_in", voltage: "logic level", notes: "Storage (latch) clock" },
      { id: "SRCLR", label: "SRCLR", role: "reset", voltage: "logic level", notes: "Active-low shift-register clear" },
      { id: "OE", label: "OE", role: "digital_in", voltage: "logic level", notes: "Active-low output enable" },
      { id: "QA", label: "QA", role: "digital_out", voltage: "logic level" },
      { id: "QB", label: "QB", role: "digital_out", voltage: "logic level" },
      { id: "QC", label: "QC", role: "digital_out", voltage: "logic level" },
      { id: "QD", label: "QD", role: "digital_out", voltage: "logic level" },
      { id: "QE", label: "QE", role: "digital_out", voltage: "logic level" },
      { id: "QF", label: "QF", role: "digital_out", voltage: "logic level" },
      { id: "QG", label: "QG", role: "digital_out", voltage: "logic level" },
      { id: "QH", label: "QH", role: "digital_out", voltage: "logic level" },
      { id: "QH'", label: "QH'", role: "digital_out", voltage: "logic level", notes: "Cascade out to next 595's SER" },
    ],
  },
  {
    id: "mcp4725-dac",
    label: "MCP4725 12-bit I2C DAC",
    category: "interface",
    summary: "12-bit DAC with internal EEPROM; ratiometric to VDD.",
    logicVoltage: 3.3,
    inputVoltageRange: [2.7, 5.5],
    manufacturer: "Microchip",
    partNumber: "MCP4725",
    datasheetUrl: "https://www.microchip.com/en-us/product/MCP4725",
    priceUsd: 5,
    source: "curated",
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "2.7-5.5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SCL", label: "SCL", role: "i2c_scl", voltage: "logic level" },
      { id: "SDA", label: "SDA", role: "i2c_sda", voltage: "logic level" },
      { id: "A0", label: "A0", role: "digital_in", voltage: "logic level", notes: "Sets I2C address LSB (0x60/0x61)" },
      { id: "VOUT", label: "VOUT", role: "analog_in", notes: "Analog output 0..VDD; treated as analog_in for safety-rules" },
    ],
  },
  {
    id: "drv8833-motor",
    label: "DRV8833 dual H-bridge motor driver",
    category: "actuator",
    summary: "Low-cost dual H-bridge, up to 1.5A/ch (2.5A peak); 2.7-10.8V motor.",
    inputVoltageRange: [2.7, 10.8],
    manufacturer: "Texas Instruments",
    partNumber: "DRV8833",
    datasheetUrl: "https://www.ti.com/product/DRV8833",
    priceUsd: 5,
    source: "curated",
    pins: [
      { id: "VM", label: "VM", role: "power_in", voltage: "2.7-10.8V", notes: "Motor power" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "AIN1", label: "AIN1", role: "digital_in", voltage: "logic level" },
      { id: "AIN2", label: "AIN2", role: "digital_in", voltage: "logic level" },
      { id: "BIN1", label: "BIN1", role: "digital_in", voltage: "logic level" },
      { id: "BIN2", label: "BIN2", role: "digital_in", voltage: "logic level" },
      { id: "AOUT1", label: "AOUT1", role: "power_out" },
      { id: "AOUT2", label: "AOUT2", role: "power_out" },
      { id: "BOUT1", label: "BOUT1", role: "power_out" },
      { id: "BOUT2", label: "BOUT2", role: "power_out" },
      { id: "SLEEP", label: "nSLEEP", role: "digital_in", voltage: "logic level", notes: "Pull high to enable" },
      { id: "FAULT", label: "nFAULT", role: "digital_out", voltage: "logic level", notes: "Open-drain fault flag" },
    ],
    warnings: ["Includes thermal protection; large heat-sink for >1A continuous."],
  },
  {
    id: "l9110-motor",
    label: "L9110S dual motor driver",
    category: "actuator",
    summary: "Cheap dual brushed-motor driver, 0.8A/ch continuous, 2.5-12V.",
    inputVoltageRange: [2.5, 12],
    manufacturer: "Various (clones of L9110S)",
    partNumber: "L9110S",
    datasheetUrl: "https://www.elecrow.com/download/datasheet-l9110.pdf",
    priceUsd: 2,
    source: "curated",
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "2.5-12V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "A-IA", label: "A-IA", role: "digital_in", voltage: "logic level" },
      { id: "A-IB", label: "A-IB", role: "digital_in", voltage: "logic level" },
      { id: "B-IA", label: "B-IA", role: "digital_in", voltage: "logic level" },
      { id: "B-IB", label: "B-IB", role: "digital_in", voltage: "logic level" },
      { id: "MOTOR-A1", label: "Motor A+", role: "power_out" },
      { id: "MOTOR-A2", label: "Motor A-", role: "power_out" },
      { id: "MOTOR-B1", label: "Motor B+", role: "power_out" },
      { id: "MOTOR-B2", label: "Motor B-", role: "power_out" },
    ],
    warnings: ["Cheaper but lossy (~1V drop). Prefer DRV8833 for >0.5A or efficiency-sensitive builds."],
  },
  {
    id: "scd30-co2",
    label: "SCD30 NDIR CO2 / temp / humidity sensor",
    category: "sensor",
    summary: "True NDIR CO2 (400-10000ppm) with temperature and humidity; I2C or UART.",
    logicVoltage: 3.3,
    inputVoltageRange: [3.3, 5.5],
    manufacturer: "Sensirion",
    partNumber: "SCD30",
    datasheetUrl: "https://sensirion.com/products/catalog/SCD30/",
    priceUsd: 50,
    source: "curated",
    pins: [
      { id: "VDD", label: "VDD", role: "power_in", voltage: "3.3-5.5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SCL", label: "SCL", role: "i2c_scl", voltage: "3.3V" },
      { id: "SDA", label: "SDA", role: "i2c_sda", voltage: "3.3V" },
      { id: "RDY", label: "RDY", role: "digital_out", voltage: "3.3V", notes: "Data-ready interrupt" },
      { id: "SEL", label: "SEL", role: "digital_in", voltage: "3.3V", notes: "Interface select: float=I2C, GND=UART" },
    ],
    warnings: ["Self-heats; place away from MCU and other heat sources for accurate readings."],
  },
  {
    id: "ens160-airquality",
    label: "ENS160 multi-gas air-quality sensor",
    category: "sensor",
    summary: "TVOC/eCO2/AQI (UBA, BME) over I2C; modern CCS811 replacement.",
    logicVoltage: 3.3,
    inputVoltageRange: [1.71, 3.6],
    manufacturer: "ScioSense",
    partNumber: "ENS160",
    datasheetUrl: "https://www.sciosense.com/products/environmental-sensors/ens160-digital-metal-oxide-multi-gas-sensor/",
    priceUsd: 18,
    source: "curated",
    pins: [
      { id: "VDD", label: "VDD", role: "power_in", voltage: "1.71-3.6V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "SCL", label: "SCL", role: "i2c_scl", voltage: "3.3V" },
      { id: "SDA", label: "SDA", role: "i2c_sda", voltage: "3.3V" },
      { id: "INT", label: "INT", role: "digital_out", voltage: "3.3V" },
      { id: "ADDR", label: "ADDR", role: "digital_in", voltage: "3.3V", notes: "Sets I2C address (0x52/0x53)" },
    ],
  },
  {
    id: "bts7960-motor",
    label: "BTS7960 high-current half-bridge driver",
    category: "actuator",
    summary: "43A peak half-bridge (common on robotics); built-in current sense.",
    inputVoltageRange: [5.5, 27],
    manufacturer: "Infineon",
    partNumber: "BTS7960",
    datasheetUrl: "https://www.infineon.com/dgdl/Infineon-BTS7960-DS-v01_00-EN.pdf",
    priceUsd: 8,
    source: "curated",
    pins: [
      { id: "VCC", label: "VCC (logic)", role: "power_in", voltage: "5V" },
      { id: "GND", label: "GND", role: "gnd" },
      { id: "B+", label: "B+", role: "power_in", voltage: "5.5-27V", notes: "Motor supply +" },
      { id: "B-", label: "B-", role: "gnd", notes: "Motor supply return" },
      { id: "RPWM", label: "RPWM", role: "pwm", voltage: "logic level" },
      { id: "LPWM", label: "LPWM", role: "pwm", voltage: "logic level" },
      { id: "R_EN", label: "R_EN", role: "digital_in", voltage: "logic level" },
      { id: "L_EN", label: "L_EN", role: "digital_in", voltage: "logic level" },
      { id: "R_IS", label: "R_IS", role: "analog_in", notes: "Right half-bridge current sense" },
      { id: "L_IS", label: "L_IS", role: "analog_in", notes: "Left half-bridge current sense" },
      { id: "M+", label: "M+", role: "power_out" },
      { id: "M-", label: "M-", role: "power_out" },
    ],
    warnings: [
      "Heatsink mandatory above ~10A continuous.",
      "Two BTS7960 paired form a full H-bridge for bidirectional drive.",
    ],
  },
];
