// AUTO-GENERATED from data/component_cache/component_database.json by
// .ingest_modules.py (kept out of the repo — re-run with that script
// to refresh). Each entry's source is recorded for traceability.
//
// Curated entries in module-library.ts take precedence by id; this file
// supplements with the broader encyclopedia drawn from the existing
// component database (100 entries across 10 categories).

import type { ModuleSpec } from "./module-library";

export const INGESTED_MODULES: ModuleSpec[] = [
  {
    id: "bmp180_pressure",
    label: "BMP180 Barometric Pressure Sensor",
    category: "sensor",
    summary: "Pressure (300-1100 hPa), Temperature",
    inputVoltageRange: [3.3, 5.0],
    manufacturer: "Bosch",
    partNumber: "BMP180",
    datasheetUrl: "https://www.adafruit.com/product/1603",
    priceUsd: 4.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3V or 5V", notes: "3.3-5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "SDA", label: "SDA", role: "i2c_sda", notes: "I2C Data" },
      { id: "SCL", label: "SCL", role: "i2c_scl", notes: "I2C Clock" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "rc522_rfid",
    label: "RC522 RFID Reader Module",
    category: "sensor",
    summary: "RC522 RFID Reader Module (SPI)",
    inputVoltageRange: [3.3, 3.3],
    manufacturer: "NXP",
    partNumber: "MFRC522",
    datasheetUrl: "https://www.nxp.com/docs/en/data-sheet/MFRC522.pdf",
    priceUsd: 3.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3V", notes: "3.3V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "RST", label: "RST", role: "reset", notes: "Reset" },
      { id: "MISO", label: "MISO", role: "spi_miso", notes: "SPI MISO" },
      { id: "MOSI", label: "MOSI", role: "spi_mosi", notes: "SPI MOSI" },
      { id: "SCK", label: "SCK", role: "spi_sck", notes: "SPI Clock" },
      { id: "SDA", label: "SDA", role: "spi_cs", notes: "SPI Chip Select" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "dc_motor_3v_6v",
    label: "Mini DC Motor 3-6V",
    category: "actuator",
    summary: "Mini DC Motor 3-6V",
    inputVoltageRange: [3.0, 6.0],
    manufacturer: "Generic",
    partNumber: "DC-MOTOR-3V",
    datasheetUrl: "https://components101.com/motors/bo-motor",
    priceUsd: 1.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3-6V DC", notes: "+" },
      { id: "GND", label: "GND", role: "gnd", notes: "-" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "dc_geared_motor_12v",
    label: "12V DC Geared Motor 1:48",
    category: "actuator",
    summary: "12V DC Geared Motor 1:48",
    inputVoltageRange: [12.0, 12.0],
    manufacturer: "Generic",
    partNumber: "GEARED-12V",
    datasheetUrl: "https://components101.com/motors/johnson-geared-dc-motor",
    priceUsd: 5.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "12V DC", notes: "+12V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "vibration_motor",
    label: "Vibration Motor 3V",
    category: "actuator",
    summary: "Vibration Motor 3V",
    inputVoltageRange: [2.0, 3.6],
    manufacturer: "Generic",
    partNumber: "VIB-MOTOR",
    datasheetUrl: "https://www.adafruit.com/product/1201",
    priceUsd: 2.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "2-3.6V", notes: "+" },
      { id: "GND", label: "GND", role: "gnd", notes: "-" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "tsl2561_light",
    label: "TSL2561 Digital Light Sensor",
    category: "sensor",
    summary: "TSL2561 Digital Light Sensor (I2C)",
    inputVoltageRange: [2.7, 3.6],
    manufacturer: "AMS",
    partNumber: "TSL2561",
    datasheetUrl: "https://www.adafruit.com/product/439",
    priceUsd: 6.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "2.7-3.6V", notes: "3.3V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "SDA", label: "SDA", role: "i2c_sda", notes: "I2C Data" },
      { id: "SCL", label: "SCL", role: "i2c_scl", notes: "I2C Clock" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "ldr_photoresistor",
    label: "LDR Photoresistor GL5528",
    category: "sensor",
    summary: "LDR Photoresistor GL5528",
    manufacturer: "Generic",
    partNumber: "GL5528",
    datasheetUrl: "https://components101.com/resistors/ldr-datasheet",
    priceUsd: 0.5,
    pins: [
      { id: "PIN1", label: "PIN1", role: "other", notes: "Connection 1" },
      { id: "PIN2", label: "PIN2", role: "other", notes: "Connection 2" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "uv_sensor_ml8511",
    label: "ML8511 UV Light Sensor",
    category: "sensor",
    summary: "ML8511 UV Light Sensor",
    inputVoltageRange: [3.3, 3.3],
    manufacturer: "LAPIS",
    partNumber: "ML8511",
    datasheetUrl: "https://www.sparkfun.com/products/12705",
    priceUsd: 8.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3V", notes: "3.3V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "OUT", label: "OUT", role: "analog_in", notes: "Analog output" },
      { id: "EN", label: "EN", role: "reset", notes: "Enable" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "tcs34725_color",
    label: "TCS34725 RGB Color Sensor",
    category: "sensor",
    summary: "TCS34725 RGB Color Sensor (I2C)",
    inputVoltageRange: [3.3, 5.0],
    manufacturer: "AMS",
    partNumber: "TCS34725",
    datasheetUrl: "https://www.adafruit.com/product/1334",
    priceUsd: 7.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3V/5V", notes: "3.3-5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "SDA", label: "SDA", role: "i2c_sda", notes: "I2C Data" },
      { id: "SCL", label: "SCL", role: "i2c_scl", notes: "I2C Clock" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "sw_420_vibration",
    label: "SW-420 Vibration Sensor",
    category: "sensor",
    summary: "SW-420 Vibration Sensor",
    inputVoltageRange: [3.3, 5.0],
    manufacturer: "Generic",
    partNumber: "SW-420",
    datasheetUrl: "https://components101.com/sensors/sw-420-vibration-sensor-module",
    priceUsd: 1.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3-5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "DO", label: "DO", role: "digital_out", notes: "Digital out" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "tilt_switch_sw_520d",
    label: "SW-520D Tilt Switch",
    category: "sensor",
    summary: "SW-520D Tilt Switch",
    inputVoltageRange: [3.3, 5.0],
    manufacturer: "Generic",
    partNumber: "SW-520D",
    datasheetUrl: "https://components101.com/switches/tilt-sensor",
    priceUsd: 1.0,
    pins: [
      { id: "PIN1", label: "PIN1", role: "other", notes: "Connection 1" },
      { id: "PIN2", label: "PIN2", role: "other", notes: "Connection 2" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "ir_obstacle_sensor",
    label: "IR Obstacle Avoidance Sensor",
    category: "sensor",
    summary: "IR Obstacle Avoidance Sensor",
    inputVoltageRange: [3.3, 5.0],
    manufacturer: "Generic",
    partNumber: "IR-OBSTACLE",
    datasheetUrl: "https://components101.com/sensors/ir-sensor-module",
    priceUsd: 1.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3-5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "OUT", label: "OUT", role: "digital_out", notes: "Digital output" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "tcrt5000_line_follower",
    label: "TCRT5000 IR Reflective Sensor",
    category: "sensor",
    summary: "TCRT5000 IR Reflective Sensor",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Vishay",
    partNumber: "TCRT5000",
    datasheetUrl: "https://components101.com/sensors/tcrt5000-ir-sensor",
    priceUsd: 1.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "AO", label: "AO", role: "analog_in", notes: "Analog out" },
      { id: "DO", label: "DO", role: "digital_out", notes: "Digital out" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "vs1838b_ir_receiver",
    label: "VS1838B IR Receiver",
    category: "sensor",
    summary: "VS1838B IR Receiver",
    inputVoltageRange: [2.7, 5.5],
    manufacturer: "Vishay",
    partNumber: "VS1838B",
    datasheetUrl: "https://components101.com/wireless/ir-receiver-tsop1738",
    priceUsd: 1.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "2.7-5.5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "OUT", label: "OUT", role: "digital_out", notes: "Signal output" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "hall_effect_a3144",
    label: "A3144 Hall Effect Sensor",
    category: "sensor",
    summary: "A3144 Hall Effect Sensor",
    inputVoltageRange: [4.5, 24.0],
    manufacturer: "Allegro",
    partNumber: "A3144",
    datasheetUrl: "https://components101.com/sensors/a3144-hall-effect-sensor",
    priceUsd: 1.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "4.5-24V", notes: "4.5-24V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "OUT", label: "OUT", role: "digital_out", notes: "Output" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "hmc5883l_magnetometer",
    label: "HMC5883L 3-Axis Magnetometer",
    category: "sensor",
    summary: "HMC5883L 3-Axis Magnetometer (I2C)",
    inputVoltageRange: [3.3, 5.0],
    manufacturer: "Honeywell",
    partNumber: "HMC5883L",
    datasheetUrl: "https://www.adafruit.com/product/1746",
    priceUsd: 5.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3V/5V", notes: "3.3-5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "SDA", label: "SDA", role: "i2c_sda", notes: "I2C Data" },
      { id: "SCL", label: "SCL", role: "i2c_scl", notes: "I2C Clock" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "sd_card_module",
    label: "Micro SD Card Module",
    category: "interface",
    summary: "Micro SD Card Module (SPI)",
    inputVoltageRange: [3.3, 5.0],
    manufacturer: "Generic",
    partNumber: "SD-MODULE",
    datasheetUrl: "https://randomnerdtutorials.com/arduino-micro-sd-card-module/",
    priceUsd: 2.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3-5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "MISO", label: "MISO", role: "spi_miso", notes: "SPI MISO" },
      { id: "MOSI", label: "MOSI", role: "spi_mosi", notes: "SPI MOSI" },
      { id: "SCK", label: "SCK", role: "spi_sck", notes: "SPI Clock" },
      { id: "CS", label: "CS", role: "spi_cs", notes: "Chip Select" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "at24c256_eeprom",
    label: "AT24C256 I2C EEPROM 256Kbit",
    category: "interface",
    summary: "AT24C256 I2C EEPROM 256Kbit (I2C)",
    inputVoltageRange: [2.5, 5.5],
    manufacturer: "Atmel",
    partNumber: "AT24C256",
    datasheetUrl: "https://www.adafruit.com/product/1895",
    priceUsd: 2.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "2.5-5.5V", notes: "2.5-5.5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "SDA", label: "SDA", role: "i2c_sda", notes: "I2C Data" },
      { id: "SCL", label: "SCL", role: "i2c_scl", notes: "I2C Clock" },
      { id: "WP", label: "WP", role: "other", notes: "Write Protect" },
      { id: "A0-A2", label: "A0-A2", role: "other", notes: "Address pins" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "w25q128_flash",
    label: "W25Q128 SPI Flash 128Mbit",
    category: "interface",
    summary: "W25Q128 SPI Flash 128Mbit (SPI)",
    inputVoltageRange: [2.7, 3.6],
    manufacturer: "Winbond",
    partNumber: "W25Q128",
    datasheetUrl: "https://www.winbond.com/hq/product/code-storage-flash-memory/",
    priceUsd: 3.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "2.7-3.6V", notes: "3.3V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "DI", label: "DI", role: "other", notes: "Data In" },
      { id: "DO", label: "DO", role: "digital_out", notes: "Data Out" },
      { id: "CLK", label: "CLK", role: "other", notes: "Clock" },
      { id: "CS", label: "CS", role: "spi_cs", notes: "Chip Select" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "passive_buzzer",
    label: "Passive Buzzer 5V",
    category: "actuator",
    summary: "Passive Buzzer 5V",
    inputVoltageRange: [3.5, 5.5],
    manufacturer: "Generic",
    partNumber: "PASSIVE-BUZZ",
    datasheetUrl: "https://components101.com/misc/buzzer-pinout-working-datasheet",
    priceUsd: 1.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.5-5.5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "active_buzzer",
    label: "Active Buzzer 5V",
    category: "actuator",
    summary: "Active Buzzer 5V",
    inputVoltageRange: [3.5, 5.5],
    manufacturer: "Generic",
    partNumber: "ACTIVE-BUZZ",
    datasheetUrl: "https://components101.com/misc/buzzer-pinout-working-datasheet",
    priceUsd: 1.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.5-5.5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "dfplayer_mini",
    label: "DFPlayer Mini MP3 Module",
    category: "actuator",
    summary: "DFPlayer Mini MP3 Module (UART/I/O)",
    inputVoltageRange: [3.2, 5.0],
    manufacturer: "DFRobot",
    partNumber: "DFR0299",
    datasheetUrl: "https://www.dfrobot.com/product-1121.html",
    priceUsd: 4.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.2-5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "TX", label: "TX", role: "uart_tx", notes: "Transmit" },
      { id: "RX", label: "RX", role: "uart_rx", notes: "Receive" },
      { id: "SPK1/SPK2", label: "SPK1/SPK2", role: "digital_out", notes: "Speaker outputs" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "pam8403_amplifier",
    label: "PAM8403 Audio Amplifier 3W",
    category: "actuator",
    summary: "PAM8403 Audio Amplifier 3W",
    inputVoltageRange: [2.5, 5.0],
    manufacturer: "Diodes Inc",
    partNumber: "PAM8403",
    datasheetUrl: "https://components101.com/ics/pam8403-audio-amplifier",
    priceUsd: 2.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "2.5-5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "LIN", label: "LIN", role: "digital_in", notes: "Left input" },
      { id: "RIN", label: "RIN", role: "digital_in", notes: "Right input" },
      { id: "LOUT+/-", label: "LOUT+/-", role: "digital_out", notes: "Left output" },
      { id: "ROUT+/-", label: "ROUT+/-", role: "digital_out", notes: "Right output" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "solenoid_valve_12v",
    label: "12V Solenoid Valve",
    category: "actuator",
    summary: "12V Solenoid Valve",
    inputVoltageRange: [12.0, 12.0],
    manufacturer: "Generic",
    partNumber: "SOLENOID-12V",
    datasheetUrl: "https://components101.com/switches/solenoid-valve",
    priceUsd: 8.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "12V DC", notes: "12V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "water_pump_5v",
    label: "5V Mini Water Pump",
    category: "actuator",
    summary: "5V Mini Water Pump",
    inputVoltageRange: [3.0, 6.0],
    manufacturer: "Generic",
    partNumber: "WATER-PUMP-5V",
    datasheetUrl: "https://components101.com/motors/mini-water-pump",
    priceUsd: 3.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3-6V DC", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "cooling_fan_5v",
    label: "5V DC Cooling Fan 40mm",
    category: "actuator",
    summary: "5V DC Cooling Fan 40mm",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Generic",
    partNumber: "FAN-40MM",
    datasheetUrl: "https://www.adafruit.com/product/3368",
    priceUsd: 2.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V DC", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "lm7805_regulator",
    label: "LM7805 5V Regulator",
    category: "power",
    summary: "LM7805 5V Regulator",
    manufacturer: "Texas Instruments",
    partNumber: "LM7805",
    datasheetUrl: "https://components101.com/ics/lm7805-voltage-regulator",
    priceUsd: 0.5,
    pins: [
      { id: "VIN", label: "VIN", role: "power_in", notes: "Input voltage" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "VOUT", label: "VOUT", role: "power_out", notes: "5V output" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "vl53l0x_tof",
    label: "VL53L0X Time-of-Flight Sensor",
    category: "sensor",
    summary: "VL53L0X Time-of-Flight Sensor (I2C)",
    inputVoltageRange: [3.3, 5.0],
    manufacturer: "ST",
    partNumber: "VL53L0X",
    datasheetUrl: "https://www.adafruit.com/product/3317",
    priceUsd: 14.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3V/5V", notes: "3.3-5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "SDA", label: "SDA", role: "i2c_sda", notes: "I2C Data" },
      { id: "SCL", label: "SCL", role: "i2c_scl", notes: "I2C Clock" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "max30102_heart_rate",
    label: "MAX30102 Heart Rate Sensor",
    category: "sensor",
    summary: "Heart rate, SpO2",
    inputVoltageRange: [1.8, 3.3],
    manufacturer: "Maxim",
    partNumber: "MAX30102",
    datasheetUrl: "https://www.sparkfun.com/products/15219",
    priceUsd: 6.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "1.8V/3.3V", notes: "3.3V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "SDA", label: "SDA", role: "i2c_sda", notes: "I2C Data" },
      { id: "SCL", label: "SCL", role: "i2c_scl", notes: "I2C Clock" },
      { id: "INT", label: "INT", role: "other", notes: "Interrupt" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "ccs811_air_quality",
    label: "CCS811 Air Quality Sensor",
    category: "sensor",
    summary: "eCO2 (400-8192 ppm), TVOC (0-1187 ppb)",
    inputVoltageRange: [3.3, 3.3],
    manufacturer: "AMS",
    partNumber: "CCS811",
    datasheetUrl: "https://www.adafruit.com/product/3566",
    priceUsd: 20.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3V", notes: "3.3V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "SDA", label: "SDA", role: "i2c_sda", notes: "I2C Data" },
      { id: "SCL", label: "SCL", role: "i2c_scl", notes: "I2C Clock" },
      { id: "WAK", label: "WAK", role: "other", notes: "Wake" },
      { id: "RST", label: "RST", role: "reset", notes: "Reset" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "as3935_lightning",
    label: "AS3935 Lightning Detector",
    category: "sensor",
    summary: "AS3935 Lightning Detector (I2C/SPI)",
    inputVoltageRange: [2.4, 3.6],
    manufacturer: "AMS",
    partNumber: "AS3935",
    datasheetUrl: "https://www.sparkfun.com/products/15441",
    priceUsd: 25.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "2.4-3.6V", notes: "3.3V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "SDA/MOSI", label: "SDA/MOSI", role: "other", notes: "Data" },
      { id: "SCL/SCK", label: "SCL/SCK", role: "other", notes: "Clock" },
      { id: "IRQ", label: "IRQ", role: "other", notes: "Interrupt" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "tm1638_led_key",
    label: "TM1638 LED & Key Module",
    category: "display",
    summary: "TM1638 LED & Key Module (3-wire serial)",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Titan Micro",
    partNumber: "TM1638",
    datasheetUrl: "https://www.instructables.com/TM1638-LED-Key-Module/",
    priceUsd: 4.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "STB", label: "STB", role: "other", notes: "Strobe" },
      { id: "CLK", label: "CLK", role: "other", notes: "Clock" },
      { id: "DIO", label: "DIO", role: "other", notes: "Data I/O" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "esp8266_nodemcu",
    label: "ESP8266 NodeMCU",
    category: "mcu",
    summary: "ESP8266 NodeMCU",
    manufacturer: "Espressif",
    partNumber: "ESP8266-12E",
    datasheetUrl: "https://www.espressif.com/sites/default/files/documentation/0a-esp8266ex_datasheet_en.pdf",
    priceUsd: 4.0,
    pins: [
      { id: "3V3", label: "3V3", role: "power_out", notes: "3.3V power output" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "D1", label: "D1", role: "digital_io", notes: "GPIO5" },
      { id: "D2", label: "D2", role: "digital_io", notes: "GPIO4" },
      { id: "D3", label: "D3", role: "digital_io", notes: "GPIO0" },
      { id: "D4", label: "D4", role: "digital_io", notes: "GPIO2" },
      { id: "D5", label: "D5", role: "digital_io", notes: "GPIO14" },
      { id: "D6", label: "D6", role: "digital_io", notes: "GPIO12" },
      { id: "D7", label: "D7", role: "digital_io", notes: "GPIO13" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "esp32_c6_devkit",
    label: "ESP32-C6 DevKit",
    category: "mcu",
    summary: "ESP32-C6 DevKit",
    manufacturer: "Espressif",
    partNumber: "ESP32-C6-DEVKIT-C1",
    datasheetUrl: "https://www.espressif.com/sites/default/files/documentation/esp32-c6_datasheet_en.pdf",
    priceUsd: 12.0,
    pins: [
      { id: "3V3", label: "3V3", role: "power_out", notes: "3.3V power output" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "GPIO0-GPIO21", label: "GPIO0-GPIO21", role: "other", notes: "General purpose I/O" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "dht11",
    label: "DHT11 Temperature and Humidity Sensor",
    category: "sensor",
    summary: "DHT11 Temperature and Humidity Sensor (Single-wire digital)",
    manufacturer: "Aosong",
    partNumber: "DHT11",
    datasheetUrl: "https://www.mouser.com/datasheet/2/758/DHT11-Technical-Data-Sheet-Translated-Version-1143054.pdf",
    priceUsd: 5.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", notes: "3-5V power" },
      { id: "DATA", label: "DATA", role: "digital_io", notes: "Digital data pin (needs 4.7k-10k pullup)" },
      { id: "NC", label: "NC", role: "other", notes: "Not connected" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "ds18b20",
    label: "DS18B20 Digital Temperature Sensor",
    category: "sensor",
    summary: "DS18B20 Digital Temperature Sensor (1-Wire (OneWire))",
    manufacturer: "Maxim Integrated",
    partNumber: "DS18B20",
    datasheetUrl: "https://datasheets.maximintegrated.com/en/ds/DS18B20.pdf",
    priceUsd: 3.95,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", notes: "3.0-5.5V power" },
      { id: "DATA", label: "DATA", role: "digital_io", notes: "1-Wire data (needs 4.7k pullup)" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "bme680",
    label: "BME680 Environmental Sensor",
    category: "sensor",
    summary: "BME680 Environmental Sensor (I2C or SPI)",
    manufacturer: "Bosch",
    partNumber: "BME680",
    datasheetUrl: "https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bme680-ds001.pdf",
    priceUsd: 18.95,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", notes: "3.3V power" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "SCL", label: "SCL", role: "i2c_scl", notes: "I2C clock" },
      { id: "SDA", label: "SDA", role: "i2c_sda", notes: "I2C data" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "bmp280",
    label: "BMP280 Barometric Pressure Sensor",
    category: "sensor",
    summary: "BMP280 Barometric Pressure Sensor (I2C or SPI)",
    manufacturer: "Bosch",
    partNumber: "BMP280",
    datasheetUrl: "https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bmp280-ds001.pdf",
    priceUsd: 9.95,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", notes: "3.3V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "SCL", label: "SCL", role: "i2c_scl", notes: "I2C clock" },
      { id: "SDA", label: "SDA", role: "i2c_sda", notes: "I2C data" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "pir_motion_sensor",
    label: "PIR Motion Sensor",
    category: "sensor",
    summary: "PIR Motion Sensor",
    manufacturer: "Generic",
    partNumber: "HC-SR501",
    datasheetUrl: "https://www.epitran.it/ebayDrive/datasheet/44.pdf",
    priceUsd: 9.95,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", notes: "5-12V power" },
      { id: "OUT", label: "OUT", role: "digital_out", notes: "Digital output" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "bh1750",
    label: "BH1750 Light Sensor",
    category: "sensor",
    summary: "BH1750 Light Sensor (I2C)",
    manufacturer: "ROHM",
    partNumber: "BH1750FVI",
    datasheetUrl: "https://www.mouser.com/datasheet/2/348/bh1750fvi-e-186247.pdf",
    priceUsd: 4.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", notes: "3.3-5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "SCL", label: "SCL", role: "i2c_scl", notes: "I2C clock" },
      { id: "SDA", label: "SDA", role: "i2c_sda", notes: "I2C data" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "arduino_uno_r3",
    label: "Arduino Uno R3",
    category: "mcu",
    summary: "Arduino Uno R3",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Arduino",
    partNumber: "A000066",
    datasheetUrl: "https://docs.arduino.cc/resources/datasheets/A000066-datasheet.pdf",
    priceUsd: 23.0,
    pins: [
      { id: "D0-D13", label: "D0-D13", role: "other", notes: "Digital I/O pins" },
      { id: "A0-A5", label: "A0-A5", role: "analog_in", notes: "Analog input pins" },
      { id: "3.3V", label: "3.3V", role: "power_out", voltage: "5V", notes: "3.3V output (50mA max)" },
      { id: "5V", label: "5V", role: "power_out", voltage: "5V", notes: "5V output" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "Vin", label: "Vin", role: "power_in", voltage: "5V", notes: "Input voltage" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "arduino_nano",
    label: "Arduino Nano",
    category: "mcu",
    summary: "Arduino Nano",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Arduino",
    partNumber: "A000005",
    datasheetUrl: "https://docs.arduino.cc/hardware/nano",
    priceUsd: 22.0,
    pins: [
      { id: "D2-D13", label: "D2-D13", role: "other", notes: "Digital pins" },
      { id: "A0-A7", label: "A0-A7", role: "analog_in", notes: "Analog pins (8 total)" },
      { id: "3.3V", label: "3.3V", role: "power_out", voltage: "5V", notes: "3.3V output" },
      { id: "5V", label: "5V", role: "power_out", voltage: "5V", notes: "5V output" },
      { id: "Vin", label: "Vin", role: "power_in", voltage: "5V", notes: "7-12V input" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "arduino_mega_2560",
    label: "Arduino Mega 2560",
    category: "mcu",
    summary: "Arduino Mega 2560",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Arduino",
    partNumber: "A000067",
    datasheetUrl: "https://docs.arduino.cc/resources/datasheets/A000067-datasheet.pdf",
    priceUsd: 38.5,
    pins: [
      { id: "D0-D53", label: "D0-D53", role: "other", notes: "54 digital pins" },
      { id: "A0-A15", label: "A0-A15", role: "analog_in", notes: "16 analog pins" },
      { id: "Serial0-Serial3", label: "Serial0-Serial3", role: "other", notes: "4 UART ports" },
      { id: "PWM", label: "PWM", role: "pwm", notes: "15 PWM-capable pins" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "28byj48_stepper",
    label: "28BYJ-48 5V Stepper Motor",
    category: "actuator",
    summary: "28BYJ-48 5V Stepper Motor",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Generic",
    partNumber: "28BYJ-48",
    datasheetUrl: "https://components101.com/motors/28byj-48-stepper-motor",
    priceUsd: 4.0,
    pins: [
      { id: "IN1-IN4", label: "IN1-IN4", role: "digital_in", notes: "Coil inputs (use with ULN2003 driver)" },
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V power" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "relay_module_1ch_5v",
    label: "5V Single Channel Relay Module",
    category: "actuator",
    summary: "5V Single Channel Relay Module",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Generic",
    partNumber: "SRD-05VDC-SL-C",
    datasheetUrl: "https://components101.com/switches/5v-single-channel-relay-module-pinout-features-applications-working-datasheet",
    priceUsd: 2.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V power" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "IN", label: "IN", role: "digital_in", notes: "Control signal (active LOW)" },
      { id: "COM", label: "COM", role: "other", notes: "Common terminal" },
      { id: "NO", label: "NO", role: "other", notes: "Normally Open (closed when active)" },
      { id: "NC", label: "NC", role: "other", notes: "Normally Closed (open when active)" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "relay_module_4ch_5v",
    label: "5V 4-Channel Relay Module",
    category: "actuator",
    summary: "5V 4-Channel Relay Module",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Generic",
    partNumber: "SRD-05VDC-SL-C-4CH",
    datasheetUrl: "https://components101.com/switches/5v-four-channel-relay-module-pinout-features-applications-working-datasheet",
    priceUsd: 6.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V power" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "IN1-IN4", label: "IN1-IN4", role: "other", notes: "Control signals for each relay" },
      { id: "COM1-COM4", label: "COM1-COM4", role: "other", notes: "Common terminals" },
      { id: "NO1-NO4", label: "NO1-NO4", role: "other", notes: "Normally Open contacts" },
      { id: "NC1-NC4", label: "NC1-NC4", role: "other", notes: "Normally Closed contacts" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "lcd_16x2_i2c",
    label: "LCD 16x2 with I2C Interface",
    category: "display",
    summary: "LCD 16x2 with I2C Interface (I2C)",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Generic",
    partNumber: "1602-I2C",
    datasheetUrl: "https://components101.com/displays/16x2-lcd-pinout-datasheet",
    priceUsd: 10.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V power" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "SDA", label: "SDA", role: "i2c_sda", notes: "I2C data (A4 on Uno)" },
      { id: "SCL", label: "SCL", role: "i2c_scl", notes: "I2C clock (A5 on Uno)" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "lcd_16x2_parallel",
    label: "LCD 16x2 Parallel Interface",
    category: "display",
    summary: "LCD 16x2 Parallel Interface (Parallel (4-bit or 8-bit mode))",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Generic",
    partNumber: "1602A",
    datasheetUrl: "https://circuitdigest.com/article/16x2-lcd-display-module-pinout-datasheet",
    priceUsd: 5.0,
    pins: [
      { id: "VSS", label: "VSS", role: "gnd", notes: "Ground" },
      { id: "VDD", label: "VDD", role: "power_in", voltage: "5V", notes: "5V power" },
      { id: "V0", label: "V0", role: "other", notes: "Contrast adjustment" },
      { id: "RS", label: "RS", role: "other", notes: "Register Select" },
      { id: "RW", label: "RW", role: "other", notes: "Read/Write" },
      { id: "E", label: "E", role: "other", notes: "Enable" },
      { id: "D0-D7", label: "D0-D7", role: "other", notes: "Data pins (D4-D7 for 4-bit mode)" },
      { id: "A", label: "A", role: "other", notes: "Backlight anode (+5V)" },
      { id: "K", label: "K", role: "other", notes: "Backlight cathode (GND)" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "lm35_temperature",
    label: "LM35 Precision Temperature Sensor",
    category: "sensor",
    summary: "LM35 Precision Temperature Sensor (Analog voltage output)",
    manufacturer: "Texas Instruments",
    partNumber: "LM35DZ",
    datasheetUrl: "https://www.ti.com/lit/ds/symlink/lm35.pdf",
    priceUsd: 2.0,
    pins: [
      { id: "1", label: "1", role: "other", notes: "VCC (4-30V)" },
      { id: "2", label: "2", role: "analog_in", notes: "Vout (analog)" },
      { id: "3", label: "3", role: "other", notes: "GND" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "mq-2_gas_sensor",
    label: "MQ-2 Gas Sensor",
    category: "sensor",
    summary: "MQ-2 Gas Sensor (Analog voltage output)",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Generic",
    partNumber: "MQ-2",
    datasheetUrl: "https://www.sparkfun.com/datasheets/Sensors/MQ-2.pdf",
    priceUsd: 3.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "A0", label: "A0", role: "analog_in", notes: "Analog output" },
      { id: "D0", label: "D0", role: "digital_out", notes: "Digital output (with comparator)" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "mq-3_gas_sensor",
    label: "MQ-3 Gas Sensor",
    category: "sensor",
    summary: "MQ-3 Gas Sensor (Analog voltage output)",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Generic",
    partNumber: "MQ-3",
    datasheetUrl: "https://www.sparkfun.com/datasheets/Sensors/MQ-3.pdf",
    priceUsd: 3.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "A0", label: "A0", role: "analog_in", notes: "Analog output" },
      { id: "D0", label: "D0", role: "digital_out", notes: "Digital output (with comparator)" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "mq-4_gas_sensor",
    label: "MQ-4 Gas Sensor",
    category: "sensor",
    summary: "MQ-4 Gas Sensor (Analog voltage output)",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Generic",
    partNumber: "MQ-4",
    datasheetUrl: "https://www.sparkfun.com/datasheets/Sensors/MQ-4.pdf",
    priceUsd: 3.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "A0", label: "A0", role: "analog_in", notes: "Analog output" },
      { id: "D0", label: "D0", role: "digital_out", notes: "Digital output (with comparator)" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "mq-5_gas_sensor",
    label: "MQ-5 Gas Sensor",
    category: "sensor",
    summary: "MQ-5 Gas Sensor (Analog voltage output)",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Generic",
    partNumber: "MQ-5",
    datasheetUrl: "https://www.sparkfun.com/datasheets/Sensors/MQ-5.pdf",
    priceUsd: 3.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "A0", label: "A0", role: "analog_in", notes: "Analog output" },
      { id: "D0", label: "D0", role: "digital_out", notes: "Digital output (with comparator)" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "mq-7_gas_sensor",
    label: "MQ-7 Gas Sensor",
    category: "sensor",
    summary: "MQ-7 Gas Sensor (Analog voltage output)",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Generic",
    partNumber: "MQ-7",
    datasheetUrl: "https://www.sparkfun.com/datasheets/Sensors/MQ-7.pdf",
    priceUsd: 3.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "A0", label: "A0", role: "analog_in", notes: "Analog output" },
      { id: "D0", label: "D0", role: "digital_out", notes: "Digital output (with comparator)" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "mq-8_gas_sensor",
    label: "MQ-8 Gas Sensor",
    category: "sensor",
    summary: "MQ-8 Gas Sensor (Analog voltage output)",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Generic",
    partNumber: "MQ-8",
    datasheetUrl: "https://www.sparkfun.com/datasheets/Sensors/MQ-8.pdf",
    priceUsd: 3.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "A0", label: "A0", role: "analog_in", notes: "Analog output" },
      { id: "D0", label: "D0", role: "digital_out", notes: "Digital output (with comparator)" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "mq-9_gas_sensor",
    label: "MQ-9 Gas Sensor",
    category: "sensor",
    summary: "MQ-9 Gas Sensor (Analog voltage output)",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Generic",
    partNumber: "MQ-9",
    datasheetUrl: "https://www.sparkfun.com/datasheets/Sensors/MQ-9.pdf",
    priceUsd: 3.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "A0", label: "A0", role: "analog_in", notes: "Analog output" },
      { id: "D0", label: "D0", role: "digital_out", notes: "Digital output (with comparator)" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "mq-135_gas_sensor",
    label: "MQ-135 Gas Sensor",
    category: "sensor",
    summary: "MQ-135 Gas Sensor (Analog voltage output)",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Generic",
    partNumber: "MQ-135",
    datasheetUrl: "https://www.sparkfun.com/datasheets/Sensors/MQ-135.pdf",
    priceUsd: 4.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "A0", label: "A0", role: "analog_in", notes: "Analog output" },
      { id: "D0", label: "D0", role: "digital_out", notes: "Digital output (with comparator)" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "acs712_5a",
    label: "ACS712 Current Sensor 5A",
    category: "sensor",
    summary: "ACS712 Current Sensor 5A",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Allegro",
    partNumber: "ACS712-05B",
    datasheetUrl: "https://www.allegromicro.com/en/products/sense/current-sensor-ics/zero-to-fifty-amp-integrated-conductor-sensor-ics/acs712",
    priceUsd: 2.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "OUT", label: "OUT", role: "analog_in", notes: "Analog output" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "acs712_20a",
    label: "ACS712 Current Sensor 20A",
    category: "sensor",
    summary: "ACS712 Current Sensor 20A",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Allegro",
    partNumber: "ACS712-20B",
    datasheetUrl: "https://www.allegromicro.com/en/products/sense/current-sensor-ics/zero-to-fifty-amp-integrated-conductor-sensor-ics/acs712",
    priceUsd: 3.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "OUT", label: "OUT", role: "analog_in", notes: "Analog output" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "acs712_30a",
    label: "ACS712 Current Sensor 30A",
    category: "sensor",
    summary: "ACS712 Current Sensor 30A",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Allegro",
    partNumber: "ACS712-30B",
    datasheetUrl: "https://www.allegromicro.com/en/products/sense/current-sensor-ics/zero-to-fifty-amp-integrated-conductor-sensor-ics/acs712",
    priceUsd: 3.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "OUT", label: "OUT", role: "analog_in", notes: "Analog output" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "voltage_sensor_25v",
    label: "Voltage Sensor Module 0-25V",
    category: "sensor",
    summary: "Voltage Sensor Module 0-25V",
    manufacturer: "Generic",
    partNumber: "VOLTAGE-SENSOR",
    priceUsd: 1.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "S", label: "S", role: "digital_out", notes: "Signal output" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "ky037_microphone",
    label: "KY-037 High Sensitivity Microphone",
    category: "sensor",
    summary: "KY-037 High Sensitivity Microphone",
    inputVoltageRange: [3.3, 5.0],
    manufacturer: "Generic",
    partNumber: "KY-037",
    datasheetUrl: "https://kunkune.co.uk/shop/arduino-sensors/ky-037-high-sensitive-sound-microphone-sensor/",
    priceUsd: 2.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3-5V", notes: "3.3-5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "A0", label: "A0", role: "analog_in", notes: "Analog output" },
      { id: "D0", label: "D0", role: "digital_out", notes: "Digital output" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "sound_sensor_module",
    label: "Sound Sensor Module",
    category: "sensor",
    summary: "Sound Sensor Module",
    inputVoltageRange: [3.3, 5.0],
    manufacturer: "Generic",
    partNumber: "SOUND-001",
    priceUsd: 1.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3-5V", notes: "3.3-5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "OUT", label: "OUT", role: "digital_out", notes: "Digital output" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "hc05_bluetooth",
    label: "HC-05 Bluetooth Module",
    category: "radio",
    summary: "HC-05 Bluetooth Module",
    inputVoltageRange: [3.3, 5.0],
    manufacturer: "Generic",
    partNumber: "HC-05",
    datasheetUrl: "https://components101.com/wireless/hc-05-bluetooth-module",
    priceUsd: 6.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3V (5V tolerant)", notes: "3.6-6V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "TXD", label: "TXD", role: "uart_tx", notes: "UART TX" },
      { id: "RXD", label: "RXD", role: "uart_rx", notes: "UART RX (3.3V!)" },
      { id: "STATE", label: "STATE", role: "other", notes: "Connection status" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "hc06_bluetooth",
    label: "HC-06 Bluetooth Module",
    category: "radio",
    summary: "HC-06 Bluetooth Module",
    inputVoltageRange: [3.3, 3.3],
    manufacturer: "Generic",
    partNumber: "HC-06",
    priceUsd: 5.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3V", notes: "3.6-6V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "TXD", label: "TXD", role: "uart_tx", notes: "UART TX" },
      { id: "RXD", label: "RXD", role: "uart_rx", notes: "UART RX (3.3V!)" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "lora_sx1278",
    label: "LoRa SX1278 433MHz Module",
    category: "radio",
    summary: "LoRa SX1278 433MHz Module (SPI)",
    inputVoltageRange: [1.8, 3.7],
    manufacturer: "Semtech",
    partNumber: "SX1278",
    datasheetUrl: "https://www.semtech.com/products/wireless-rf/lora-core/sx1278",
    priceUsd: 8.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "1.8-3.7V (3.3V typical)", notes: "3.3V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "MISO", label: "MISO", role: "spi_miso", notes: "SPI MISO" },
      { id: "MOSI", label: "MOSI", role: "spi_mosi", notes: "SPI MOSI" },
      { id: "SCK", label: "SCK", role: "spi_sck", notes: "SPI Clock" },
      { id: "NSS", label: "NSS", role: "spi_cs", notes: "SPI CS" },
      { id: "RST", label: "RST", role: "reset", notes: "Reset" },
      { id: "DIO0-DIO5", label: "DIO0-DIO5", role: "other", notes: "Digital I/O" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "neo6m_gps",
    label: "NEO-6M GPS Module",
    category: "radio",
    summary: "NEO-6M GPS Module (UART (9600 baud))",
    inputVoltageRange: [3.0, 5.0],
    manufacturer: "u-blox",
    partNumber: "NEO-6M",
    datasheetUrl: "https://www.u-blox.com/en/product/neo-6-series",
    priceUsd: 12.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3-5V", notes: "3-5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "TX", label: "TX", role: "uart_tx", notes: "UART TX" },
      { id: "RX", label: "RX", role: "uart_rx", notes: "UART RX" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "sim800l_gsm",
    label: "SIM800L GSM/GPRS Module",
    category: "radio",
    summary: "SIM800L GSM/GPRS Module (UART)",
    inputVoltageRange: [3.4, 4.4],
    manufacturer: "SIMCom",
    partNumber: "SIM800L",
    datasheetUrl: "https://www.simcom.com/product/SIM800L.html",
    priceUsd: 10.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.4-4.4V", notes: "3.7-4.2V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "TXD", label: "TXD", role: "uart_tx", notes: "UART TX" },
      { id: "RXD", label: "RXD", role: "uart_rx", notes: "UART RX" },
      { id: "RST", label: "RST", role: "reset", notes: "Reset" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "esp32_cam",
    label: "ESP32-CAM Camera Module",
    category: "radio",
    summary: "ESP32-CAM Camera Module",
    manufacturer: "Espressif",
    partNumber: "ESP32-CAM",
    datasheetUrl: "https://www.espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf",
    priceUsd: 10.0,
    pins: [
      { id: "5V", label: "5V", role: "power_out", notes: "5V input" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "U0R", label: "U0R", role: "uart_rx", notes: "UART RX (programming)" },
      { id: "U0T", label: "U0T", role: "uart_tx", notes: "UART TX" },
      { id: "GPIO0-GPIO16", label: "GPIO0-GPIO16", role: "other", notes: "GPIO pins" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "st7735_tft",
    label: "1.8\" TFT Display ST7735",
    category: "display",
    summary: "1.8\" TFT Display ST7735 (SPI)",
    inputVoltageRange: [3.3, 5.0],
    manufacturer: "Sitronix",
    partNumber: "ST7735",
    datasheetUrl: "https://www.displayfuture.com/Display/datasheet/controller/ST7735.pdf",
    priceUsd: 8.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3-5V", notes: "3.3-5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "SCL", label: "SCL", role: "spi_sck", notes: "SPI Clock" },
      { id: "SDA", label: "SDA", role: "spi_mosi", notes: "SPI MOSI" },
      { id: "RES", label: "RES", role: "other", notes: "Reset" },
      { id: "DC", label: "DC", role: "other", notes: "Data/Command" },
      { id: "CS", label: "CS", role: "spi_cs", notes: "Chip Select" },
      { id: "BL", label: "BL", role: "other", notes: "Backlight" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "ili9341_tft",
    label: "2.4\" TFT Display ILI9341",
    category: "display",
    summary: "2.4\" TFT Display ILI9341 (SPI)",
    manufacturer: "ILI Technology",
    partNumber: "ILI9341",
    datasheetUrl: "https://www.displayfuture.com/Display/datasheet/controller/ILI9341.pdf",
    priceUsd: 12.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "CS", label: "CS", role: "spi_cs", notes: "Chip Select" },
      { id: "RST", label: "RST", role: "reset", notes: "Reset" },
      { id: "DC", label: "DC", role: "other", notes: "Data/Command" },
      { id: "SDI", label: "SDI", role: "spi_mosi", notes: "SPI MOSI" },
      { id: "SCK", label: "SCK", role: "spi_sck", notes: "SPI Clock" },
      { id: "LED", label: "LED", role: "other", notes: "Backlight" },
      { id: "SDO", label: "SDO", role: "spi_miso", notes: "SPI MISO" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "max7219_7seg",
    label: "MAX7219 8-Digit 7-Segment Display",
    category: "display",
    summary: "MAX7219 8-Digit 7-Segment Display (SPI)",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Maxim",
    partNumber: "MAX7219",
    datasheetUrl: "https://datasheets.maximintegrated.com/en/ds/MAX7219-MAX7221.pdf",
    priceUsd: 5.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "DIN", label: "DIN", role: "spi_mosi", notes: "Data In (SPI MOSI)" },
      { id: "CS", label: "CS", role: "spi_cs", notes: "Chip Select" },
      { id: "CLK", label: "CLK", role: "spi_sck", notes: "Clock (SPI SCK)" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "ws2812b_strip",
    label: "WS2812B Addressable RGB LED Strip",
    category: "display",
    summary: "WS2812B Addressable RGB LED Strip",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "WorldSemi",
    partNumber: "WS2812B",
    datasheetUrl: "https://cdn-shop.adafruit.com/datasheets/WS2812B.pdf",
    priceUsd: 15.0,
    pins: [
      { id: "5V", label: "5V", role: "power_out", voltage: "5V", notes: "5V power" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "DIN", label: "DIN", role: "digital_in", notes: "Data input" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "neopixel_ring",
    label: "NeoPixel Ring 12 LED",
    category: "display",
    summary: "NeoPixel Ring 12 LED",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Adafruit",
    partNumber: "NeoPixel-Ring-12",
    priceUsd: 7.5,
    pins: [
      { id: "5V", label: "5V", role: "power_out", voltage: "5V", notes: "Power" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "IN", label: "IN", role: "digital_in", notes: "Data input" },
      { id: "OUT", label: "OUT", role: "digital_out", notes: "Data output (chainable)" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "tm1637_4digit",
    label: "TM1637 4-Digit 7-Segment Display",
    category: "display",
    summary: "TM1637 4-Digit 7-Segment Display (2-wire (CLK, DIO))",
    inputVoltageRange: [3.3, 5.0],
    manufacturer: "Titan Micro",
    partNumber: "TM1637",
    priceUsd: 2.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3-5V", notes: "3.3-5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "CLK", label: "CLK", role: "other", notes: "Clock" },
      { id: "DIO", label: "DIO", role: "other", notes: "Data I/O" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "ky040_encoder",
    label: "KY-040 Rotary Encoder",
    category: "interface",
    summary: "KY-040 Rotary Encoder",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Generic",
    partNumber: "KY-040",
    priceUsd: 2.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "CLK", label: "CLK", role: "digital_out", notes: "Clock output A" },
      { id: "DT", label: "DT", role: "digital_out", notes: "Data output B" },
      { id: "SW", label: "SW", role: "other", notes: "Switch (push button)" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "joystick_module",
    label: "Analog Joystick Module",
    category: "interface",
    summary: "Analog Joystick Module",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Generic",
    partNumber: "JOYSTICK-XY",
    priceUsd: 3.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "VRx", label: "VRx", role: "analog_in", notes: "X-axis analog" },
      { id: "VRy", label: "VRy", role: "analog_in", notes: "Y-axis analog" },
      { id: "SW", label: "SW", role: "other", notes: "Button" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "keypad_4x4",
    label: "4x4 Matrix Keypad",
    category: "interface",
    summary: "4x4 Matrix Keypad (8 digital pins (4 rows + 4 cols))",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Generic",
    partNumber: "KEYPAD-4X4",
    priceUsd: 3.5,
    pins: [
      { id: "ROW1-ROW4", label: "ROW1-ROW4", role: "other", notes: "Row pins" },
      { id: "COL1-COL4", label: "COL1-COL4", role: "other", notes: "Column pins" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "capacitive_touch",
    label: "TTP223 Capacitive Touch Sensor",
    category: "interface",
    summary: "TTP223 Capacitive Touch Sensor",
    inputVoltageRange: [2.0, 5.5],
    manufacturer: "Generic",
    partNumber: "TTP223",
    priceUsd: 1.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "2-5.5V", notes: "2-5.5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "SIG", label: "SIG", role: "digital_out", notes: "Signal output" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "soil_moisture",
    label: "Soil Moisture Sensor",
    category: "sensor",
    summary: "Soil Moisture Sensor",
    inputVoltageRange: [3.3, 5.0],
    manufacturer: "Generic",
    partNumber: "SOIL-001",
    priceUsd: 2.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3-5V", notes: "3.3-5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "A0", label: "A0", role: "analog_in", notes: "Analog output" },
      { id: "D0", label: "D0", role: "digital_out", notes: "Digital output (optional)" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "water_level",
    label: "Water Level Sensor",
    category: "sensor",
    summary: "Water Level Sensor",
    inputVoltageRange: [3.0, 5.0],
    manufacturer: "Generic",
    partNumber: "WATER-001",
    priceUsd: 1.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3-5V", notes: "3-5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "S", label: "S", role: "analog_in", notes: "Analog signal" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "flame_sensor",
    label: "Flame Sensor Module",
    category: "sensor",
    summary: "Flame Sensor Module",
    manufacturer: "Generic",
    partNumber: "FLAME-001",
    priceUsd: 2.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", notes: "3.3-5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "D0", label: "D0", role: "digital_out", notes: "Digital output" },
      { id: "A0", label: "A0", role: "analog_in", notes: "Analog output" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "rain_sensor",
    label: "Rain Drop Sensor",
    category: "sensor",
    summary: "Rain Drop Sensor",
    inputVoltageRange: [3.3, 5.0],
    manufacturer: "Generic",
    partNumber: "RAIN-001",
    priceUsd: 1.5,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "3.3-5V", notes: "3.3-5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "A0", label: "A0", role: "analog_in", notes: "Analog output" },
      { id: "D0", label: "D0", role: "digital_out", notes: "Digital output" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "tb6612_driver",
    label: "TB6612FNG Motor Driver",
    category: "actuator",
    summary: "TB6612FNG Motor Driver",
    manufacturer: "Toshiba",
    partNumber: "TB6612FNG",
    priceUsd: 5.0,
    pins: [
      { id: "PWMA,_PWMB", label: "PWMA, PWMB", role: "pwm", notes: "PWM speed control" },
      { id: "AIN1,_AIN2,_BIN1,_BIN2", label: "AIN1, AIN2, BIN1, BIN2", role: "other", notes: "Direction control" },
      { id: "A01,_A02,_B01,_B02", label: "A01, A02, B01, B02", role: "digital_out", notes: "Motor outputs" },
      { id: "VM", label: "VM", role: "other", notes: "Motor power (2.5-13.5V)" },
      { id: "VCC", label: "VCC", role: "power_in", notes: "Logic power (2.7-5.5V)" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "STBY", label: "STBY", role: "other", notes: "Standby" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "drv8825_stepper",
    label: "DRV8825 Stepper Driver",
    category: "actuator",
    summary: "DRV8825 Stepper Driver (STEP/DIR)",
    manufacturer: "Texas Instruments",
    partNumber: "DRV8825",
    datasheetUrl: "https://www.ti.com/lit/ds/symlink/drv8825.pdf",
    priceUsd: 6.0,
    pins: [
      { id: "VMOT", label: "VMOT", role: "other", notes: "Motor power (8.2-45V)" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "STEP", label: "STEP", role: "digital_in", notes: "Step input" },
      { id: "DIR", label: "DIR", role: "other", notes: "Direction" },
      { id: "EN", label: "EN", role: "reset", notes: "Enable" },
      { id: "MS1,_MS2,_MS3", label: "MS1, MS2, MS3", role: "other", notes: "Microstepping" },
      { id: "RST", label: "RST", role: "reset", notes: "Reset" },
      { id: "SLP", label: "SLP", role: "other", notes: "Sleep" },
      { id: "A1,_A2,_B1,_B2", label: "A1, A2, B1, B2", role: "other", notes: "Motor coils" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "ds1307_rtc",
    label: "DS1307 RTC Module",
    category: "interface",
    summary: "DS1307 RTC Module (I2C)",
    inputVoltageRange: [5.0, 5.0],
    manufacturer: "Maxim",
    partNumber: "DS1307",
    datasheetUrl: "https://datasheets.maximintegrated.com/en/ds/DS1307.pdf",
    priceUsd: 3.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "5V", notes: "5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "SDA", label: "SDA", role: "i2c_sda", notes: "I2C Data" },
      { id: "SCL", label: "SCL", role: "i2c_scl", notes: "I2C Clock" },
      { id: "SQW", label: "SQW", role: "digital_out", notes: "Square wave output" },
    ],
    source: "ingested-component-db",
  },
  {
    id: "ds3231_rtc",
    label: "DS3231 Precision RTC",
    category: "interface",
    summary: "DS3231 Precision RTC (I2C)",
    inputVoltageRange: [2.3, 5.5],
    manufacturer: "Maxim",
    partNumber: "DS3231",
    datasheetUrl: "https://datasheets.maximintegrated.com/en/ds/DS3231.pdf",
    priceUsd: 5.0,
    pins: [
      { id: "VCC", label: "VCC", role: "power_in", voltage: "2.3-5.5V", notes: "2.3-5.5V" },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "SDA", label: "SDA", role: "i2c_sda", notes: "I2C Data" },
      { id: "SCL", label: "SCL", role: "i2c_scl", notes: "I2C Clock" },
      { id: "SQW", label: "SQW", role: "other", notes: "Square wave/interrupt" },
      { id: "32K", label: "32K", role: "digital_out", notes: "32.768kHz output" },
    ],
    source: "ingested-component-db",
  },
];
