// AUTO-GENERATED from data/extracted_pinouts/*.json by scripts/
// ingest_pinout_extracts.py — bare-IC datasheet pinouts complementing
// the module-breakout entries in ingested.ts. Re-run the script to refresh.

import type { ModuleSpec } from "./module-library";

export const INGESTED_PINOUTS: ModuleSpec[] = [
  {
    id: "74hc04_chip",
    label: "74HC04",
    category: "interface",
    summary: "74HC04 datasheet pinout (extracted)",
    partNumber: "74HC04",
    pins: [
      { id: "PIN1", label: "PIN1", role: "other" },
      { id: "PIN2", label: "PIN2", role: "other" },
      { id: "PIN3", label: "PIN3", role: "other" },
      { id: "PIN4", label: "PIN4", role: "other" },
      { id: "PIN5", label: "PIN5", role: "other" },
      { id: "PIN6", label: "PIN6", role: "other" },
    ],
    source: "ingested-pinout-extract",
  },
  {
    id: "ads1115_chip",
    label: "ADS1115",
    category: "sensor",
    summary: "ADS1115 datasheet pinout (extracted)",
    partNumber: "ADS1115",
    pins: [
      { id: "PIN0", label: "PIN0", role: "other" },
      { id: "PIN1", label: "PIN1", role: "other" },
      { id: "PIN2", label: "PIN2", role: "other" },
      { id: "PIN3", label: "PIN3", role: "other" },
    ],
    source: "ingested-pinout-extract",
  },
  {
    id: "atmega2560_chip",
    label: "ATmega2560",
    category: "mcu",
    summary: "ATmega2560 datasheet pinout (extracted)",
    partNumber: "ATmega2560",
    pins: [
      { id: "PIN86", label: "PIN86", role: "other" },
      { id: "PIN54", label: "PIN54", role: "other" },
    ],
    source: "ingested-pinout-extract",
  },
  {
    id: "cp2102_chip",
    label: "CP2102",
    category: "interface",
    summary: "CP2102 datasheet pinout (extracted)",
    partNumber: "CP2102",
    pins: [
      { id: "V_DD", label: "V DD", role: "power_in", notes: "3.0–3.6V Power Supply Voltage Input. 3.3V Voltage Regulator Output. See \"10. Voltage Regulator\" on page 19." },
      { id: "GND", label: "GND", role: "gnd", notes: "Ground" },
      { id: "RST", label: "RST", role: "reset", notes: "Device Reset. Open-drain output of internal POR or V monitor. An DD external source can initiate a system reset by dr..." },
      { id: "REGIN", label: "REGIN", role: "other", notes: "5V Regulator Input. This pin is the input to the on-chip voltage regu- lator." },
      { id: "VBUS", label: "VBUS", role: "power_in", notes: "VBUS Sense Input. This pin should be connected to the VBUS signal of a USB network. A 5V signal on this pin indicates..." },
      { id: "NC1_/_V_2_PP", label: "NC1 / V 2 PP", role: "power_in", notes: "This pin should be left unconnected or tied to V . This pin is unused DD on the CP2102 and may be connected to the Vp..." },
      { id: "D+", label: "D+", role: "other", notes: "USB D+" },
      { id: "D–", label: "D–", role: "other", notes: "USB D–" },
      { id: "TXD", label: "TXD", role: "uart_tx", notes: "Asynchronous data output (UART Transmit)" },
      { id: "RXD", label: "RXD", role: "uart_rx", notes: "Asynchronous data input (UART Receive)" },
      { id: "CTS", label: "CTS", role: "other", notes: "Clear To Send control input (active low)" },
      { id: "RTS", label: "RTS", role: "other", notes: "Ready to Send control output (active low)" },
      { id: "DSR", label: "DSR", role: "other", notes: "Data Set Ready control input (active low)" },
      { id: "DTR", label: "DTR", role: "other", notes: "Data Terminal Ready control output (active low)" },
      { id: "DCD", label: "DCD", role: "other", notes: "Data Carrier Detect control input (active low)" },
      { id: "RI", label: "RI", role: "other", notes: "Ring Indicator control input (active low)" },
      { id: "SUSPEND", label: "SUSPEND", role: "other", notes: "This pin is driven high when the CP2102/9 enters the USB suspend state." },
      { id: "NC", label: "NC", role: "other", notes: "These pins should be left unconnected or tied to V . DD" },
    ],
    source: "ingested-pinout-extract",
  },
  {
    id: "esp32_chip",
    label: "ESP32",
    category: "mcu",
    summary: "ESP32 datasheet pinout (extracted)",
    partNumber: "ESP32",
    pins: [
      { id: "ADC1_CH4", label: "ADC1_CH4", role: "other" },
      { id: "ADC1_CH5", label: "ADC1_CH5", role: "other" },
      { id: "ADC1_CH6", label: "ADC1_CH6", role: "other" },
      { id: "ADC1_CH7", label: "ADC1_CH7", role: "other" },
      { id: "ADC2_CH0", label: "ADC2_CH0", role: "other" },
      { id: "ADC2_CH1", label: "ADC2_CH1", role: "other" },
      { id: "ADC2_CH2", label: "ADC2_CH2", role: "other" },
      { id: "ADC2_CH7", label: "ADC2_CH7", role: "other" },
      { id: "ADC2_CH8", label: "ADC2_CH8", role: "other" },
      { id: "ADC2_CH9", label: "ADC2_CH9", role: "other" },
      { id: "DAC_1", label: "DAC_1", role: "other", notes: "Two8-bitDACs" },
      { id: "DAC_2", label: "DAC_2", role: "other" },
      { id: "TOUCH0", label: "TOUCH0", role: "other", notes: "Capacitivetouchsensors" },
      { id: "TOUCH1", label: "TOUCH1", role: "other" },
      { id: "TOUCH2", label: "TOUCH2", role: "other" },
      { id: "TOUCH7", label: "TOUCH7", role: "other" },
      { id: "TOUCH8", label: "TOUCH8", role: "other" },
      { id: "TOUCH9", label: "TOUCH9", role: "other" },
    ],
    source: "ingested-pinout-extract",
  },
  {
    id: "ft232rl_chip",
    label: "FT232RL",
    category: "interface",
    summary: "FT232RL datasheet pinout (extracted)",
    partNumber: "FT232RL",
    pins: [
      { id: "TXDEN", label: "TXDEN", role: "uart_tx", notes: "Enable transmit data for RS485" },
      { id: "PWREN#", label: "PWREN#", role: "other", notes: "Output is low after the device has been configured by USB, then high during USB suspending mode. This output can be u..." },
      { id: "TXLED#", label: "TXLED#", role: "uart_tx", notes: "Transmit data LED drive: Data from USB Host to FT232R. Pulses low when transmitting data via USB. See Section 7.5 for..." },
      { id: "RXLED#", label: "RXLED#", role: "uart_rx", notes: "Receive data LED drive: Data from FT232R to USB Host. Pulses low when receiving data via USB. See Section 7.5 for mor..." },
      { id: "TX&RXLED#", label: "TX&RXLED#", role: "other", notes: "LED drive – pulses low when transmitting or receiving data via USB. See Section 7.5 for more details." },
      { id: "SLEEP#", label: "SLEEP#", role: "other", notes: "Goes low during USB suspend mode. Typically used to power down an external TTL to RS232 level converter IC in USB to ..." },
      { id: "CLK48", label: "CLK48", role: "other", notes: "48MHz ±0.7% Clock output. **" },
      { id: "CLK24", label: "CLK24", role: "other", notes: "24 MHz Clock output. **" },
      { id: "CLK12", label: "CLK12", role: "other", notes: "12 MHz Clock output. **" },
      { id: "CLK6", label: "CLK6", role: "other", notes: "6 MHz ±0.7% Clock output. **" },
      { id: "CBitBangI/O", label: "CBitBangI/O", role: "other", notes: "CBUS bit bang mode option. Allows up to 4 of the CBUS pins to be used as general purpose I/O. Configured individually..." },
      { id: "BitBangWRn", label: "BitBangWRn", role: "other", notes: "Synchronous and asynchronous bit bang mode WR# strobe output." },
      { id: "BitBangRDn", label: "BitBangRDn", role: "other", notes: "Synchronous and asynchronous bit bang mode RD# strobe output." },
    ],
    source: "ingested-pinout-extract",
  },
  {
    id: "lm2596_chip",
    label: "LM2596",
    category: "other",
    summary: "LM2596 datasheet pinout (extracted)",
    partNumber: "LM2596",
    pins: [
      { id: "PIN1", label: "PIN1", role: "power_in", notes: "This is the positive input supply for the IC switching regulator. A suitable input bypass capacitor must be present a..." },
      { id: "PIN2", label: "PIN2", role: "other", notes: "Internal switch. The voltage at this pin switches between approximately (+V − V ) and IN SAT approximately −0.5 V, wi..." },
      { id: "PIN3", label: "PIN3", role: "gnd", notes: "Circuit ground" },
      { id: "PIN4", label: "PIN4", role: "power_out", notes: "Senses the regulated output voltage to complete the feedback loop." },
      { id: "PIN5", label: "PIN5", role: "gnd", notes: "Allows the switching regulator circuit to be shut down using logic signals thus dropping the total input supply curre..." },
    ],
    source: "ingested-pinout-extract",
  },
  {
    id: "lm358_chip",
    label: "LM358",
    category: "other",
    summary: "LM358 datasheet pinout (extracted)",
    partNumber: "LM358",
    pins: [
      { id: "PIN1", label: "PIN1", role: "other" },
      { id: "PIN2", label: "PIN2", role: "other" },
    ],
    source: "ingested-pinout-extract",
  },
  {
    id: "lm393_chip",
    label: "LM393",
    category: "other",
    summary: "LM393 datasheet pinout (extracted)",
    partNumber: "LM393",
    pins: [
      { id: "PIN1", label: "PIN1", role: "other" },
      { id: "PIN2", label: "PIN2", role: "other" },
    ],
    source: "ingested-pinout-extract",
  },
  {
    id: "pic16f877a_chip",
    label: "PIC16F877A",
    category: "mcu",
    summary: "PIC16F877A datasheet pinout (extracted)",
    partNumber: "PIC16F877A",
    pins: [
      { id: "PIN38", label: "PIN38", role: "other", notes: "PORTD is a bidirectional I/O port or Parallel Slave Port when interfacing to a microprocessor bus. Digital I/O. Paral..." },
      { id: "PIN25", label: "PIN25", role: "spi_cs", notes: "PORTE is a bidirectional I/O port. Digital I/O. Read control for Parallel Slave Port. Analog input 5. Digital I/O. Wr..." },
      { id: "PIN6", label: "PIN6", role: "gnd", notes: "Ground reference for logic and I/O pins." },
      { id: "PIN7", label: "PIN7", role: "other", notes: "Positive supply for logic and I/O pins." },
      { id: "PIN13", label: "PIN13", role: "other", notes: "These pins are not internally connected. These pins should be left unconnected." },
    ],
    source: "ingested-pinout-extract",
  },
  {
    id: "tl072_chip",
    label: "TL072",
    category: "other",
    summary: "TL072 datasheet pinout (extracted)",
    partNumber: "TL072",
    pins: [
      { id: "PIN1", label: "PIN1", role: "other", notes: "Inverting input" },
      { id: "PIN2", label: "PIN2", role: "other", notes: "Inverting input" },
      { id: "PIN3", label: "PIN3", role: "other", notes: "Inverting input" },
      { id: "PIN4", label: "PIN4", role: "other", notes: "Inverting input" },
    ],
    source: "ingested-pinout-extract",
  },
  {
    id: "uln2003_chip",
    label: "ULN2003",
    category: "actuator",
    summary: "ULN2003 datasheet pinout (extracted)",
    partNumber: "ULN2003",
    pins: [
      { id: "PIN1", label: "PIN1", role: "other", notes: "Channel 1 through 7 Darlington base input" },
      { id: "PIN2", label: "PIN2", role: "other" },
      { id: "PIN3", label: "PIN3", role: "other" },
      { id: "PIN4", label: "PIN4", role: "other" },
      { id: "PIN5", label: "PIN5", role: "other" },
      { id: "PIN6", label: "PIN6", role: "other" },
      { id: "PIN7", label: "PIN7", role: "other" },
    ],
    source: "ingested-pinout-extract",
  },
];
