from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

from ..spec import (
    AssemblyInstanceSpec,
    AssemblySpec,
    BeltReductionSpec,
    GripperSpec,
    KeepoutSpec,
    LeadScrewAxisSpec,
    LinearAxisSpec,
    PanTiltSpec,
    ProjectSpec,
    RotaryJointSpec,
    ServoMountSpec,
    TransformSpec,
)
from .bearing_library import get_bearing_dims
from .hardware_patterns import NEMA17


def _scad_header(comment: str) -> str:
    return "\n".join(["// Auto-generated by Mecha-Splicer", f"// {comment}", "", "$fn = 64;", ""])


@dataclass(frozen=True)
class Mat4:
    m: Tuple[Tuple[float, float, float, float], Tuple[float, float, float, float], Tuple[float, float, float, float], Tuple[float, float, float, float]]

    @staticmethod
    def identity() -> "Mat4":
        return Mat4(((1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1)))


@dataclass(frozen=True)
class BBox:
    min_x: float
    min_y: float
    min_z: float
    max_x: float
    max_y: float
    max_z: float

    def corners(self) -> list[tuple[float, float, float]]:
        return [
            (self.min_x, self.min_y, self.min_z),
            (self.min_x, self.min_y, self.max_z),
            (self.min_x, self.max_y, self.min_z),
            (self.min_x, self.max_y, self.max_z),
            (self.max_x, self.min_y, self.min_z),
            (self.max_x, self.min_y, self.max_z),
            (self.max_x, self.max_y, self.min_z),
            (self.max_x, self.max_y, self.max_z),
        ]


def _mul(a: Mat4, b: Mat4) -> Mat4:
    out = [[0.0] * 4 for _ in range(4)]
    for i in range(4):
        for j in range(4):
            out[i][j] = sum(a.m[i][k] * b.m[k][j] for k in range(4))
    return Mat4(tuple(tuple(float(out[i][j]) for j in range(4)) for i in range(4)))  # type: ignore[arg-type]


def _tx(x: float, y: float, z: float) -> Mat4:
    return Mat4(((1, 0, 0, x), (0, 1, 0, y), (0, 0, 1, z), (0, 0, 0, 1)))


def _rx(deg: float) -> Mat4:
    r = math.radians(deg)
    c, s = math.cos(r), math.sin(r)
    return Mat4(((1, 0, 0, 0), (0, c, -s, 0), (0, s, c, 0), (0, 0, 0, 1)))


def _ry(deg: float) -> Mat4:
    r = math.radians(deg)
    c, s = math.cos(r), math.sin(r)
    return Mat4(((c, 0, s, 0), (0, 1, 0, 0), (-s, 0, c, 0), (0, 0, 0, 1)))


def _rz(deg: float) -> Mat4:
    r = math.radians(deg)
    c, s = math.cos(r), math.sin(r)
    return Mat4(((c, -s, 0, 0), (s, c, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1)))


def _from_transform(t: TransformSpec) -> Mat4:
    # Mirror OpenSCAD rotate([rx,ry,rz]) order (X then Y then Z) with pre-multiplication.
    return _mul(_mul(_mul(_tx(t.x_mm, t.y_mm, t.z_mm), _rx(t.rx_deg)), _ry(t.ry_deg)), _rz(t.rz_deg))


def _invert_rigid(a: Mat4) -> Mat4:
    # Rigid transform inverse: [R t; 0 1] -> [R^T -R^T t; 0 1]
    R = [[a.m[i][j] for j in range(3)] for i in range(3)]
    Rt = [[R[j][i] for j in range(3)] for i in range(3)]
    t = [a.m[i][3] for i in range(3)]
    nt = [-(Rt[i][0] * t[0] + Rt[i][1] * t[1] + Rt[i][2] * t[2]) for i in range(3)]
    return Mat4(
        (
            (Rt[0][0], Rt[0][1], Rt[0][2], nt[0]),
            (Rt[1][0], Rt[1][1], Rt[1][2], nt[1]),
            (Rt[2][0], Rt[2][1], Rt[2][2], nt[2]),
            (0, 0, 0, 1),
        )
    )


def _transform_point(T: Mat4, p: tuple[float, float, float]) -> tuple[float, float, float]:
    x, y, z = p
    nx = T.m[0][0] * x + T.m[0][1] * y + T.m[0][2] * z + T.m[0][3]
    ny = T.m[1][0] * x + T.m[1][1] * y + T.m[1][2] * z + T.m[1][3]
    nz = T.m[2][0] * x + T.m[2][1] * y + T.m[2][2] * z + T.m[2][3]
    return float(nx), float(ny), float(nz)


def _transform_bbox(T: Mat4, b: BBox) -> BBox:
    pts = [_transform_point(T, c) for c in b.corners()]
    xs = [p[0] for p in pts]
    ys = [p[1] for p in pts]
    zs = [p[2] for p in pts]
    return BBox(min(xs), min(ys), min(zs), max(xs), max(ys), max(zs))


def _bbox_intersection(a: BBox, b: BBox) -> Optional[tuple[float, float, float]]:
    dx = min(a.max_x, b.max_x) - max(a.min_x, b.min_x)
    dy = min(a.max_y, b.max_y) - max(a.min_y, b.min_y)
    dz = min(a.max_z, b.max_z) - max(a.min_z, b.min_z)
    if dx <= 0 or dy <= 0 or dz <= 0:
        return None
    return dx, dy, dz


def _to_scad_transform(a: Mat4) -> TransformSpec:
    # Extract translation and an approximate Euler (XYZ) from rotation matrix.
    x, y, z = a.m[0][3], a.m[1][3], a.m[2][3]
    r00, r01, r02 = a.m[0][0], a.m[0][1], a.m[0][2]
    r10, r11, r12 = a.m[1][0], a.m[1][1], a.m[1][2]
    r20, r21, r22 = a.m[2][0], a.m[2][1], a.m[2][2]

    # XYZ extraction (approx)
    if abs(r20) < 0.999999:
        ry = math.asin(-r20)
        rx = math.atan2(r21, r22)
        rz = math.atan2(r10, r00)
    else:
        # Gimbal lock
        ry = math.asin(-r20)
        rx = 0.0
        rz = math.atan2(-r01, r11)
    return TransformSpec(
        x_mm=float(x),
        y_mm=float(y),
        z_mm=float(z),
        rx_deg=float(math.degrees(rx)),
        ry_deg=float(math.degrees(ry)),
        rz_deg=float(math.degrees(rz)),
    )


def _instance_id(inst: AssemblyInstanceSpec, *, index: int) -> str:
    v = (inst.id or "").strip()
    if v:
        return v
    stem = (inst.output_file or "").replace(".scad", "").strip()
    return stem or f"inst_{index}"


def _anchors_from_instance(inst: AssemblyInstanceSpec) -> Dict[str, Mat4]:
    out: Dict[str, Mat4] = {}
    for a in inst.anchors or []:
        if not (a.name or "").strip():
            continue
        out[a.name.strip()] = _from_transform(a.transform)
    # Always provide an implicit origin anchor.
    out.setdefault("origin", Mat4.identity())
    return out


def _auto_anchors_for_rotary_joint_block(spec: RotaryJointSpec) -> Dict[str, Mat4]:
    b = get_bearing_dims(spec.bearing)
    pocket_d = b.od_mm + 2 * spec.clearance_mm
    pocket_h = b.width_mm + spec.clearance_mm
    w = max(spec.block_w_mm, pocket_d + 2 * spec.wall_mm)
    d = max(spec.block_d_mm, pocket_d + 2 * spec.wall_mm)
    h = max(spec.block_h_mm, pocket_h + 2.0)
    # Bearing axis center near top where pocket starts (approx), but for mating we mostly need XY.
    return {
        "center": _tx(w / 2.0, d / 2.0, 0.0),
        "bearing_center": _tx(w / 2.0, d / 2.0, h - (pocket_h / 2.0)),
        "axis": _tx(w / 2.0, d / 2.0, h - (pocket_h / 2.0)),
        "mount_plane": Mat4.identity(),
    }


def _auto_anchors_for_linear_axis_motor_mount(ax: LinearAxisSpec) -> Dict[str, Mat4]:
    plate_w = max(60.0, ax.rod_spacing_mm + 30.0)
    plate_h = 70.0
    y = 12.0
    anchors = {
        "center": _tx(plate_w / 2.0, plate_h / 2.0, 0.0),
        "motor_center": _tx(plate_w / 2.0, plate_h / 2.0, 0.0),
        "rod_left": _tx(plate_w / 2.0 - ax.rod_spacing_mm / 2.0, y, 0.0),
        "rod_right": _tx(plate_w / 2.0 + ax.rod_spacing_mm / 2.0, y, 0.0),
        "mount_plane": Mat4.identity(),
    }
    # NEMA17 bolt anchors relative to motor center
    for name, (bx, by) in NEMA17.bolt_xy().items():
        anchors[f"nema17_bolt_{name}"] = _tx(plate_w / 2.0 + bx, plate_h / 2.0 + by, 0.0)
    return anchors


def _auto_anchors_for_linear_axis_idler_mount(ax: LinearAxisSpec) -> Dict[str, Mat4]:
    plate_w = max(60.0, ax.rod_spacing_mm + 30.0)
    plate_h = 55.0
    y = 10.0
    return {
        "center": _tx(plate_w / 2.0, plate_h / 2.0, 0.0),
        "idler_center": _tx(plate_w / 2.0, plate_h / 2.0, 0.0),
        "rod_left": _tx(plate_w / 2.0 - ax.rod_spacing_mm / 2.0, y, 0.0),
        "rod_right": _tx(plate_w / 2.0 + ax.rod_spacing_mm / 2.0, y, 0.0),
        "mount_plane": Mat4.identity(),
    }


def _auto_anchors_for_linear_axis_carriage(ax: LinearAxisSpec) -> Dict[str, Mat4]:
    w = ax.rod_spacing_mm + ax.rod_d_mm + 20.0
    h = ax.rod_d_mm + 20.0
    return {
        "center": _tx(w / 2.0, h / 2.0, 0.0),
        "rod_left": _tx(w / 2.0 - ax.rod_spacing_mm / 2.0, h / 2.0, 0.0),
        "rod_right": _tx(w / 2.0 + ax.rod_spacing_mm / 2.0, h / 2.0, 0.0),
        "belt_center": _tx(w / 2.0, h / 2.0, 0.0),
    }


def _auto_anchors_for_belt_clamp(ax: LinearAxisSpec) -> Dict[str, Mat4]:
    w, h = 30.0, 16.0
    return {"center": _tx(w / 2.0, h / 2.0, 0.0)}


def _auto_anchors_for_rod_holder(ax: LinearAxisSpec) -> Dict[str, Mat4]:
    rod_d = ax.rod_d_mm
    od = rod_d + 10.0
    w = 24.0
    return {
        "center": _tx(w / 2.0, od / 2.0, 0.0),
        "rod_center": _tx(w / 2.0, od / 2.0, 0.0),
        "mount_plane": Mat4.identity(),
    }


def _auto_anchors_for_endstop_mount() -> Dict[str, Mat4]:
    w, h = 30.0, 20.0
    return {"center": _tx(w / 2.0, h / 2.0, 0.0), "mount_plane": Mat4.identity()}


def _auto_anchors_for_leadscrew_motor_mount(ax: LeadScrewAxisSpec) -> Dict[str, Mat4]:
    plate_w = max(70.0, ax.rod_spacing_mm + 35.0)
    plate_h = 80.0
    y = 12.0
    anchors = {
        "center": _tx(plate_w / 2.0, plate_h / 2.0, 0.0),
        "motor_center": _tx(plate_w / 2.0, plate_h * 0.6, 0.0),
        "coupler_center": _tx(plate_w / 2.0, plate_h * 0.3, 0.0),
        "screw_center": _tx(plate_w / 2.0, y, 0.0),
        "rod_left": _tx(plate_w / 2.0 - ax.rod_spacing_mm / 2.0, y, 0.0),
        "rod_right": _tx(plate_w / 2.0 + ax.rod_spacing_mm / 2.0, y, 0.0),
        "mount_plane": Mat4.identity(),
    }
    for name, (bx, by) in NEMA17.bolt_xy().items():
        anchors[f"nema17_bolt_{name}"] = _tx(plate_w / 2.0 + bx, plate_h * 0.6 + by, 0.0)
    return anchors


def _auto_anchors_for_leadscrew_end_support(ax: LeadScrewAxisSpec) -> Dict[str, Mat4]:
    w = max(70.0, ax.rod_spacing_mm + 35.0)
    h = 70.0
    y = h * 0.25
    return {
        "center": _tx(w / 2.0, h / 2.0, 0.0),
        "screw_center": _tx(w / 2.0, h * 0.6, 0.0),
        "rod_left": _tx(w / 2.0 - ax.rod_spacing_mm / 2.0, y, 0.0),
        "rod_right": _tx(w / 2.0 + ax.rod_spacing_mm / 2.0, y, 0.0),
        "mount_plane": Mat4.identity(),
    }


def _auto_anchors_for_leadscrew_carriage(ax: LeadScrewAxisSpec) -> Dict[str, Mat4]:
    w = ax.rod_spacing_mm + ax.rod_d_mm + 26.0
    h = ax.rod_d_mm + 26.0
    return {
        "center": _tx(w / 2.0, h / 2.0, 0.0),
        "screw_center": _tx(w / 2.0, h / 2.0, 0.0),
        "rod_left": _tx(w / 2.0 - ax.rod_spacing_mm / 2.0, h / 2.0, 0.0),
        "rod_right": _tx(w / 2.0 + ax.rod_spacing_mm / 2.0, h / 2.0, 0.0),
    }


def _auto_anchors_for_belt_reduction(br: BeltReductionSpec) -> Dict[str, Mat4]:
    mx = 28.0
    my = br.plate_h_mm / 2.0
    dx = mx + br.center_distance_mm
    dy = my
    ix = mx + br.center_distance_mm / 2.0
    iy = my + (br.idler_offset_mm if br.include_idler else 0.0)
    anchors = {"motor_center": _tx(mx, my, 0.0), "driven_center": _tx(dx, dy, 0.0), "center": _tx(br.plate_w_mm / 2.0, br.plate_h_mm / 2.0, 0.0)}
    for name, (bx, by) in NEMA17.bolt_xy().items():
        anchors[f"nema17_bolt_{name}"] = _tx(mx + bx, my + by, 0.0)
    if br.include_idler:
        anchors["idler_center"] = _tx(ix, iy, 0.0)
    anchors["mount_plane"] = Mat4.identity()
    return anchors


def _auto_anchors_for_servo_mount(sm: ServoMountSpec) -> Dict[str, Mat4]:
    return {"center": _tx(sm.plate_w_mm / 2.0, sm.plate_h_mm / 2.0, 0.0), "servo_center": _tx(sm.plate_w_mm / 2.0, sm.plate_h_mm / 2.0, 0.0)}


def _auto_anchors_for_gripper(g: GripperSpec) -> Dict[str, Mat4]:
    px = g.base_w_mm / 2.0
    py = g.base_h_mm * 0.25
    offset = 18.0
    return {
        "center": _tx(g.base_w_mm / 2.0, g.base_h_mm / 2.0, 0.0),
        "jaw_pivot_left": _tx(px - offset, py, 0.0),
        "jaw_pivot_right": _tx(px + offset, py, 0.0),
        "servo_center": _tx(g.base_w_mm / 2.0, g.base_h_mm / 2.0, 0.0),
        "mount_plane": Mat4.identity(),
    }


def _auto_anchors_for_pan_tilt(pt: PanTiltSpec) -> Dict[str, Dict[str, Mat4]]:
    # Base and bracket anchors are separate outputs.
    return {
        "pt_base.scad": {"center": _tx(pt.base_w_mm / 2.0, pt.base_h_mm / 2.0, 0.0), "servo_center": _tx(pt.base_w_mm / 2.0, pt.base_h_mm / 2.0, 0.0), "mount_plane": Mat4.identity()},
        "pt_bracket.scad": {"center": _tx(pt.bracket_w_mm / 2.0, pt.bracket_h_mm / 2.0, 0.0), "servo_center": _tx(pt.bracket_w_mm / 2.0, pt.bracket_h_mm / 2.0, 0.0), "mount_plane": Mat4.identity()},
        "pt_platform.scad": {"center": _tx(pt.platform_w_mm / 2.0, pt.platform_h_mm / 2.0, 0.0), "mount_plane": Mat4.identity()},
    }


def _build_auto_anchors(project: ProjectSpec) -> Dict[str, Dict[str, Mat4]]:
    anchors_by_output: Dict[str, Dict[str, Mat4]] = {}
    if project.rotary_joint is not None:
        anchors_by_output["rj_bearing_block.scad"] = _auto_anchors_for_rotary_joint_block(project.rotary_joint)
        anchors_by_output["rj_arm.scad"] = {"shaft": Mat4.identity(), "axis": Mat4.identity(), "origin": Mat4.identity(), "center": Mat4.identity()}
    if project.linear_axis is not None:
        ax = project.linear_axis
        anchors_by_output["motor_mount.scad"] = _auto_anchors_for_linear_axis_motor_mount(ax)
        anchors_by_output["idler_mount.scad"] = _auto_anchors_for_linear_axis_idler_mount(ax)
        anchors_by_output["carriage.scad"] = _auto_anchors_for_linear_axis_carriage(ax)
        anchors_by_output["belt_clamp.scad"] = _auto_anchors_for_belt_clamp(ax)
        if ax.include_rod_holders:
            anchors_by_output["rod_holder.scad"] = _auto_anchors_for_rod_holder(ax)
        if ax.include_endstops:
            anchors_by_output["endstop_mount.scad"] = _auto_anchors_for_endstop_mount()
    if project.leadscrew_axis is not None:
        ax = project.leadscrew_axis
        anchors_by_output["ls_motor_mount.scad"] = _auto_anchors_for_leadscrew_motor_mount(ax)
        anchors_by_output["ls_screw_end_support.scad"] = _auto_anchors_for_leadscrew_end_support(ax)
        anchors_by_output["ls_carriage_nut_mount.scad"] = _auto_anchors_for_leadscrew_carriage(ax)
        if ax.include_rod_holders:
            la = LinearAxisSpec.model_validate(
                {"rod_d_mm": ax.rod_d_mm, "rod_spacing_mm": ax.rod_spacing_mm, "rod_length_mm": ax.rod_length_mm, "clearance_mm": ax.clearance_mm, "wall_mm": ax.wall_mm}
            )
            anchors_by_output["rod_holder.scad"] = _auto_anchors_for_rod_holder(la)
        if ax.include_endstops:
            anchors_by_output["endstop_mount.scad"] = _auto_anchors_for_endstop_mount()
    if project.belt_reduction is not None:
        anchors_by_output["br_reduction_plate.scad"] = _auto_anchors_for_belt_reduction(project.belt_reduction)
    if project.servo_mount is not None:
        anchors_by_output["servo_mount.scad"] = _auto_anchors_for_servo_mount(project.servo_mount)
    if project.gripper is not None:
        anchors_by_output["gr_base.scad"] = _auto_anchors_for_gripper(project.gripper)
        anchors_by_output["gr_jaw_left.scad"] = {"pivot": Mat4.identity(), "origin": Mat4.identity()}
        anchors_by_output["gr_jaw_right.scad"] = {"pivot": Mat4.identity(), "origin": Mat4.identity()}
        anchors_by_output["gr_link.scad"] = {"center": Mat4.identity(), "origin": Mat4.identity()}
    if project.pan_tilt is not None:
        anchors_by_output.update(_auto_anchors_for_pan_tilt(project.pan_tilt))
    return anchors_by_output


def _build_auto_bboxes(project: ProjectSpec) -> Dict[str, BBox]:
    bboxes: Dict[str, BBox] = {}

    if project.enclosure is not None:
        enc = project.enclosure
        outer_w = enc.inner_w_mm + 2 * enc.wall_mm
        outer_d = enc.inner_d_mm + 2 * enc.wall_mm
        outer_h = enc.inner_h_mm + enc.floor_mm + (enc.lid_mm + 1.0 if enc.lid_style == "screw" else 0.0)
        bboxes["enclosure.scad"] = BBox(0, 0, 0, outer_w, outer_d, outer_h)

    if project.bracket is not None:
        br = project.bracket
        bboxes["bracket.scad"] = BBox(0, 0, 0, br.w_mm, br.d_mm, br.t_mm)

    if project.servo_mount is not None:
        sm = project.servo_mount
        bboxes["servo_mount.scad"] = BBox(0, 0, 0, sm.plate_w_mm, sm.plate_h_mm, sm.plate_t_mm)

    if project.linear_axis is not None:
        ax = project.linear_axis
        plate_w = max(60.0, ax.rod_spacing_mm + 30.0)
        bboxes["motor_mount.scad"] = BBox(0, 0, 0, plate_w, 70.0, ax.wall_mm * 2.0)
        bboxes["idler_mount.scad"] = BBox(0, 0, 0, plate_w, 55.0, ax.wall_mm * 2.0)
        w = ax.rod_spacing_mm + ax.rod_d_mm + 20.0
        h = ax.rod_d_mm + 20.0
        t = max(10.0, ax.wall_mm * 3.0)
        bboxes["carriage.scad"] = BBox(0, 0, 0, w, h, t)
        bboxes["belt_clamp.scad"] = BBox(0, 0, 0, 30.0, 16.0, max(4.0, ax.wall_mm * 2.0))
        rod_d = ax.rod_d_mm
        od = rod_d + 10.0
        bboxes["rod_holder.scad"] = BBox(0, 0, 0, 24.0, od, max(10.0, ax.wall_mm * 3.0))
        bboxes["endstop_mount.scad"] = BBox(0, 0, 0, 30.0, 20.0, max(4.0, ax.wall_mm * 2.0))

    if project.leadscrew_axis is not None:
        ax = project.leadscrew_axis
        plate_w = max(70.0, ax.rod_spacing_mm + 35.0)
        bboxes["ls_motor_mount.scad"] = BBox(0, 0, 0, plate_w, 80.0, ax.wall_mm * 2.0)
        w = max(70.0, ax.rod_spacing_mm + 35.0)
        bboxes["ls_screw_end_support.scad"] = BBox(0, 0, 0, w, 70.0, ax.wall_mm * 2.0)
        cw = ax.rod_spacing_mm + ax.rod_d_mm + 26.0
        ch = ax.rod_d_mm + 26.0
        ct = max(14.0, ax.wall_mm * 4.0)
        bboxes["ls_carriage_nut_mount.scad"] = BBox(0, 0, 0, cw, ch, ct)

    if project.rotary_joint is not None:
        rj = project.rotary_joint
        bd = get_bearing_dims(rj.bearing)
        pocket_d = bd.od_mm + 2 * rj.clearance_mm
        pocket_h = bd.width_mm + rj.clearance_mm
        w = max(rj.block_w_mm, pocket_d + 2 * rj.wall_mm)
        d = max(rj.block_d_mm, pocket_d + 2 * rj.wall_mm)
        h = max(rj.block_h_mm, pocket_h + 2.0)
        bboxes["rj_bearing_block.scad"] = BBox(0, 0, 0, w, d, h)
        bboxes["rj_arm.scad"] = BBox(0, 0, 0, rj.arm_len_mm, rj.arm_w_mm, rj.arm_t_mm)

    if project.belt_reduction is not None:
        br = project.belt_reduction
        bboxes["br_reduction_plate.scad"] = BBox(0, 0, 0, br.plate_w_mm, br.plate_h_mm, br.plate_t_mm)

    if project.gripper is not None:
        g = project.gripper
        bboxes["gr_base.scad"] = BBox(0, 0, 0, g.base_w_mm, g.base_h_mm, g.base_t_mm)
        bboxes["gr_jaw_left.scad"] = BBox(0, 0, 0, g.jaw_len_mm, g.jaw_w_mm, g.jaw_t_mm)
        bboxes["gr_jaw_right.scad"] = BBox(0, 0, 0, g.jaw_len_mm, g.jaw_w_mm, g.jaw_t_mm)
        bboxes["gr_link.scad"] = BBox(0, 0, 0, 50.0, g.link_w_mm, g.link_t_mm)

    if project.pan_tilt is not None:
        pt = project.pan_tilt
        bboxes["pt_base.scad"] = BBox(0, 0, 0, pt.base_w_mm, pt.base_h_mm, pt.base_t_mm)
        bboxes["pt_bracket.scad"] = BBox(0, 0, 0, pt.bracket_w_mm, pt.bracket_h_mm, pt.bracket_t_mm)
        bboxes["pt_platform.scad"] = BBox(0, 0, 0, pt.platform_w_mm, pt.platform_h_mm, pt.platform_t_mm)

    return bboxes


def _build_keepouts(project: ProjectSpec, assembly: AssemblySpec, *, anchors_by_output: Dict[str, Dict[str, Mat4]]) -> Dict[str, List[Tuple[str, BBox]]]:
    """
    Keepouts are AABB approximations used to warn about fastener access/cable space.

    Returns instance_id -> list of (name, local_bbox).
    """
    out: Dict[str, List[Tuple[str, BBox]]] = {}
    if not assembly.auto_keepouts:
        return out

    for i, inst in enumerate(assembly.instances):
        iid = _instance_id(inst, index=i)
        klist: List[Tuple[str, BBox]] = []

        # Manual keepouts
        for ko in inst.keepouts or []:
            kbox = _keepout_to_bbox(ko)
            if kbox is not None:
                klist.append((ko.name or "keepout", _transform_bbox(_from_transform(ko.transform), kbox)))

        # Auto keepouts: NEMA17 bolt access cylinders on any part that has those anchors.
        anchors = anchors_by_output.get(inst.output_file, {})
        for hole in ("ne", "nw", "se", "sw"):
            name = f"nema17_bolt_{hole}"
            if name not in anchors:
                continue
            p = anchors[name]
            # Cylinder keepout approximated as a box around a bolt head/tool (12mm dia x 20mm tall)
            r = 6.0
            h = 20.0
            klist.append((f"keepout_{name}", BBox(p.m[0][3] - r, p.m[1][3] - r, 0.0, p.m[0][3] + r, p.m[1][3] + r, h)))

        if klist:
            out[iid] = klist
    return out


def _keepout_to_bbox(k: KeepoutSpec) -> Optional[BBox]:
    if k.shape == "box":
        if k.w_mm <= 0 or k.d_mm <= 0 or k.h_mm <= 0:
            return None
        return BBox(0.0, 0.0, 0.0, float(k.w_mm), float(k.d_mm), float(k.h_mm))
    if k.shape == "cylinder":
        if k.r_mm <= 0 or k.z_mm <= 0:
            return None
        r = float(k.r_mm)
        h = float(k.z_mm)
        return BBox(-r, -r, 0.0, r, r, h)
    return None


def _merge_anchors(manual: Dict[str, Mat4], auto: Dict[str, Mat4]) -> Dict[str, Mat4]:
    # Manual overrides auto.
    out = dict(auto)
    out.update(manual)
    return out


def _solve_mates(assembly: AssemblySpec, *, anchors: Dict[str, Dict[str, Mat4]]) -> Tuple[Dict[str, Mat4], List[str]]:
    warnings: List[str] = []
    inst_ids: List[str] = []
    id_to_inst: Dict[str, AssemblyInstanceSpec] = {}
    for i, inst in enumerate(assembly.instances):
        iid = _instance_id(inst, index=i)
        inst_ids.append(iid)
        id_to_inst[iid] = inst

    placed: Dict[str, Mat4] = {}
    placed_by: Dict[str, Tuple[int, str]] = {}
    fixed_ids = [iid for iid in inst_ids if id_to_inst[iid].fixed]
    if fixed_ids:
        for iid in fixed_ids:
            placed[iid] = _from_transform(id_to_inst[iid].transform)
            placed_by[iid] = (10_000, "fixed")
    elif inst_ids:
        # Default: first instance is fixed.
        iid = inst_ids[0]
        placed[iid] = _from_transform(id_to_inst[iid].transform)
        placed_by[iid] = (0, "default_fixed")

    # Iterate mates; place any instance that can be solved.
    mates_sorted = sorted(list(assembly.mates or []), key=lambda m: int(getattr(m, "priority", 0)), reverse=True)
    for _ in range(64):
        progress = False
        for m in mates_sorted:
            a_id = m.a_instance
            b_id = m.b_instance
            if a_id not in id_to_inst or b_id not in id_to_inst:
                warnings.append(f"Mate '{m.name}' references unknown instance id(s).")
                continue
            a_anchors = anchors.get(a_id, {})
            b_anchors = anchors.get(b_id, {})
            a_anchor_name, b_anchor_name = _resolve_mate_anchor_names(m.kind, m.a_anchor, m.b_anchor)
            if a_anchor_name not in a_anchors:
                warnings.append(f"Mate '{m.name}' missing anchor '{a_anchor_name}' on instance '{a_id}'.")
                continue
            if b_anchor_name not in b_anchors:
                warnings.append(f"Mate '{m.name}' missing anchor '{b_anchor_name}' on instance '{b_id}'.")
                continue

            Ta = placed.get(a_id)
            Tb = placed.get(b_id)
            Off = _from_transform(m.offset)

            if m.kind == "bolt_pattern":
                pat = str((m.params or {}).get("pattern") or "nema17").lower()
                align = str((m.params or {}).get("align") or "single").lower()
                hole = str((m.params or {}).get("hole") or "ne").lower()
                if pat != "nema17":
                    warnings.append(f"Mate '{m.name}': unsupported bolt pattern '{pat}'.")
                    continue
                if align == "best_fit":
                    holes = (m.params or {}).get("holes") or ["ne", "nw", "se", "sw"]
                    holes = [str(h).lower() for h in holes]
                    if Ta is not None and Tb is None:
                        a_pts: list[tuple[float, float, float]] = []
                        b_pts: list[tuple[float, float, float]] = []
                        for h in holes:
                            an = f"nema17_bolt_{h}"
                            bn = f"nema17_bolt_{h}"
                            if an not in a_anchors or bn not in b_anchors:
                                continue
                            a_pts.append(_transform_point(_mul(Ta, _mul(a_anchors[an], Off)), (0.0, 0.0, 0.0)))
                            b_pts.append(_transform_point(b_anchors[bn], (0.0, 0.0, 0.0)))
                        if len(a_pts) < 2 or len(b_pts) < 2:
                            warnings.append(f"Mate '{m.name}': not enough bolt points for best_fit.")
                            continue
                        TinstB = _solve_best_fit_rz_translation(world_targets=a_pts, local_points=b_pts)
                        _set_placed(placed, placed_by, b_id, TinstB, int(m.priority), m.name, warnings)
                        progress = True
                        continue
                    if Tb is not None and Ta is None:
                        # Solve A by best-fitting A from B targets (swap roles)
                        b_world: list[tuple[float, float, float]] = []
                        a_local: list[tuple[float, float, float]] = []
                        for h in holes:
                            an = f"nema17_bolt_{h}"
                            bn = f"nema17_bolt_{h}"
                            if an not in a_anchors or bn not in b_anchors:
                                continue
                            b_world.append(_transform_point(_mul(Tb, b_anchors[bn]), (0.0, 0.0, 0.0)))
                            a_local.append(_transform_point(_mul(a_anchors[an], Off), (0.0, 0.0, 0.0)))
                        if len(b_world) < 2 or len(a_local) < 2:
                            warnings.append(f"Mate '{m.name}': not enough bolt points to solve A.")
                            continue
                        TinstA = _solve_best_fit_rz_translation(world_targets=b_world, local_points=a_local)
                        _set_placed(placed, placed_by, a_id, TinstA, int(m.priority), m.name, warnings)
                        progress = True
                        continue
                if align == "full":
                    # Solve using two bolts for orientation, then sanity-check remaining bolts.
                    a1 = f"nema17_bolt_{str((m.params or {}).get('a1') or 'ne').lower()}"
                    a2 = f"nema17_bolt_{str((m.params or {}).get('a2') or 'nw').lower()}"
                    b1 = f"nema17_bolt_{str((m.params or {}).get('b1') or 'ne').lower()}"
                    b2 = f"nema17_bolt_{str((m.params or {}).get('b2') or 'nw').lower()}"
                    if any(k not in a_anchors for k in (a1, a2)) or any(k not in b_anchors for k in (b1, b2)):
                        warnings.append(f"Mate '{m.name}': missing bolt anchors for full alignment.")
                        continue
                    if Ta is not None and Tb is None:
                        TinstB = _solve_two_point_align(T_known=Ta, P1=a_anchors[a1], P2=a_anchors[a2], Q1=b_anchors[b1], Q2=b_anchors[b2], Off=Off)
                        _set_placed(placed, placed_by, b_id, TinstB, int(m.priority), m.name, warnings)
                        progress = True
                        # residual check
                        _bolt_pattern_residual(warnings, m.name, Ta, a_anchors, b_anchors, TinstB, Off)
                        continue
                    if Tb is not None and Ta is None:
                        inv_off = _invert_rigid(Off)
                        TinstA = _solve_two_point_align(T_known=Tb, P1=b_anchors[b1], P2=b_anchors[b2], Q1=a_anchors[a1], Q2=a_anchors[a2], Off=inv_off)
                        _set_placed(placed, placed_by, a_id, TinstA, int(m.priority), m.name, warnings)
                        progress = True
                        _bolt_pattern_residual(warnings, m.name, TinstA, a_anchors, b_anchors, Tb, Mat4.identity())
                        continue
                    # If both placed, fall through to mismatch check using single anchor.
                a_anchor_name = f"nema17_bolt_{hole}"
                b_anchor_name = f"nema17_bolt_{hole}"
                if a_anchor_name not in a_anchors or b_anchor_name not in b_anchors:
                    warnings.append(f"Mate '{m.name}': missing nema17 bolt anchor '{hole}' on one side.")
                    continue

            A = a_anchors[a_anchor_name]
            B = b_anchors[b_anchor_name]

            if m.kind == "axis_collinear":
                if Ta is not None and Tb is None:
                    TinstB = _solve_axis_collinear(Ta, A, B, Off)
                    _set_placed(placed, placed_by, b_id, TinstB, int(m.priority), m.name, warnings)
                    progress = True
                    continue
                if Tb is not None and Ta is None:
                    # Solve A by inverting roles (apply inverse off by convention)
                    inv_off = _invert_rigid(Off)
                    TinstA = _solve_axis_collinear(Tb, B, A, inv_off)
                    _set_placed(placed, placed_by, a_id, TinstA, int(m.priority), m.name, warnings)
                    progress = True
                    continue

            if Ta is not None and Tb is None:
                # Solve B
                TinstB = _mul(_mul(_mul(Ta, A), Off), _invert_rigid(B))
                _set_placed(placed, placed_by, b_id, TinstB, int(m.priority), m.name, warnings)
                progress = True
            elif Tb is not None and Ta is None:
                # Solve A (rearrange): Ta*A*Off == Tb*B => Ta = Tb*B*inv(Off)*inv(A)
                TinstA = _mul(_mul(_mul(Tb, B), _invert_rigid(Off)), _invert_rigid(A))
                _set_placed(placed, placed_by, a_id, TinstA, int(m.priority), m.name, warnings)
                progress = True
            elif Ta is not None and Tb is not None:
                # Both placed: optionally check mismatch (translation only)
                left = _mul(_mul(Ta, A), Off)
                right = _mul(Tb, B)
                dx = left.m[0][3] - right.m[0][3]
                dy = left.m[1][3] - right.m[1][3]
                dz = left.m[2][3] - right.m[2][3]
                err = math.sqrt(dx * dx + dy * dy + dz * dz)
                if err > 1.0:
                    # Conflict resolver: if this mate has higher priority, try moving the less-protected instance.
                    pa, _sa = placed_by.get(a_id, (0, ""))
                    pb, _sb = placed_by.get(b_id, (0, ""))
                    # Prefer moving B using A as reference (common "attach B to A" workflow).
                    if int(m.priority) > pb and pa >= pb:
                        TinstB = _mul(_mul(_mul(Ta, A), Off), _invert_rigid(B))
                        _set_placed(placed, placed_by, b_id, TinstB, int(m.priority), m.name, warnings)
                        progress = True
                    elif int(m.priority) > pa and pb > pa:
                        TinstA = _mul(_mul(_mul(Tb, B), _invert_rigid(Off)), _invert_rigid(A))
                        _set_placed(placed, placed_by, a_id, TinstA, int(m.priority), m.name, warnings)
                        progress = True
                    else:
                        warnings.append(f"Conflict: mate '{m.name}' mismatch ~{err:.1f}mm (kept existing placements; try raising priority).")
            else:
                # Neither placed
                continue

            if m.kind == "rod_pair_align":
                # Align two points simultaneously to reduce twist. Defaults to rod_left/rod_right.
                aL = a_anchors.get(str((m.params or {}).get("a_left") or "rod_left"))
                aR = a_anchors.get(str((m.params or {}).get("a_right") or "rod_right"))
                bL = b_anchors.get(str((m.params or {}).get("b_left") or "rod_left"))
                bR = b_anchors.get(str((m.params or {}).get("b_right") or "rod_right"))
                if not (aL and aR and bL and bR):
                    warnings.append(f"Mate '{m.name}': missing rod_pair anchors; need left/right on both instances.")
                    continue
                Ta2, Tb2 = _solve_rod_pair_align(Ta=placed.get(a_id), Tb=placed.get(b_id), A_left=aL, A_right=aR, B_left=bL, B_right=bR, Off=Off)
                if Tb2 is not None and b_id in placed:
                    _set_placed(placed, placed_by, b_id, Tb2, int(m.priority), m.name, warnings)
                    progress = True
                if Ta2 is not None and a_id in placed:
                    _set_placed(placed, placed_by, a_id, Ta2, int(m.priority), m.name, warnings)
                    progress = True
        if not progress:
            break

    for iid in inst_ids:
        if iid not in placed:
            warnings.append(f"Instance '{iid}' not placed by mates; using its explicit transform.")
            placed[iid] = _from_transform(id_to_inst[iid].transform)
    return placed, warnings


def _transform_diff_mm(a: Mat4, b: Mat4) -> float:
    dx = a.m[0][3] - b.m[0][3]
    dy = a.m[1][3] - b.m[1][3]
    dz = a.m[2][3] - b.m[2][3]
    return float(math.sqrt(dx * dx + dy * dy + dz * dz))


def _col(T: Mat4, idx: int) -> tuple[float, float, float]:
    return (float(T.m[0][idx]), float(T.m[1][idx]), float(T.m[2][idx]))


def _dot(a: tuple[float, float, float], b: tuple[float, float, float]) -> float:
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def _cross(a: tuple[float, float, float], b: tuple[float, float, float]) -> tuple[float, float, float]:
    return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])


def _norm(a: tuple[float, float, float]) -> float:
    return float(math.sqrt(_dot(a, a)))


def _normalize(a: tuple[float, float, float]) -> tuple[float, float, float]:
    n = _norm(a)
    if n < 1e-9:
        return (0.0, 0.0, 0.0)
    return (a[0] / n, a[1] / n, a[2] / n)


def _proj_perp(v: tuple[float, float, float], n: tuple[float, float, float]) -> tuple[float, float, float]:
    # project v onto plane perpendicular to n
    nn = _normalize(n)
    return (v[0] - _dot(v, nn) * nn[0], v[1] - _dot(v, nn) * nn[1], v[2] - _dot(v, nn) * nn[2])


def _mat3_mul(A: list[list[float]], B: list[list[float]]) -> list[list[float]]:
    return [[sum(A[i][k] * B[k][j] for k in range(3)) for j in range(3)] for i in range(3)]


def _mat3_T(A: list[list[float]]) -> list[list[float]]:
    return [[A[j][i] for j in range(3)] for i in range(3)]


def _basis_from(z: tuple[float, float, float], x_hint: tuple[float, float, float]) -> list[list[float]]:
    zN = _normalize(z)
    xP = _proj_perp(x_hint, zN)
    if _norm(xP) < 1e-6:
        # pick another hint
        xP = _proj_perp((0.0, 1.0, 0.0), zN)
    xN = _normalize(xP)
    yN = _normalize(_cross(zN, xN))
    # Columns are basis vectors
    return [[xN[0], yN[0], zN[0]], [xN[1], yN[1], zN[1]], [xN[2], yN[2], zN[2]]]


def _mat4_from_R_t(R: list[list[float]], t: tuple[float, float, float]) -> Mat4:
    return Mat4(((R[0][0], R[0][1], R[0][2], t[0]), (R[1][0], R[1][1], R[1][2], t[1]), (R[2][0], R[2][1], R[2][2], t[2]), (0, 0, 0, 1)))


def _solve_axis_collinear(T_known: Mat4, A: Mat4, B: Mat4, Off: Mat4) -> Mat4:
    """
    Solve placement for the unknown instance so that the B-anchor axis (local +Z) is collinear
    with the target axis (A-anchor local +Z), and aligns roll using A-anchor local +X as hint.
    """
    Tw = _mul(_mul(T_known, A), Off)
    zT = _col(Tw, 2)
    xT = _col(Tw, 0)
    zB = _col(B, 2)
    xB = _col(B, 0)
    BT = _basis_from(zB, xB)
    TT = _basis_from(zT, xT)
    R = _mat3_mul(TT, _mat3_T(BT))  # maps B basis -> target basis

    # origin_target - R * origin_B
    oT = (Tw.m[0][3], Tw.m[1][3], Tw.m[2][3])
    oB = (B.m[0][3], B.m[1][3], B.m[2][3])
    oBR = (R[0][0] * oB[0] + R[0][1] * oB[1] + R[0][2] * oB[2], R[1][0] * oB[0] + R[1][1] * oB[1] + R[1][2] * oB[2], R[2][0] * oB[0] + R[2][1] * oB[1] + R[2][2] * oB[2])
    t = (float(oT[0] - oBR[0]), float(oT[1] - oBR[1]), float(oT[2] - oBR[2]))
    return _mat4_from_R_t(R, t)


def _set_placed(
    placed: Dict[str, Mat4],
    placed_by: Dict[str, Tuple[int, str]],
    inst_id: str,
    T: Mat4,
    priority: int,
    source: str,
    warnings: List[str],
) -> None:
    prev = placed.get(inst_id)
    if prev is None:
        placed[inst_id] = T
        placed_by[inst_id] = (priority, source)
        return
    prev_p, prev_src = placed_by.get(inst_id, (0, "unknown"))
    err = _transform_diff_mm(prev, T)
    if err < 0.5:
        return
    if priority > prev_p:
        warnings.append(f"Override: instance '{inst_id}' moved by mate '{source}' (p={priority}) over '{prev_src}' (p={prev_p}), Δ≈{err:.1f}mm")
        placed[inst_id] = T
        placed_by[inst_id] = (priority, source)
    else:
        warnings.append(f"Conflict: mate '{source}' suggests moving instance '{inst_id}' by Δ≈{err:.1f}mm but kept '{prev_src}' (p={prev_p}>=p={priority})")


def _bolt_pattern_residual(
    warnings: List[str],
    mate_name: str,
    Ta: Mat4,
    a_anchors: Dict[str, Mat4],
    b_anchors: Dict[str, Mat4],
    Tb: Mat4,
    Off: Mat4,
) -> None:
    # Check other bolts (se, sw) against the aligned transform.
    for hole in ("se", "sw"):
        a = a_anchors.get(f"nema17_bolt_{hole}")
        b = b_anchors.get(f"nema17_bolt_{hole}")
        if not (a and b):
            continue
        left = _mul(_mul(Ta, a), Off)
        right = _mul(Tb, b)
        err = _transform_diff_mm(left, right)
        if err > 1.0:
            warnings.append(f"Mate '{mate_name}' residual bolt {hole} mismatch ~{err:.1f}mm (full pattern)")


def _resolve_mate_anchor_names(kind: str, a_anchor: str, b_anchor: str) -> Tuple[str, str]:
    """
    Provide ergonomic mate kinds that map to anchor names.
    If anchor names are explicitly provided, preserve them.
    """
    a_anchor = (a_anchor or "").strip()
    b_anchor = (b_anchor or "").strip()
    if kind == "anchor":
        return a_anchor or "origin", b_anchor or "origin"
    if kind == "center_to_center":
        return a_anchor or "center", b_anchor or "center"
    if kind == "mount_plane_flush":
        return a_anchor or "mount_plane", b_anchor or "mount_plane"
    if kind == "shaft_into_bearing":
        # Convention: A= bearing side, B= shaft side
        return a_anchor or "bearing_center", b_anchor or "shaft"
    if kind == "axis_collinear":
        return a_anchor or "axis", b_anchor or "axis"
    return a_anchor or "origin", b_anchor or "origin"


def _solve_rod_pair_align(
    *,
    Ta: Optional[Mat4],
    Tb: Optional[Mat4],
    A_left: Mat4,
    A_right: Mat4,
    B_left: Mat4,
    B_right: Mat4,
    Off: Mat4,
) -> Tuple[Optional[Mat4], Optional[Mat4]]:
    """
    Solve a 2D rigid placement (Rz + translation) so that two points align simultaneously.
    Returns (Ta_new, Tb_new) where one may be filled if solvable.
    """

    def _solve(T_known: Mat4, P1: Mat4, P2: Mat4, Q1: Mat4, Q2: Mat4) -> Mat4:
        # Targets in world
        p1 = _transform_point(_mul(T_known, _mul(P1, Off)), (0.0, 0.0, 0.0))
        p2 = _transform_point(_mul(T_known, _mul(P2, Off)), (0.0, 0.0, 0.0))
        # Points in unknown local
        q1 = _transform_point(Q1, (0.0, 0.0, 0.0))
        q2 = _transform_point(Q2, (0.0, 0.0, 0.0))
        v1 = (p2[0] - p1[0], p2[1] - p1[1])
        v2 = (q2[0] - q1[0], q2[1] - q1[1])
        ang1 = math.atan2(v1[1], v1[0])
        ang2 = math.atan2(v2[1], v2[0])
        theta = math.degrees(ang1 - ang2)
        R = _rz(theta)
        q1r = _transform_point(R, q1)
        t = (p1[0] - q1r[0], p1[1] - q1r[1], p1[2] - q1r[2])
        return _mul(_tx(t[0], t[1], t[2]), R)

    if Ta is not None and Tb is None:
        return None, _solve(Ta, A_left, A_right, B_left, B_right)
    if Tb is not None and Ta is None:
        # Solve A from B by swapping roles; note Off is applied on the A side in the equation, so invert it here.
        inv_off = _invert_rigid(Off)
        return _solve(Tb, B_left, B_right, A_left, A_right, inv_off), None
    return None, None


def _solve_two_point_align(
    *,
    T_known: Mat4,
    P1: Mat4,
    P2: Mat4,
    Q1: Mat4,
    Q2: Mat4,
    Off: Mat4,
) -> Mat4:
    """
    Solve a 2D rigid placement (Rz + translation) so that two points align simultaneously.
    """
    p1 = _transform_point(_mul(T_known, _mul(P1, Off)), (0.0, 0.0, 0.0))
    p2 = _transform_point(_mul(T_known, _mul(P2, Off)), (0.0, 0.0, 0.0))
    q1 = _transform_point(Q1, (0.0, 0.0, 0.0))
    q2 = _transform_point(Q2, (0.0, 0.0, 0.0))
    v1 = (p2[0] - p1[0], p2[1] - p1[1])
    v2 = (q2[0] - q1[0], q2[1] - q1[1])
    ang1 = math.atan2(v1[1], v1[0])
    ang2 = math.atan2(v2[1], v2[0])
    theta = math.degrees(ang1 - ang2)
    R = _rz(theta)
    q1r = _transform_point(R, q1)
    t = (p1[0] - q1r[0], p1[1] - q1r[1], p1[2] - q1r[2])
    return _mul(_tx(t[0], t[1], t[2]), R)


def _solve_best_fit_rz_translation(
    *,
    world_targets: list[tuple[float, float, float]],
    local_points: list[tuple[float, float, float]],
) -> Mat4:
    """
    Best-fit in XY: find Rz(theta) + translation that maps local_points -> world_targets
    minimizing squared error in XY. Z is translated by centroid difference (no tilt).
    """
    if len(world_targets) != len(local_points) or len(world_targets) < 2:
        return Mat4.identity()

    twx = sum(p[0] for p in world_targets) / len(world_targets)
    twy = sum(p[1] for p in world_targets) / len(world_targets)
    twz = sum(p[2] for p in world_targets) / len(world_targets)
    tlx = sum(p[0] for p in local_points) / len(local_points)
    tly = sum(p[1] for p in local_points) / len(local_points)
    tlz = sum(p[2] for p in local_points) / len(local_points)

    # Compute optimal theta in 2D using atan2 of cross/dot sums.
    num = 0.0
    den = 0.0
    for (wx, wy, _wz), (lx, ly, _lz) in zip(world_targets, local_points):
        ax = wx - twx
        ay = wy - twy
        bx = lx - tlx
        by = ly - tly
        num += ax * by - ay * bx
        den += ax * bx + ay * by
    theta = math.degrees(math.atan2(num, den))
    R = _rz(theta)

    # Rotate local centroid then translate.
    c_local_rot = _transform_point(R, (tlx, tly, tlz))
    tx = twx - c_local_rot[0]
    ty = twy - c_local_rot[1]
    tz = twz - c_local_rot[2]
    return _mul(_tx(tx, ty, tz), R)


def generate_assembly_scad(project: ProjectSpec) -> str:
    assembly = project.assembly
    if assembly is None:
        raise ValueError("Project has no assembly.")

    auto_by_output = _build_auto_anchors(project) if assembly.auto_anchors else {}

    # Build per-instance anchor dictionaries
    inst_anchor_mats: Dict[str, Dict[str, Mat4]] = {}
    for i, inst in enumerate(assembly.instances):
        iid = _instance_id(inst, index=i)
        manual = _anchors_from_instance(inst)
        auto = auto_by_output.get(inst.output_file, {})
        inst_anchor_mats[iid] = _merge_anchors(manual, auto)

    placed, warnings = _solve_mates(assembly, anchors=inst_anchor_mats)

    # Assembly-level clearance heuristic (AABB overlap using approximate bboxes)
    bboxes_local = _build_auto_bboxes(project)
    world_boxes: Dict[str, BBox] = {}
    for i, inst in enumerate(assembly.instances):
        iid = _instance_id(inst, index=i)
        b = bboxes_local.get(inst.output_file)
        if b is None:
            continue
        world_boxes[iid] = _transform_bbox(placed[iid], b)
    checked = 0
    ids = list(world_boxes.keys())
    for i in range(len(ids)):
        for j in range(i + 1, len(ids)):
            if checked > 40:
                break
            a_id, b_id = ids[i], ids[j]
            inter = _bbox_intersection(world_boxes[a_id], world_boxes[b_id])
            if inter is None:
                continue
            dx, dy, dz = inter
            if dx * dy * dz < 1.0:  # ignore tiny overlaps
                continue
            warnings.append(f"Overlap: {a_id} vs {b_id} intersection≈{dx:.1f}×{dy:.1f}×{dz:.1f}mm (AABB heuristic)")
            checked += 1

    # Fastener access / keepouts heuristic
    keepouts = _build_keepouts(project, assembly, anchors_by_output=auto_by_output)
    world_keepouts: list[tuple[str, str, BBox]] = []
    for iid, ks in keepouts.items():
        T = placed.get(iid, Mat4.identity())
        for name, kbox_local in ks:
            world_keepouts.append((iid, name, _transform_bbox(T, kbox_local)))
    for iid, name, kbox in world_keepouts[:80]:
        for other_id, obox in world_boxes.items():
            if other_id == iid:
                continue
            inter = _bbox_intersection(kbox, obox)
            if inter is None:
                continue
            dx, dy, dz = inter
            if dx * dy * dz < 1.0:
                continue
            warnings.append(f"Keepout hit: {iid}.{name} overlaps {other_id} (~{dx:.1f}×{dy:.1f}×{dz:.1f}mm)")

    lines: list[str] = []
    lines.append(_scad_header(f"assembly={assembly.name}"))
    for w in warnings[:50]:
        lines.append(f"// WARN: {w}")

    # use<> each referenced scad
    used_files: set[str] = set()
    for inst in assembly.instances:
        f = str(inst.output_file).strip()
        if f and f not in used_files:
            used_files.add(f)
            lines.append(f"use <{f}>;")
    lines.append("")

    # Place each instance by solved transform
    for i, inst in enumerate(assembly.instances):
        iid = _instance_id(inst, index=i)
        T = placed[iid]
        t = _to_scad_transform(T)
        mod = str(inst.module).strip()
        lines.append(
            "translate([{x:.3f}, {y:.3f}, {z:.3f}]) rotate([{rx:.3f}, {ry:.3f}, {rz:.3f}]) {mod}();".format(
                x=t.x_mm,
                y=t.y_mm,
                z=t.z_mm,
                rx=t.rx_deg,
                ry=t.ry_deg,
                rz=t.rz_deg,
                mod=mod,
            )
        )

    return "\n".join(lines).strip() + "\n"
