from __future__ import annotations

from ..spec import (
    BeltReductionSpec,
    BracketSpec,
    Cutout,
    EnclosureSpec,
    GripperSpec,
    LeadScrewAxisSpec,
    LinearAxisSpec,
    PanTiltSpec,
    RotaryJointSpec,
    ServoMountSpec,
)
from .bearing_library import get_bearing_dims
from .servo_library import get_servo_dims
from .hardware_patterns import NEMA17


def _header(comment: str) -> str:
    return "\n".join(["// Auto-generated by Mecha-Splicer", f"// {comment}", "", "$fn = 64;", ""])


def _wrap_module(module: str, body_lines: list[str], *, call: bool = True) -> str:
    lines: list[str] = []
    lines.append(f"module {module}() {{")
    for l in body_lines:
        lines.append(f"  {l}")
    lines.append("}")
    if call:
        lines.append(f"{module}();")
    return "\n".join(lines) + "\n"


def generate_enclosure_scad(enc: EnclosureSpec) -> str:
    outer_w = enc.inner_w_mm + 2 * enc.wall_mm
    outer_d = enc.inner_d_mm + 2 * enc.wall_mm
    outer_h = enc.inner_h_mm + enc.floor_mm

    lines: list[str] = []
    lines.append(_header(f"enclosure={enc.name}"))
    lines.append(f"inner_w = {enc.inner_w_mm};")
    lines.append(f"inner_d = {enc.inner_d_mm};")
    lines.append(f"inner_h = {enc.inner_h_mm};")
    lines.append(f"wall = {enc.wall_mm};")
    lines.append(f"floor = {enc.floor_mm};")
    lines.append(f"lid_t = {enc.lid_mm};")
    lines.append(f"standoff_h = {enc.standoff_h_mm};")
    lines.append(f"standoff_od = {enc.standoff_od_mm};")
    lines.append(f"standoff_hole_d = {enc.standoff_hole_d_mm};")
    lines.append("")

    lines.append("module base() {")
    lines.append("  union() {")
    lines.append("    difference() {")
    lines.append(f"      cube([{outer_w}, {outer_d}, {outer_h}], center=false);")
    lines.append(
        f"      translate([{enc.wall_mm}, {enc.wall_mm}, {enc.floor_mm}]) cube([{enc.inner_w_mm}, {enc.inner_d_mm}, {enc.inner_h_mm}], center=false);"
    )
    for c in enc.cutouts:
        lines.extend(_cutout_scad(c, enc))
    # Lid screw clearance holes through the lid seating plane (optional, simplified)
    if enc.include_lid_screw_holes and enc.mount_holes:
        for mh in enc.mount_holes:
            x = enc.wall_mm + mh.x_mm
            y = enc.wall_mm + mh.y_mm
            lines.append(f"      translate([{x}, {y}, -1]) cylinder(h={outer_h + 2}, d={enc.lid_screw_hole_d_mm}, center=false);")
    lines.append("    }")

    # Standoffs: cylinders with center hole
    if enc.include_standoffs and enc.mount_holes:
        lines.append("    // Standoffs")
        lines.append("    difference() {")
        lines.append("      union() {")
        for mh in enc.mount_holes:
            x = enc.wall_mm + mh.x_mm
            y = enc.wall_mm + mh.y_mm
            lines.append(f"        translate([{x}, {y}, {enc.floor_mm}]) cylinder(h=standoff_h, d=standoff_od, center=false);")
        lines.append("      }")
        for mh in enc.mount_holes:
            x = enc.wall_mm + mh.x_mm
            y = enc.wall_mm + mh.y_mm
            lines.append(f"      translate([{x}, {y}, {enc.floor_mm - 1}]) cylinder(h=standoff_h + 2, d=standoff_hole_d, center=false);")
        lines.append("    }")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    lines.append("module lid() {")
    lines.append("  difference() {")
    lines.append(f"    cube([{outer_w}, {outer_d}, {enc.lid_mm}], center=false);")
    if enc.include_lid_screw_holes and enc.mount_holes:
        for mh in enc.mount_holes:
            x = enc.wall_mm + mh.x_mm
            y = enc.wall_mm + mh.y_mm
            lines.append(f"    translate([{x}, {y}, -1]) cylinder(h={enc.lid_mm + 2}, d={enc.lid_screw_hole_d_mm}, center=false);")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    body: list[str] = []
    body.append("base();")
    if enc.lid_style == "screw":
        body.append(f"translate([0, 0, {outer_h + 1.0}]) lid();")

    lines.append(_wrap_module("enclosure", body))
    return "\n".join(lines) + "\n"


def _cutout_scad(c: Cutout, enc: EnclosureSpec) -> list[str]:
    lines: list[str] = []
    depth = enc.wall_mm + 1.0
    if c.kind == "rect" and c.rect:
        r = c.rect
        if c.face == "front":
            lines.append(f"    translate([{enc.wall_mm + r.x_mm}, 0, {enc.floor_mm + r.y_mm}]) cube([{r.w_mm}, {depth}, {r.h_mm}], center=false);")
        elif c.face == "back":
            outer_d = enc.inner_d_mm + 2 * enc.wall_mm
            lines.append(f"    translate([{enc.wall_mm + r.x_mm}, {outer_d - depth}, {enc.floor_mm + r.y_mm}]) cube([{r.w_mm}, {depth}, {r.h_mm}], center=false);")
        elif c.face == "left":
            lines.append(f"    translate([0, {enc.wall_mm + r.x_mm}, {enc.floor_mm + r.y_mm}]) cube([{depth}, {r.w_mm}, {r.h_mm}], center=false);")
        elif c.face == "right":
            outer_w = enc.inner_w_mm + 2 * enc.wall_mm
            lines.append(f"    translate([{outer_w - depth}, {enc.wall_mm + r.x_mm}, {enc.floor_mm + r.y_mm}]) cube([{depth}, {r.w_mm}, {r.h_mm}], center=false);")
        elif c.face == "top":
            outer_h = enc.inner_h_mm + enc.floor_mm
            lines.append(f"    translate([{enc.wall_mm + r.x_mm}, {enc.wall_mm + r.y_mm}, {outer_h - depth}]) cube([{r.w_mm}, {r.h_mm}, {depth}], center=false);")
    elif c.kind == "circle" and c.circle:
        cc = c.circle
        if c.face in ("front", "back"):
            y = 0 if c.face == "front" else enc.inner_d_mm + 2 * enc.wall_mm - depth
            lines.append(f"    translate([{enc.wall_mm + cc.x_mm}, {y}, {enc.floor_mm + cc.y_mm}]) rotate([90,0,0]) cylinder(h={depth}, d={cc.d_mm}, center=false);")
        elif c.face in ("left", "right"):
            x = 0 if c.face == "left" else enc.inner_w_mm + 2 * enc.wall_mm - depth
            lines.append(f"    translate([{x}, {enc.wall_mm + cc.x_mm}, {enc.floor_mm + cc.y_mm}]) rotate([0,90,0]) cylinder(h={depth}, d={cc.d_mm}, center=false);")
    return lines


def generate_bracket_scad(br: BracketSpec) -> str:
    lines: list[str] = []
    lines.append(_header(f"bracket={br.name}"))
    lines.append(f"w = {br.w_mm};")
    lines.append(f"d = {br.d_mm};")
    lines.append(f"t = {br.t_mm};")
    lines.append(f"hole_d = {br.hole_d_mm};")
    lines.append(f"hole_spacing = {br.hole_spacing_mm};")
    lines.append("")
    lines.append("difference() {")
    lines.append("  cube([w, d, t], center=false);")
    lines.append("  translate([(w-hole_spacing)/2, d/2, -1]) cylinder(h=t+2, d=hole_d, center=false);")
    lines.append("  translate([(w+hole_spacing)/2, d/2, -1]) cylinder(h=t+2, d=hole_d, center=false);")
    lines.append("}")
    header = _header(f"bracket={br.name}")
    body = []
    body.append(f"w = {br.w_mm}; d = {br.d_mm}; t = {br.t_mm};")
    body.append(f"hole_d = {br.hole_d_mm}; hole_spacing = {br.hole_spacing_mm};")
    body.append("difference() {")
    body.append("  cube([w, d, t], center=false);")
    body.append("  translate([(w-hole_spacing)/2, d/2, -1]) cylinder(h=t+2, d=hole_d, center=false);")
    body.append("  translate([(w+hole_spacing)/2, d/2, -1]) cylinder(h=t+2, d=hole_d, center=false);")
    body.append("}")
    return "\n".join([header, _wrap_module("bracket", body)])


def generate_servo_mount_scad(sm: ServoMountSpec) -> str:
    dims = get_servo_dims(sm.servo_type)

    lines: list[str] = []
    lines.append(_header(f"servo_mount={sm.name} type={dims.name}"))
    lines.append(f"plate_w = {sm.plate_w_mm};")
    lines.append(f"plate_h = {sm.plate_h_mm};")
    lines.append(f"plate_t = {sm.plate_t_mm};")
    lines.append(f"clearance = {sm.clearance_mm};")
    lines.append(f"hole_d = {sm.hole_d_mm};")
    lines.append(f"body_w = {dims.body_w_mm};")
    lines.append(f"body_h = {dims.body_h_mm};")
    lines.append(f"flange_w = {dims.flange_w_mm};")
    lines.append(f"flange_h = {dims.flange_h_mm};")
    lines.append(f"hole_spacing_x = {dims.flange_hole_spacing_x_mm};")
    lines.append("")

    # Plate with a rectangular cutout for servo body and two flange holes.
    lines.append("difference() {")
    lines.append("  cube([plate_w, plate_h, plate_t], center=false);")
    # Body cutout centered
    lines.append("  translate([(plate_w-body_w-clearance*2)/2, (plate_h-body_h-clearance*2)/2, -1])")
    lines.append("    cube([body_w+clearance*2, body_h+clearance*2, plate_t+2], center=false);")
    # Flange hole pair along X axis, centered on plate
    lines.append("  translate([plate_w/2 - hole_spacing_x/2, plate_h/2, -1]) cylinder(h=plate_t+2, d=hole_d, center=false);")
    lines.append("  translate([plate_w/2 + hole_spacing_x/2, plate_h/2, -1]) cylinder(h=plate_t+2, d=hole_d, center=false);")
    lines.append("}")

    header = _header(f"servo_mount={sm.name} servo={sm.servo_type}")
    body = lines[len(header.splitlines()):]  # crude, but lines currently start with header
    # Rebuild body directly to avoid relying on the header length.
    d = get_servo_dims(sm.servo_type)
    clearance = sm.clearance_mm
    plate_w = sm.plate_w_mm
    plate_h = sm.plate_h_mm
    plate_t = sm.plate_t_mm
    hole_d = sm.hole_d_mm
    body_w = d.body_w_mm
    body_h = d.body_h_mm
    flange_w = d.flange_w_mm
    flange_h = d.flange_h_mm
    hole_spacing_x = d.flange_hole_spacing_x_mm

    body_lines: list[str] = []
    body_lines.append(f"plate_w = {plate_w}; plate_h = {plate_h}; plate_t = {plate_t};")
    body_lines.append(f"clearance = {clearance}; hole_d = {hole_d};")
    body_lines.append(f"body_w = {body_w}; body_h = {body_h}; flange_w = {flange_w}; flange_h = {flange_h};")
    body_lines.append(f"hole_spacing_x = {hole_spacing_x};")
    body_lines.append("difference() {")
    body_lines.append("  cube([plate_w, plate_h, plate_t], center=false);")
    body_lines.append("  translate([(plate_w-body_w-clearance*2)/2, (plate_h-body_h-clearance*2)/2, -1])")
    body_lines.append("    cube([body_w+clearance*2, body_h+clearance*2, plate_t+2], center=false);")
    body_lines.append("  translate([plate_w/2 - hole_spacing_x/2, plate_h/2, -1]) cylinder(h=plate_t+2, d=hole_d, center=false);")
    body_lines.append("  translate([plate_w/2 + hole_spacing_x/2, plate_h/2, -1]) cylinder(h=plate_t+2, d=hole_d, center=false);")
    body_lines.append("}")
    return "\n".join([header, _wrap_module("servo_mount", body_lines)])


def generate_linear_axis_parts_scad(axis: LinearAxisSpec) -> dict[str, str]:
    """
    Generate separate OpenSCAD part files for a belt-driven linear axis:
      - motor_mount.scad
      - idler_mount.scad
      - carriage.scad
      - assembly_preview.scad (non-printable helper)
    """
    parts: dict[str, str] = {}
    parts["motor_mount.scad"] = _wrap_module("motor_mount", _linear_axis_motor_mount_lines(axis))
    parts["idler_mount.scad"] = _wrap_module("idler_mount", _linear_axis_idler_mount_lines(axis))
    parts["carriage.scad"] = _wrap_module("carriage", _linear_axis_carriage_lines(axis))
    parts["belt_clamp.scad"] = _wrap_module("belt_clamp", _linear_axis_belt_clamp_lines(axis))
    if axis.include_rod_holders:
        parts["rod_holder.scad"] = _wrap_module("rod_holder", _linear_axis_rod_holder_lines(axis))
    if axis.include_tensioner:
        parts["tensioner_block.scad"] = _wrap_module("tensioner_block", _linear_axis_tensioner_lines(axis))
    if axis.include_endstops:
        parts["endstop_mount.scad"] = _wrap_module("endstop_mount", _linear_axis_endstop_mount_lines(axis))
    parts["assembly_preview.scad"] = _wrap_module("assembly_preview", _linear_axis_preview_lines(axis))
    return parts


def generate_leadscrew_axis_parts_scad(axis: LeadScrewAxisSpec) -> dict[str, str]:
    """
    Generate printable parts for a lead-screw axis:
      - motor_mount.scad (with coupler clearance)
      - screw_end_support.scad
      - carriage_nut_mount.scad
      - rod_holder.scad (reuse style)
      - endstop_mount.scad (reuse style)
      - assembly_preview.scad
    """
    parts: dict[str, str] = {}
    parts["ls_motor_mount.scad"] = _wrap_module("ls_motor_mount", _leadscrew_motor_mount_lines(axis))
    parts["ls_screw_end_support.scad"] = _wrap_module("ls_screw_end_support", _leadscrew_end_support_lines(axis))
    parts["ls_carriage_nut_mount.scad"] = _wrap_module("ls_carriage_nut_mount", _leadscrew_nut_carriage_lines(axis))
    if axis.include_rod_holders:
        # reuse the rod holder generator by mapping fields
        parts["rod_holder.scad"] = _wrap_module(
            "rod_holder",
            _linear_axis_rod_holder_lines(
            LinearAxisSpec.model_validate(
                {
                    "travel_mm": axis.travel_mm,
                    "rod_d_mm": axis.rod_d_mm,
                    "rod_spacing_mm": axis.rod_spacing_mm,
                    "rod_length_mm": axis.rod_length_mm,
                    "clearance_mm": axis.clearance_mm,
                    "wall_mm": axis.wall_mm,
                }
            )
            ),
        )
    if axis.include_endstops:
        parts["endstop_mount.scad"] = _wrap_module(
            "endstop_mount",
            _linear_axis_endstop_mount_lines(
            LinearAxisSpec.model_validate(
                {
                    "travel_mm": axis.travel_mm,
                    "rod_d_mm": axis.rod_d_mm,
                    "rod_spacing_mm": axis.rod_spacing_mm,
                    "rod_length_mm": axis.rod_length_mm,
                    "clearance_mm": axis.clearance_mm,
                    "wall_mm": axis.wall_mm,
                }
            )
            ),
        )
    parts["ls_assembly_preview.scad"] = _wrap_module("ls_assembly_preview", _leadscrew_preview_lines(axis))
    return parts


def generate_rotary_joint_parts_scad(joint: RotaryJointSpec) -> dict[str, str]:
    """
    Generate printable parts for a bearing-supported rotary joint:
      - rj_bearing_block.scad
      - rj_arm.scad
      - rj_preview.scad (helper)
    """
    parts: dict[str, str] = {}
    parts["rj_bearing_block.scad"] = _wrap_module("rj_bearing_block", _rotary_joint_block_lines(joint, with_header=False))
    parts["rj_arm.scad"] = _wrap_module("rj_arm", _rotary_joint_arm_lines(joint, with_header=False))
    parts["rj_preview.scad"] = _wrap_module("rj_preview", _rotary_joint_preview_lines(joint))
    return parts


def _leadscrew_motor_mount_lines(a: LeadScrewAxisSpec) -> list[str]:
    hole_spacing = NEMA17.hole_spacing_mm
    bore_d = NEMA17.bore_d_mm
    plate_w = max(70.0, a.rod_spacing_mm + 35.0)
    plate_h = 80.0
    t = a.wall_mm * 2.0
    coupler_clear_d = 20.0

    lines: list[str] = []
    lines.append(f"plate_w = {plate_w};")
    lines.append(f"plate_h = {plate_h};")
    lines.append(f"t = {t};")
    lines.append(f"hole_spacing = {hole_spacing};")
    lines.append(f"bore_d = {bore_d};")
    lines.append(f"coupler_d = {coupler_clear_d};")
    lines.append("difference() {")
    lines.append("  cube([plate_w, plate_h, t], center=false);")
    lines.append("  translate([plate_w/2, plate_h*0.6, -1]) cylinder(h=t+2, d=bore_d, center=false);")
    for sx in (-1, 1):
        for sy in (-1, 1):
            lines.append(f"  translate([plate_w/2 + {sx}*hole_spacing/2, plate_h*0.6 + {sy}*hole_spacing/2, -1]) cylinder(h=t+2, d={NEMA17.mount_hole_d_mm}, center=false);")
    # Coupler clearance
    lines.append("  translate([plate_w/2, plate_h*0.3, -1]) cylinder(h=t+2, d=coupler_d, center=false);")
    # Rod clearances
    clamp_d = a.rod_d_mm + 2.0
    y = 12.0
    lines.append(f"  translate([plate_w/2 - {a.rod_spacing_mm}/2, {y}, -1]) cylinder(h=t+2, d={clamp_d}, center=false);")
    lines.append(f"  translate([plate_w/2 + {a.rod_spacing_mm}/2, {y}, -1]) cylinder(h=t+2, d={clamp_d}, center=false);")
    # Leadscrew clearance
    lines.append(f"  translate([plate_w/2, {y}, -1]) cylinder(h=t+2, d={a.screw_d_mm + 2.0}, center=false);")
    lines.append("}")
    return lines


def _leadscrew_end_support_lines(a: LeadScrewAxisSpec) -> list[str]:
    w = max(70.0, a.rod_spacing_mm + 35.0)
    h = 70.0
    t = a.wall_mm * 2.0
    bearing_d = 22.2
    bearing_t = 7.2

    lines: list[str] = []
    lines.append(f"w = {w}; h = {h}; t = {t};")
    lines.append("difference(){")
    lines.append(f"  cube([w, h, t], center=false);")
    # Bearing pocket
    lines.append(f"  translate([w/2, h*0.6, t - {bearing_t}]) cylinder(h={bearing_t+1}, d={bearing_d}, center=false);")
    # Leadscrew pass-through
    lines.append(f"  translate([w/2, h*0.6, -1]) cylinder(h={t+2}, d={a.screw_d_mm + 1.0}, center=false);")
    # Rod clearances
    clamp_d = a.rod_d_mm + 2.0
    y = h * 0.25
    lines.append(f"  translate([w/2 - {a.rod_spacing_mm}/2, {y}, -1]) cylinder(h={t+2}, d={clamp_d}, center=false);")
    lines.append(f"  translate([w/2 + {a.rod_spacing_mm}/2, {y}, -1]) cylinder(h={t+2}, d={clamp_d}, center=false);")
    lines.append("}")
    return lines


def _leadscrew_nut_carriage_lines(a: LeadScrewAxisSpec) -> list[str]:
    w = a.rod_spacing_mm + a.rod_d_mm + 26.0
    h = a.rod_d_mm + 26.0
    t = max(14.0, a.wall_mm * 4.0)
    rod_clear = a.rod_d_mm + a.clearance_mm * 2.0
    nut_w = 22.0
    nut_h = 22.0
    nut_t = 12.0

    lines: list[str] = []
    lines.append("difference(){")
    lines.append(f"  cube([{w}, {h}, {t}], center=false);")
    lines.append(f"  translate([{w/2 - a.rod_spacing_mm/2}, {h/2}, -1]) cylinder(h={t+2}, d={rod_clear}, center=false);")
    lines.append(f"  translate([{w/2 + a.rod_spacing_mm/2}, {h/2}, -1]) cylinder(h={t+2}, d={rod_clear}, center=false);")
    lines.append(f"  translate([{w/2 - nut_w/2}, {h/2 - nut_h/2}, {t/2 - nut_t/2}]) cube([{nut_w}, {nut_h}, {nut_t}], center=false);")
    lines.append(f"  translate([{w/2}, {h/2}, -1]) cylinder(h={t+2}, d={a.screw_d_mm + 2.0}, center=false);")
    lines.append("}")
    return lines


def _leadscrew_preview_lines(a: LeadScrewAxisSpec) -> list[str]:
    lines: list[str] = []
    lines.append(f"rod_d = {a.rod_d_mm};")
    lines.append(f"rod_spacing = {a.rod_spacing_mm};")
    lines.append(f"rod_len = {a.rod_length_mm};")
    lines.append(f"screw_d = {a.screw_d_mm};")
    lines.append(f"screw_len = {a.screw_length_mm};")
    lines.append("")
    lines.append("color([0.7,0.7,0.7]) {")
    lines.append("  translate([0, -rod_spacing/2, 0]) rotate([0,90,0]) cylinder(h=rod_len, d=rod_d, center=false);")
    lines.append("  translate([0,  rod_spacing/2, 0]) rotate([0,90,0]) cylinder(h=rod_len, d=rod_d, center=false);")
    lines.append("}")
    lines.append("color([0.2,0.2,0.2]) translate([0,0,0]) rotate([0,90,0]) cylinder(h=screw_len, d=screw_d, center=false);")
    if a.frame == "2020_extrusion":
        lines.append("color([0.3,0.3,0.3]) translate([0, -25, -10]) cube([rod_len, 20, 20], center=false);")
        lines.append("color([0.3,0.3,0.3]) translate([0,  5, -10]) cube([rod_len, 20, 20], center=false);")
    lines.append("// Import and position printable parts manually for full assembly.")
    return lines


def _linear_axis_motor_mount_lines(a: LinearAxisSpec) -> list[str]:
    hole_spacing = NEMA17.hole_spacing_mm
    bore_d = NEMA17.bore_d_mm
    plate_w = max(60.0, a.rod_spacing_mm + 30.0)
    plate_h = 70.0
    t = a.wall_mm * 2.0

    lines: list[str] = []
    lines.append(f"plate_w = {plate_w};")
    lines.append(f"plate_h = {plate_h};")
    lines.append(f"t = {t};")
    lines.append(f"hole_spacing = {hole_spacing};")
    lines.append(f"bore_d = {bore_d};")
    lines.append(f"mount_hole_d = {NEMA17.mount_hole_d_mm};")
    lines.append("difference() {")
    lines.append("  cube([plate_w, plate_h, t], center=false);")
    lines.append("  translate([plate_w/2, plate_h/2, -1]) cylinder(h=t+2, d=bore_d, center=false);")
    for sx in (-1, 1):
        for sy in (-1, 1):
            lines.append(
                f"  translate([plate_w/2 + {sx}*hole_spacing/2, plate_h/2 + {sy}*hole_spacing/2, -1]) cylinder(h=t+2, d=mount_hole_d, center=false);"
            )
    clamp_d = a.rod_d_mm + 2.0
    y = 12.0
    lines.append("  // rod clearances")
    lines.append(f"  translate([plate_w/2 - {a.rod_spacing_mm}/2, {y}, -1]) cylinder(h=t+2, d={clamp_d}, center=false);")
    lines.append(f"  translate([plate_w/2 + {a.rod_spacing_mm}/2, {y}, -1]) cylinder(h=t+2, d={clamp_d}, center=false);")
    lines.append("}")
    return lines


def _linear_axis_idler_mount_lines(a: LinearAxisSpec) -> list[str]:
    plate_w = max(60.0, a.rod_spacing_mm + 30.0)
    plate_h = 55.0
    t = a.wall_mm * 2.0
    idler_bolt_d = 5.2
    idler_slot_w = 12.0
    idler_slot_h = 18.0

    lines: list[str] = []
    lines.append(f"plate_w = {plate_w};")
    lines.append(f"plate_h = {plate_h};")
    lines.append(f"t = {t};")
    lines.append("difference() {")
    lines.append("  cube([plate_w, plate_h, t], center=false);")
    lines.append(f"  translate([plate_w/2 - {idler_slot_w}/2, plate_h/2 - {idler_slot_h}/2, -1]) cube([{idler_slot_w}, {idler_slot_h}, t+2], center=false);")
    lines.append(f"  translate([plate_w/2, plate_h/2, -1]) cylinder(h=t+2, d={idler_bolt_d}, center=false);")
    clamp_d = a.rod_d_mm + 2.0
    y = 10.0
    lines.append(f"  translate([plate_w/2 - {a.rod_spacing_mm}/2, {y}, -1]) cylinder(h=t+2, d={clamp_d}, center=false);")
    lines.append(f"  translate([plate_w/2 + {a.rod_spacing_mm}/2, {y}, -1]) cylinder(h=t+2, d={clamp_d}, center=false);")
    lines.append("}")
    return lines


def _linear_axis_carriage_lines(a: LinearAxisSpec) -> list[str]:
    w = a.rod_spacing_mm + a.rod_d_mm + 20.0
    h = a.rod_d_mm + 20.0
    t = max(10.0, a.wall_mm * 3.0)
    rod_clear = a.rod_d_mm + a.clearance_mm * 2.0

    lines: list[str] = []
    lines.append(f"w = {w}; h = {h}; t = {t};")
    lines.append(f"rod_clear = {rod_clear}; rod_spacing = {a.rod_spacing_mm};")
    lines.append(f"belt_w = {a.belt_width_mm}; belt_slot_h = 2.4;")
    lines.append("difference() {")
    lines.append("  cube([w, h, t], center=false);")
    lines.append("  // rod bores")
    lines.append("  translate([w/2 - rod_spacing/2, h/2, -1]) cylinder(h=t+2, d=rod_clear, center=false);")
    lines.append("  translate([w/2 + rod_spacing/2, h/2, -1]) cylinder(h=t+2, d=rod_clear, center=false);")
    lines.append("  // belt slot")
    lines.append("  translate([w/2 - 14, h/2 - belt_w/2, t/2 - belt_slot_h/2]) cube([28, belt_w, belt_slot_h], center=false);")
    lines.append("}")
    return lines


def _linear_axis_preview_lines(a: LinearAxisSpec) -> list[str]:
    lines: list[str] = []
    lines.append(f"rod_d = {a.rod_d_mm};")
    lines.append(f"rod_spacing = {a.rod_spacing_mm};")
    lines.append(f"rod_len = {a.rod_length_mm};")
    lines.append("")
    lines.append("module rods(){")
    lines.append("  color([0.7,0.7,0.7]) {")
    lines.append("    translate([0, -rod_spacing/2, 0]) rotate([0,90,0]) cylinder(h=rod_len, d=rod_d, center=false);")
    lines.append("    translate([0,  rod_spacing/2, 0]) rotate([0,90,0]) cylinder(h=rod_len, d=rod_d, center=false);")
    lines.append("  }")
    lines.append("}")
    lines.append("rods();")
    if a.frame == "2020_extrusion":
        lines.append("color([0.3,0.3,0.3]) translate([0, -25, -10]) cube([rod_len, 20, 20], center=false);")
        lines.append("color([0.3,0.3,0.3]) translate([0,  5, -10]) cube([rod_len, 20, 20], center=false);")
    lines.append("color([0.1,0.1,0.1]) translate([0,0,rod_d/2]) cube([rod_len, 2, 1], center=false);")
    lines.append("// Import and position printable parts manually if you want a full assembly preview.")
    return lines


def _linear_axis_belt_clamp_lines(a: LinearAxisSpec) -> list[str]:
    w = 30.0
    h = 16.0
    t = max(4.0, a.wall_mm * 2.0)
    hole_d = 3.2
    slot_w = a.belt_width_mm + 1.0
    slot_l = 18.0

    lines: list[str] = []
    lines.append("difference() {")
    lines.append(f"  cube([{w}, {h}, {t}], center=false);")
    lines.append(f"  translate([{w/2 - slot_l/2}, {h/2 - slot_w/2}, {t/2 - 1.2}]) cube([{slot_l}, {slot_w}, 2.4], center=false);")
    lines.append(f"  translate([{w*0.25}, {h/2}, -1]) cylinder(h={t+2}, d={hole_d}, center=false);")
    lines.append(f"  translate([{w*0.75}, {h/2}, -1]) cylinder(h={t+2}, d={hole_d}, center=false);")
    lines.append("}")
    return lines


def _linear_axis_tensioner_lines(a: LinearAxisSpec) -> list[str]:
    w = 40.0
    h = 25.0
    t = max(10.0, a.wall_mm * 3.0)
    slot_w = 6.0
    slot_l = 20.0
    bolt_d = 5.2

    lines: list[str] = []
    lines.append("difference() {")
    lines.append(f"  cube([{w}, {h}, {t}], center=false);")
    lines.append(f"  translate([{w/2 - slot_l/2}, {h/2 - slot_w/2}, -1]) cube([{slot_l}, {slot_w}, {t+2}], center=false);")
    lines.append(f"  translate([{w/2}, {h/2}, -1]) cylinder(h={t+2}, d={bolt_d}, center=false);")
    lines.append("}")
    return lines


def _linear_axis_endstop_mount_lines(a: LinearAxisSpec) -> list[str]:
    w = 30.0
    h = 20.0
    t = max(4.0, a.wall_mm * 2.0)
    hole_d = 2.2

    lines: list[str] = []
    lines.append("difference() {")
    lines.append(f"  cube([{w}, {h}, {t}], center=false);")
    lines.append(f"  translate([{w*0.35}, {h*0.5}, -1]) cylinder(h={t+2}, d={hole_d}, center=false);")
    lines.append(f"  translate([{w*0.65}, {h*0.5}, -1]) cylinder(h={t+2}, d={hole_d}, center=false);")
    lines.append(f"  translate([{w/2 - 8}, {h - 6}, {t/2 - 1}]) cube([16, 5, 2], center=false);")
    lines.append("}")
    return lines


def _linear_axis_rod_holder_lines(a: LinearAxisSpec) -> list[str]:
    rod_d = a.rod_d_mm
    clear = a.clearance_mm
    od = rod_d + 10.0
    w = 24.0
    h = 18.0
    t = max(10.0, a.wall_mm * 3.0)
    slit = 1.5
    bolt_d = 3.2 if a.rod_holder_bolt == "m3" else 2.2
    nut_flat = 5.6 if a.rod_holder_bolt == "m3" else 4.0

    lines: list[str] = []
    lines.append(f"rod_clear = {rod_d + clear*2};")
    lines.append(f"od = {od}; w = {w}; t = {t}; slit = {slit};")
    lines.append(f"bolt_d = {bolt_d}; nut_flat = {nut_flat};")
    lines.append("difference() {")
    lines.append("  cube([w, od, t], center=false);")
    lines.append("  translate([w/2, od/2, -1]) cylinder(h=t+2, d=rod_clear, center=false);")
    lines.append("  translate([w/2 - slit/2, 0, -1]) cube([slit, od, t+2], center=false);")
    lines.append("  translate([w*0.25, od*0.25, -1]) cylinder(h=t+2, d=bolt_d, center=false);")
    lines.append("  translate([w*0.75, od*0.75, -1]) cylinder(h=t+2, d=bolt_d, center=false);")
    lines.append("  translate([w*0.25, od*0.25, 0]) cylinder(h=4, d=nut_flat, $fn=6, center=false);")
    lines.append("  translate([w*0.75, od*0.75, 0]) cylinder(h=4, d=nut_flat, $fn=6, center=false);")
    lines.append("}")
    return lines


def _rotary_joint_block_lines(j: RotaryJointSpec, *, with_header: bool) -> list[str]:
    b = get_bearing_dims(j.bearing)
    pocket_d = b.od_mm + 2 * j.clearance_mm
    pocket_h = b.width_mm + j.clearance_mm

    # Ensure a minimum block thickness around the bearing.
    w = max(j.block_w_mm, pocket_d + 2 * j.wall_mm)
    d = max(j.block_d_mm, pocket_d + 2 * j.wall_mm)
    h = max(j.block_h_mm, pocket_h + 2.0)

    hx = j.mount_hole_spacing_x_mm / 2.0
    hy = j.mount_hole_spacing_y_mm / 2.0

    lines: list[str] = []
    if with_header:
        lines.append(_header(f"rotary_joint_block name={j.name} bearing={j.bearing}"))
    lines.append(f"w = {w}; d = {d}; h = {h};")
    lines.append(f"pocket_d = {pocket_d}; pocket_h = {pocket_h};")
    lines.append(f"hole_d = {j.mount_hole_d_mm};")
    lines.append(f"hx = {hx}; hy = {hy};")
    lines.append("difference() {")
    lines.append("  cube([w, d, h], center=false);")
    # Bearing pocket (top-down)
    lines.append("  translate([w/2, d/2, h-pocket_h]) cylinder(h=pocket_h+1, d=pocket_d, center=false);")
    # Through shaft hole
    lines.append(f"  translate([w/2, d/2, -1]) cylinder(h=h+2, d={b.id_mm + 2 * j.clearance_mm}, center=false);")
    # Mounting holes (4-corner pattern)
    for sx in (-1, 1):
        for sy in (-1, 1):
            lines.append(f"  translate([w/2 + {sx}*hx, d/2 + {sy}*hy, -1]) cylinder(h=h+2, d=hole_d, center=false);")
    lines.append("}")
    return lines


def _rotary_joint_arm_lines(j: RotaryJointSpec, *, with_header: bool) -> list[str]:
    b = get_bearing_dims(j.bearing)
    shaft_hole_d = max(j.shaft_d_mm, b.id_mm) + 2 * j.clearance_mm

    lines: list[str] = []
    if with_header:
        lines.append(_header(f"rotary_joint_arm name={j.name}"))
    lines.append(f"len = {j.arm_len_mm}; w = {j.arm_w_mm}; t = {j.arm_t_mm};")
    lines.append(f"shaft_hole_d = {shaft_hole_d};")
    lines.append(f"hole_d = {j.arm_hole_d_mm}; pitch = {j.arm_hole_pitch_mm}; n = {j.arm_hole_count};")
    lines.append("difference() {")
    lines.append("  cube([len, w, t], center=false);")
    # Shaft hole near one end (centered on width)
    lines.append("  translate([w/2, w/2, -1]) cylinder(h=t+2, d=shaft_hole_d, center=false);")
    # Utility holes along the arm (centered)
    lines.append("  for (i=[0:n-1]) {")
    lines.append("    x = w/2 + (i+1)*pitch;")
    lines.append("    if (x < len - w/2) translate([x, w/2, -1]) cylinder(h=t+2, d=hole_d, center=false);")
    lines.append("  }")
    lines.append("}")
    return lines


def _rotary_joint_preview_lines(j: RotaryJointSpec) -> list[str]:
    b = get_bearing_dims(j.bearing)
    pocket_d = b.od_mm + 2 * j.clearance_mm
    pocket_h = b.width_mm + j.clearance_mm
    w = max(j.block_w_mm, pocket_d + 2 * j.wall_mm)
    d = max(j.block_d_mm, pocket_d + 2 * j.wall_mm)
    h = max(j.block_h_mm, pocket_h + 2.0)

    lines: list[str] = []
    lines.append("// Preview: block + arm placed next to each other.")
    lines.extend(_rotary_joint_block_lines(j, with_header=False))
    lines.append("")
    lines.append(f"translate([{w + 10}, 0, 0]) {{")
    for l in _rotary_joint_arm_lines(j, with_header=False):
        lines.append(f"  {l}")
    lines.append("}")
    return lines


def generate_belt_reduction_parts_scad(stage: BeltReductionSpec) -> dict[str, str]:
    parts: dict[str, str] = {}
    parts["br_reduction_plate.scad"] = _wrap_module("br_reduction_plate", _belt_reduction_plate_lines(stage))
    parts["br_preview.scad"] = _wrap_module("br_preview", _belt_reduction_preview_lines(stage))
    return parts


def _belt_reduction_plate_lines(s: BeltReductionSpec) -> list[str]:
    hole_spacing = NEMA17.hole_spacing_mm
    bore_d = NEMA17.bore_d_mm
    b = get_bearing_dims("625zz")
    bearing_pocket_d = b.od_mm + 2 * s.clearance_mm
    shaft_hole_d = b.id_mm + 2 * s.clearance_mm

    # Place motor near left; driven shaft to the right; idler optionally above/below.
    mx = 28.0
    my = s.plate_h_mm / 2.0
    dx = mx + s.center_distance_mm
    dy = my
    ix = mx + s.center_distance_mm / 2.0
    iy = my + (s.idler_offset_mm if s.include_idler else 0.0)

    lines: list[str] = []
    lines.append(f"w={s.plate_w_mm}; h={s.plate_h_mm}; t={s.plate_t_mm};")
    lines.append("difference() {")
    lines.append("  cube([w, h, t], center=false);")
    # Motor bore + holes
    lines.append(f"  translate([{mx}, {my}, -1]) cylinder(h=t+2, d={bore_d}, center=false);")
    for sx in (-1, 1):
        for sy in (-1, 1):
            lines.append(
                f"  translate([{mx} + {sx}*{hole_spacing}/2, {my} + {sy}*{hole_spacing}/2, -1]) cylinder(h=t+2, d={NEMA17.mount_hole_d_mm}, center=false);"
            )
    # Driven shaft bearing pocket + through hole
    lines.append(f"  translate([{dx}, {dy}, t-({b.width_mm + s.clearance_mm})]) cylinder(h={b.width_mm + s.clearance_mm + 1}, d={bearing_pocket_d}, center=false);")
    lines.append(f"  translate([{dx}, {dy}, -1]) cylinder(h=t+2, d={shaft_hole_d}, center=false);")
    # Idler pocket if enabled
    if s.include_idler:
        lines.append(f"  translate([{ix}, {iy}, t-({b.width_mm + s.clearance_mm})]) cylinder(h={b.width_mm + s.clearance_mm + 1}, d={bearing_pocket_d}, center=false);")
        lines.append(f"  translate([{ix}, {iy}, -1]) cylinder(h=t+2, d={shaft_hole_d}, center=false);")
    lines.append("}")
    return lines


def _belt_reduction_preview_lines(s: BeltReductionSpec) -> list[str]:
    ratio = float(s.driven_pulley_teeth) / float(s.motor_pulley_teeth)
    lines: list[str] = []
    lines.append(f"// GT2 belt reduction stage preview (ratio ~{ratio:.2f}:1)")
    lines.append("br_reduction_plate();")
    lines.append("// Note: add real pulleys/belt/shafts; this preview only shows the mounting plate.")
    return lines


def generate_gripper_parts_scad(g: GripperSpec) -> dict[str, str]:
    parts: dict[str, str] = {}
    parts["gr_base.scad"] = _wrap_module("gr_base", _gripper_base_lines(g))
    parts["gr_jaw_left.scad"] = _wrap_module("gr_jaw_left", _gripper_jaw_lines(g, side=-1))
    parts["gr_jaw_right.scad"] = _wrap_module("gr_jaw_right", _gripper_jaw_lines(g, side=1))
    parts["gr_link.scad"] = _wrap_module("gr_link", _gripper_link_lines(g))
    parts["gr_preview.scad"] = _wrap_module("gr_preview", _gripper_preview_lines(g))
    return parts


def _gripper_base_lines(g: GripperSpec) -> list[str]:
    d = get_servo_dims(g.servo_type)
    body_lines: list[str] = []
    body_lines.append(f"w={g.base_w_mm}; h={g.base_h_mm}; t={g.base_t_mm};")
    body_lines.append("difference() {")
    body_lines.append("  cube([w,h,t], center=false);")
    # Servo cutout centered
    body_lines.append(f"  translate([(w-{d.body_w_mm}-2*{g.clearance_mm})/2, (h-{d.body_h_mm}-2*{g.clearance_mm})/2, -1])")
    body_lines.append(f"    cube([{d.body_w_mm}+2*{g.clearance_mm}, {d.body_h_mm}+2*{g.clearance_mm}, t+2], center=false);")
    # Jaw pivots near front edge, symmetric
    px = g.base_w_mm / 2.0
    py = g.base_h_mm * 0.25
    offset = 18.0
    body_lines.append(f"  translate([{px - offset}, {py}, -1]) cylinder(h=t+2, d={g.jaw_pivot_hole_d_mm}, center=false);")
    body_lines.append(f"  translate([{px + offset}, {py}, -1]) cylinder(h=t+2, d={g.jaw_pivot_hole_d_mm}, center=false);")
    body_lines.append("}")
    return body_lines


def _gripper_jaw_lines(g: GripperSpec, *, side: int) -> list[str]:
    # side: -1 left, +1 right (mirrored pattern)
    lines: list[str] = []
    lines.append(f"len={g.jaw_len_mm}; w={g.jaw_w_mm}; t={g.jaw_t_mm};")
    lines.append("difference() {")
    lines.append("  cube([len,w,t], center=false);")
    # Pivot hole at one end
    lines.append(f"  translate([w/2, w/2, -1]) cylinder(h=t+2, d={g.jaw_pivot_hole_d_mm}, center=false);")
    # Link hole along the jaw
    link_x = max(g.jaw_w_mm, g.jaw_len_mm * 0.45)
    lines.append(f"  translate([{link_x:.2f}, w/2, -1]) cylinder(h=t+2, d={g.link_hole_d_mm}, center=false);")
    lines.append("}")
    if side < 0:
        return ["mirror([0,1,0]) {"] + [f"  {l}" for l in lines] + ["}"]
    return lines


def _gripper_link_lines(g: GripperSpec) -> list[str]:
    lines: list[str] = []
    lines.append(f"w={g.link_w_mm}; t={g.link_t_mm};")
    lines.append("len = 50;")
    lines.append("difference() {")
    lines.append("  cube([len,w,t], center=false);")
    lines.append(f"  translate([w/2, w/2, -1]) cylinder(h=t+2, d={g.link_hole_d_mm}, center=false);")
    lines.append(f"  translate([len-w/2, w/2, -1]) cylinder(h=t+2, d={g.link_hole_d_mm}, center=false);")
    lines.append("}")
    return lines


def _gripper_preview_lines(g: GripperSpec) -> list[str]:
    lines: list[str] = []
    lines.append("// Scissor gripper preview (non-kinematic).")
    lines.append("gr_base();")
    lines.append("translate([10, 0, 8]) gr_jaw_left();")
    lines.append("translate([60, 0, 8]) gr_jaw_right();")
    lines.append("// Note: assemble with real fasteners; iterate pivot spacing/geometry as needed.")
    return lines


def generate_pan_tilt_parts_scad(pt: PanTiltSpec) -> dict[str, str]:
    parts: dict[str, str] = {}
    parts["pt_base.scad"] = _wrap_module("pt_base", _pan_tilt_base_lines(pt))
    parts["pt_bracket.scad"] = _wrap_module("pt_bracket", _pan_tilt_bracket_lines(pt))
    parts["pt_platform.scad"] = _wrap_module("pt_platform", _pan_tilt_platform_lines(pt))
    parts["pt_preview.scad"] = _wrap_module("pt_preview", _pan_tilt_preview_lines(pt))
    return parts


def _pan_tilt_base_lines(pt: PanTiltSpec) -> list[str]:
    s = get_servo_dims(pt.pan_servo)
    lines: list[str] = []
    lines.append(f"w={pt.base_w_mm}; h={pt.base_h_mm}; t={pt.base_t_mm};")
    lines.append("difference() {")
    lines.append("  cube([w,h,t], center=false);")
    lines.append(f"  translate([(w-{s.body_w_mm}-2*{pt.clearance_mm})/2, (h-{s.body_h_mm}-2*{pt.clearance_mm})/2, -1])")
    lines.append(f"    cube([{s.body_w_mm}+2*{pt.clearance_mm}, {s.body_h_mm}+2*{pt.clearance_mm}, t+2], center=false);")
    lines.append("}")
    return lines


def _pan_tilt_bracket_lines(pt: PanTiltSpec) -> list[str]:
    s = get_servo_dims(pt.tilt_servo)
    lines: list[str] = []
    lines.append(f"w={pt.bracket_w_mm}; h={pt.bracket_h_mm}; t={pt.bracket_t_mm};")
    lines.append("difference() {")
    lines.append("  cube([w,h,t], center=false);")
    lines.append(f"  translate([(w-{s.body_w_mm}-2*{pt.clearance_mm})/2, (h-{s.body_h_mm}-2*{pt.clearance_mm})/2, -1])")
    lines.append(f"    cube([{s.body_w_mm}+2*{pt.clearance_mm}, {s.body_h_mm}+2*{pt.clearance_mm}, t+2], center=false);")
    lines.append("}")
    return lines


def _pan_tilt_platform_lines(pt: PanTiltSpec) -> list[str]:
    lines: list[str] = []
    lines.append(f"w={pt.platform_w_mm}; h={pt.platform_h_mm}; t={pt.platform_t_mm};")
    lines.append("cube([w,h,t], center=false);")
    return lines


def _pan_tilt_preview_lines(pt: PanTiltSpec) -> list[str]:
    lines: list[str] = []
    lines.append("// Pan/tilt preview (non-kinematic).")
    lines.append("pt_base();")
    lines.append(f"translate([{pt.base_w_mm + 10}, 0, 0]) pt_bracket();")
    lines.append(f"translate([{pt.base_w_mm + pt.bracket_w_mm + 20}, 0, 0]) pt_platform();")
    return lines



def _leadscrew_end_support(a: LeadScrewAxisSpec) -> str:
    # Simple end support block with a bearing seat (608-ish) and rod clearances.
    w = max(70.0, a.rod_spacing_mm + 35.0)
    h = 40.0
    t = max(14.0, a.wall_mm * 4.0)
    bearing_d = 22.2  # 608 bearing OD approx
    bearing_t = 7.2
    lines: list[str] = []
    lines.append(_header(f"leadscrew_end_support name={a.name}"))
    lines.append("difference(){")
    lines.append(f"  cube([{w}, {h}, {t}], center=false);")
    # Bearing pocket
    lines.append(f"  translate([{w/2}, {h*0.6}, {t - bearing_t}]) cylinder(h={bearing_t+1}, d={bearing_d}, center=false);")
    # Leadscrew pass-through
    lines.append(f"  translate([{w/2}, {h*0.6}, -1]) cylinder(h={t+2}, d={a.screw_d_mm + 1.0}, center=false);")
    # Rod clearances
    clamp_d = a.rod_d_mm + 2.0
    y = h * 0.25
    lines.append(f"  translate([{w/2 - a.rod_spacing_mm/2}, {y}, -1]) cylinder(h={t+2}, d={clamp_d}, center=false);")
    lines.append(f"  translate([{w/2 + a.rod_spacing_mm/2}, {y}, -1]) cylinder(h={t+2}, d={clamp_d}, center=false);")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _leadscrew_nut_carriage(a: LeadScrewAxisSpec) -> str:
    # Simple carriage around rods + rectangular nut cavity.
    w = a.rod_spacing_mm + a.rod_d_mm + 26.0
    h = a.rod_d_mm + 26.0
    t = max(14.0, a.wall_mm * 4.0)
    rod_clear = a.rod_d_mm + a.clearance_mm * 2.0
    nut_w = 22.0
    nut_h = 22.0
    nut_t = 12.0

    lines: list[str] = []
    lines.append(_header(f"leadscrew_carriage_nut_mount name={a.name}"))
    lines.append("difference(){")
    lines.append(f"  cube([{w}, {h}, {t}], center=false);")
    # Rod bores
    lines.append(f"  translate([{w/2 - a.rod_spacing_mm/2}, {h/2}, -1]) cylinder(h={t+2}, d={rod_clear}, center=false);")
    lines.append(f"  translate([{w/2 + a.rod_spacing_mm/2}, {h/2}, -1]) cylinder(h={t+2}, d={rod_clear}, center=false);")
    # Nut cavity centered
    lines.append(f"  translate([{w/2 - nut_w/2}, {h/2 - nut_h/2}, {t/2 - nut_t/2}]) cube([{nut_w}, {nut_h}, {nut_t}], center=false);")
    # Leadscrew clearance
    lines.append(f"  translate([{w/2}, {h/2}, -1]) cylinder(h={t+2}, d={a.screw_d_mm + 2.0}, center=false);")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _leadscrew_preview(a: LeadScrewAxisSpec) -> str:
    lines: list[str] = []
    lines.append(_header(f"leadscrew_axis_preview name={a.name}"))
    lines.append(f"rod_d = {a.rod_d_mm};")
    lines.append(f"rod_spacing = {a.rod_spacing_mm};")
    lines.append(f"rod_len = {a.rod_length_mm};")
    lines.append(f"screw_d = {a.screw_d_mm};")
    lines.append(f"screw_len = {a.screw_length_mm};")
    lines.append("")
    lines.append("color([0.7,0.7,0.7]) {")
    lines.append("  translate([0, -rod_spacing/2, 0]) rotate([0,90,0]) cylinder(h=rod_len, d=rod_d, center=false);")
    lines.append("  translate([0,  rod_spacing/2, 0]) rotate([0,90,0]) cylinder(h=rod_len, d=rod_d, center=false);")
    lines.append("}")
    lines.append("color([0.2,0.2,0.2]) translate([0,0,0]) rotate([0,90,0]) cylinder(h=screw_len, d=screw_d, center=false);")
    if a.frame == "2020_extrusion":
        lines.append("color([0.3,0.3,0.3]) translate([0, -25, -10]) cube([rod_len, 20, 20], center=false);")
        lines.append("color([0.3,0.3,0.3]) translate([0,  5, -10]) cube([rod_len, 20, 20], center=false);")
    lines.append("// Import and position printable parts manually for full assembly.")
    return "\n".join(lines) + "\n"


def _linear_axis_motor_mount(a: LinearAxisSpec) -> str:
    # NEMA17 face pattern constants (approx): 31mm hole spacing, 22mm center bore clearance.
    hole_spacing = 31.0
    bore_d = 22.0
    plate_w = max(60.0, a.rod_spacing_mm + 30.0)
    plate_h = 70.0
    t = a.wall_mm * 2.0

    lines: list[str] = []
    lines.append(_header(f"linear_axis_motor_mount name={a.name}"))
    lines.append(f"plate_w = {plate_w};")
    lines.append(f"plate_h = {plate_h};")
    lines.append(f"t = {t};")
    lines.append(f"hole_spacing = {hole_spacing};")
    lines.append(f"bore_d = {bore_d};")
    lines.append(f"mount_hole_d = 3.4;")
    lines.append("")
    lines.append("difference() {")
    lines.append("  cube([plate_w, plate_h, t], center=false);")
    lines.append("  translate([plate_w/2, plate_h/2, -1]) cylinder(h=t+2, d=bore_d, center=false);")
    for sx in (-1, 1):
        for sy in (-1, 1):
            lines.append(f"  translate([plate_w/2 + {sx}*hole_spacing/2, plate_h/2 + {sy}*hole_spacing/2, -1]) cylinder(h=t+2, d=mount_hole_d, center=false);")
    # Rod clamp through-holes (2)
    clamp_d = a.rod_d_mm + 2.0
    y = 12.0
    lines.append(f"  // rod clearances")
    lines.append(f"  translate([plate_w/2 - {a.rod_spacing_mm}/2, {y}, -1]) cylinder(h=t+2, d={clamp_d}, center=false);")
    lines.append(f"  translate([plate_w/2 + {a.rod_spacing_mm}/2, {y}, -1]) cylinder(h=t+2, d={clamp_d}, center=false);")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _linear_axis_idler_mount(a: LinearAxisSpec) -> str:
    plate_w = max(60.0, a.rod_spacing_mm + 30.0)
    plate_h = 55.0
    t = a.wall_mm * 2.0
    idler_bolt_d = 5.2  # M5 clearance (common idler bolt)
    idler_slot_w = 12.0
    idler_slot_h = 18.0

    lines: list[str] = []
    lines.append(_header(f"linear_axis_idler_mount name={a.name}"))
    lines.append(f"plate_w = {plate_w};")
    lines.append(f"plate_h = {plate_h};")
    lines.append(f"t = {t};")
    lines.append("")
    lines.append("difference() {")
    lines.append("  cube([plate_w, plate_h, t], center=false);")
    # Tension slot (rect) centered
    lines.append(f"  translate([plate_w/2 - {idler_slot_w}/2, plate_h/2 - {idler_slot_h}/2, -1]) cube([{idler_slot_w}, {idler_slot_h}, t+2], center=false);")
    lines.append(f"  translate([plate_w/2, plate_h/2, -1]) cylinder(h=t+2, d={idler_bolt_d}, center=false);")
    # Rod clearance holes
    clamp_d = a.rod_d_mm + 2.0
    y = 10.0
    lines.append(f"  translate([plate_w/2 - {a.rod_spacing_mm}/2, {y}, -1]) cylinder(h=t+2, d={clamp_d}, center=false);")
    lines.append(f"  translate([plate_w/2 + {a.rod_spacing_mm}/2, {y}, -1]) cylinder(h=t+2, d={clamp_d}, center=false);")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _linear_axis_carriage(a: LinearAxisSpec) -> str:
    # Simple carriage block around two rods + belt clamp slot.
    w = a.rod_spacing_mm + a.rod_d_mm + 20.0
    h = a.rod_d_mm + 20.0
    t = max(10.0, a.wall_mm * 3.0)
    rod_clear = a.rod_d_mm + a.clearance_mm * 2.0

    lines: list[str] = []
    lines.append(_header(f"linear_axis_carriage name={a.name}"))
    lines.append(f"w = {w};")
    lines.append(f"h = {h};")
    lines.append(f"t = {t};")
    lines.append(f"rod_clear = {rod_clear};")
    lines.append(f"rod_spacing = {a.rod_spacing_mm};")
    lines.append(f"belt_w = {a.belt_width_mm};")
    lines.append(f"belt_slot_h = 2.4;")
    lines.append("")
    lines.append("difference() {")
    lines.append("  cube([w, h, t], center=false);")
    # Rod bores
    lines.append("  // rod bores")
    lines.append("  translate([w/2 - rod_spacing/2, h/2, -1]) cylinder(h=t+2, d=rod_clear, center=false);")
    lines.append("  translate([w/2 + rod_spacing/2, h/2, -1]) cylinder(h=t+2, d=rod_clear, center=false);")
    # Belt clamp slot
    lines.append("  // belt slot")
    lines.append("  translate([w/2 - 14, h/2 - belt_w/2, t/2 - belt_slot_h/2]) cube([28, belt_w, belt_slot_h], center=false);")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _linear_axis_preview(a: LinearAxisSpec) -> str:
    # Visual-only preview (not a printable assembly).
    # Draw rods and place printable parts as bounding boxes.
    lines: list[str] = []
    lines.append(_header(f"linear_axis_preview name={a.name}"))
    lines.append(f"rod_d = {a.rod_d_mm};")
    lines.append(f"rod_spacing = {a.rod_spacing_mm};")
    lines.append(f"rod_len = {a.rod_length_mm};")
    lines.append("")
    lines.append("module rods(){")
    lines.append("  color([0.7,0.7,0.7]) {")
    lines.append("    translate([0, -rod_spacing/2, 0]) rotate([0,90,0]) cylinder(h=rod_len, d=rod_d, center=false);")
    lines.append("    translate([0,  rod_spacing/2, 0]) rotate([0,90,0]) cylinder(h=rod_len, d=rod_d, center=false);")
    lines.append("  }")
    lines.append("}")
    lines.append("rods();")
    if a.frame == "2020_extrusion":
        # Simple extrusion visual (not accurate profile): two rails under the rods.
        lines.append("color([0.3,0.3,0.3]) translate([0, -25, -10]) cube([rod_len, 20, 20], center=false);")
        lines.append("color([0.3,0.3,0.3]) translate([0,  5, -10]) cube([rod_len, 20, 20], center=false);")
    lines.append("// Quick belt path hint (2D line placeholder)")
    lines.append("color([0.1,0.1,0.1]) translate([0,0,rod_d/2]) cube([rod_len, 2, 1], center=false);")
    lines.append("// Import and position printable parts manually if you want a full assembly preview.")
    return "\n".join(lines) + "\n"


def _linear_axis_belt_clamp(a: LinearAxisSpec) -> str:
    # Simple belt clamp plate: two M3 holes and a slot for GT2 belt.
    w = 30.0
    h = 16.0
    t = max(4.0, a.wall_mm * 2.0)
    hole_d = 3.2
    slot_w = a.belt_width_mm + 1.0
    slot_l = 18.0

    lines: list[str] = []
    lines.append(_header(f"linear_axis_belt_clamp name={a.name}"))
    lines.append("difference() {")
    lines.append(f"  cube([{w}, {h}, {t}], center=false);")
    lines.append(f"  translate([{w/2 - slot_l/2}, {h/2 - slot_w/2}, {t/2 - 1.2}]) cube([{slot_l}, {slot_w}, 2.4], center=false);")
    lines.append(f"  translate([{w*0.25}, {h/2}, -1]) cylinder(h={t+2}, d={hole_d}, center=false);")
    lines.append(f"  translate([{w*0.75}, {h/2}, -1]) cylinder(h={t+2}, d={hole_d}, center=false);")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _linear_axis_tensioner(a: LinearAxisSpec) -> str:
    # Tensioner block with an M5 slot; bolts to idler mount (conceptual).
    w = 40.0
    h = 25.0
    t = max(10.0, a.wall_mm * 3.0)
    slot_w = 6.0
    slot_l = 20.0
    bolt_d = 5.2

    lines: list[str] = []
    lines.append(_header(f"linear_axis_tensioner name={a.name}"))
    lines.append("difference() {")
    lines.append(f"  cube([{w}, {h}, {t}], center=false);")
    lines.append(f"  translate([{w/2 - slot_l/2}, {h/2 - slot_w/2}, -1]) cube([{slot_l}, {slot_w}, {t+2}], center=false);")
    lines.append(f"  translate([{w/2}, {h/2}, -1]) cylinder(h={t+2}, d={bolt_d}, center=false);")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _linear_axis_endstop_mount(a: LinearAxisSpec) -> str:
    # Micro-switch mount plate with two M2 holes and a lever clearance slot.
    w = 30.0
    h = 20.0
    t = max(4.0, a.wall_mm * 2.0)
    hole_d = 2.2

    lines: list[str] = []
    lines.append(_header(f"linear_axis_endstop_mount name={a.name}"))
    lines.append("difference() {")
    lines.append(f"  cube([{w}, {h}, {t}], center=false);")
    lines.append(f"  translate([{w*0.35}, {h*0.5}, -1]) cylinder(h={t+2}, d={hole_d}, center=false);")
    lines.append(f"  translate([{w*0.65}, {h*0.5}, -1]) cylinder(h={t+2}, d={hole_d}, center=false);")
    lines.append(f"  translate([{w/2 - 8}, {h - 6}, {t/2 - 1}]) cube([16, 5, 2], center=false);")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _linear_axis_rod_holder(a: LinearAxisSpec) -> str:
    """
    Two-piece clamp block for holding a smooth rod to a frame/plate.
    This is intentionally simple and printable.
    """
    rod_d = a.rod_d_mm
    clear = a.clearance_mm
    od = rod_d + 10.0
    w = 24.0
    h = 18.0
    t = max(10.0, a.wall_mm * 3.0)
    slit = 1.5
    bolt_d = 3.2 if a.rod_holder_bolt == "m3" else 2.2
    nut_flat = 5.6 if a.rod_holder_bolt == "m3" else 4.0

    lines: list[str] = []
    lines.append(_header(f"linear_axis_rod_holder name={a.name}"))
    lines.append(f"rod_d = {rod_d};")
    lines.append(f"rod_clear = {rod_d + clear*2};")
    lines.append(f"od = {od};")
    lines.append(f"w = {w};")
    lines.append(f"h = {h};")
    lines.append(f"t = {t};")
    lines.append(f"slit = {slit};")
    lines.append(f"bolt_d = {bolt_d};")
    lines.append(f"nut_flat = {nut_flat};")
    lines.append("")

    # Base block with semi-circular bore and clamping slit.
    lines.append("difference() {")
    lines.append("  cube([w, od, t], center=false);")
    lines.append("  // rod bore")
    lines.append("  translate([w/2, od/2, -1]) cylinder(h=t+2, d=rod_clear, center=false);")
    lines.append("  // clamp slit")
    lines.append("  translate([w/2 - slit/2, 0, -1]) cube([slit, od, t+2], center=false);")
    lines.append("  // clamp bolt holes (2)")
    lines.append("  translate([w*0.25, od*0.25, -1]) cylinder(h=t+2, d=bolt_d, center=false);")
    lines.append("  translate([w*0.75, od*0.75, -1]) cylinder(h=t+2, d=bolt_d, center=false);")
    lines.append("  // hex nut pockets (underside)")
    lines.append("  translate([w*0.25, od*0.25, 0]) cylinder(h=4, d=nut_flat, $fn=6, center=false);")
    lines.append("  translate([w*0.75, od*0.75, 0]) cylinder(h=4, d=nut_flat, $fn=6, center=false);")
    lines.append("}")
    return "\n".join(lines) + "\n"
