#!/usr/bin/env python3
"""
Arduino Code Generator for Circuit-AI
Generates working Arduino code using templates scraped from tutorials
"""

import json
from pathlib import Path
from typing import List, Dict, Optional
from dataclasses import dataclass


@dataclass
class PinConnection:
    """Represents a pin connection"""
    component: str
    signal: str  # e.g., "DATA", "SCL", "TX"
    gpio_pin: str  # e.g., "4", "D1", "GPIO5"


@dataclass
class GeneratedCode:
    """Complete generated Arduino code"""
    code: str
    filename: str
    libraries_needed: List[str]
    upload_instructions: str
    notes: List[str]


class ArduinoCodeGenerator:
    """Generates working Arduino code from component selections"""

    def __init__(self, template_file: Path = None):
        if template_file is None:
            template_file = Path(__file__).parent.parent.parent / "data" / "code_cache" / "arduino_code_templates.json"

        self.template_file = template_file
        self.templates = self._load_templates()

    def _load_templates(self) -> Dict:
        """Load code templates from file"""
        if not self.template_file.exists():
            print(f"Warning: Template file not found: {self.template_file}")
            return {}

        with open(self.template_file, 'r') as f:
            templates = json.load(f)

        print(f"✓ Loaded {len(templates)} code templates")
        return templates

    def generate_for_project(
        self,
        microcontroller: str,
        components: List[str],
        connections: List[PinConnection],
        project_name: str = "circuit_ai_project",
        features: Optional[List[str]] = None
    ) -> GeneratedCode:
        """
        Generate complete Arduino code for a project

        Args:
            microcontroller: "ESP32", "ESP8266", "Arduino Uno", etc.
            components: List of components like ["DHT22", "OLED"]
            connections: Pin connections
            project_name: Name for the generated .ino file
            features: Optional features like ["wifi", "web_server"]

        Returns:
            GeneratedCode with complete .ino file
        """
        features = features or []

        # Build code sections
        includes = []
        defines = []
        globals = []
        setup_code = []
        loop_code = []
        all_libraries = []
        all_notes = []

        # Add WiFi if requested
        if "wifi" in features or "web_server" in features:
            wifi_template_key = f"{microcontroller}_WiFi"
            if wifi_template_key in self.templates:
                wifi_template = self.templates[wifi_template_key]
                includes.extend(wifi_template["common_includes"])
                defines.extend(wifi_template["common_defines"])
                setup_code.extend(wifi_template["setup_code"])
                all_libraries.extend(wifi_template["required_libraries"])
                all_notes.extend(wifi_template.get("notes", []))

        # Add web server if requested
        if "web_server" in features:
            if "AsyncWebServer" in self.templates:
                server_template = self.templates["AsyncWebServer"]
                includes.extend(server_template["common_includes"])
                globals.extend(server_template["globals"])
                setup_code.extend(server_template["setup_code"])
                all_libraries.extend(server_template["required_libraries"])
                all_notes.extend(server_template.get("notes", []))

        # Add each component
        for component in components:
            if component in self.templates:
                template = self.templates[component]

                # Add includes
                includes.extend(template["common_includes"])

                # Add defines with pin substitution
                for define in template["common_defines"]:
                    # Find matching pin connection
                    pin_value = self._find_pin_for_component(component, connections)
                    if pin_value:
                        define = define.replace("{pin}", str(pin_value))
                    defines.append(define)

                # Add globals
                globals.extend(template.get("globals", []))

                # Add setup code
                setup_code.extend(template["setup_code"])

                # Add loop code
                loop_code.extend(template.get("loop_code_simple", []))

                # Track libraries and notes
                all_libraries.extend(template["required_libraries"])
                all_notes.extend(template.get("notes", []))

        # Assemble final code
        code_lines = []

        # Header comment
        code_lines.append(f"/*")
        code_lines.append(f" * {project_name}")
        code_lines.append(f" * Generated by Circuit-AI")
        code_lines.append(f" * Microcontroller: {microcontroller}")
        code_lines.append(f" * Components: {', '.join(components)}")
        code_lines.append(f" */")
        code_lines.append("")

        # Includes
        if includes:
            code_lines.append("// Include required libraries")
            for inc in self._deduplicate(includes):
                code_lines.append(inc)
            code_lines.append("")

        # Defines
        if defines:
            code_lines.append("// Pin definitions and constants")
            for define in self._deduplicate(defines):
                code_lines.append(define)
            code_lines.append("")

        # Globals
        if globals:
            code_lines.append("// Global objects and variables")
            for global_var in self._deduplicate(globals):
                code_lines.append(global_var)
            code_lines.append("")

        # Setup function
        code_lines.append("void setup() {")
        if setup_code:
            for line in self._deduplicate(setup_code):
                if line.strip() and not line.strip().startswith('//'):
                    code_lines.append(f"  {line}")
                elif line.strip().startswith('//'):
                    code_lines.append(f"  {line}")
                else:
                    code_lines.append(line)
        else:
            code_lines.append("  // No setup code needed")
        code_lines.append("}")
        code_lines.append("")

        # Loop function
        code_lines.append("void loop() {")
        if loop_code:
            for line in self._deduplicate(loop_code):
                if line.strip() and not line.strip().startswith('//'):
                    code_lines.append(f"  {line}")
                elif line.strip().startswith('//'):
                    code_lines.append(f"  {line}")
                else:
                    code_lines.append(line)
        else:
            code_lines.append("  // Add your code here")
            code_lines.append("  delay(1000);")
        code_lines.append("}")

        final_code = "\n".join(code_lines)

        # Generate upload instructions
        upload_instructions = self._generate_upload_instructions(microcontroller, all_libraries)

        return GeneratedCode(
            code=final_code,
            filename=f"{project_name}.ino",
            libraries_needed=self._deduplicate(all_libraries),
            upload_instructions=upload_instructions,
            notes=self._deduplicate(all_notes)
        )

    def _find_pin_for_component(self, component: str, connections: List[PinConnection]) -> Optional[str]:
        """Find GPIO pin for a component from connections"""
        for conn in connections:
            if component.lower() in conn.component.lower():
                return conn.gpio_pin
        return None

    def _deduplicate(self, items: List[str]) -> List[str]:
        """Remove duplicates while preserving order"""
        seen = set()
        result = []
        for item in items:
            if item not in seen:
                seen.add(item)
                result.append(item)
        return result

    def _generate_upload_instructions(self, microcontroller: str, libraries: List[str]) -> str:
        """Generate upload instructions for Arduino IDE"""
        instructions = []

        instructions.append("=== Upload Instructions ===\n")

        # Library installation
        if libraries:
            instructions.append("1. Install Required Libraries:")
            instructions.append("   Open Arduino IDE → Tools → Manage Libraries")
            for lib in libraries:
                instructions.append(f"   • Search and install: {lib}")
            instructions.append("")

        # Board selection
        instructions.append("2. Select Board:")
        if "ESP32" in microcontroller:
            instructions.append("   Tools → Board → ESP32 Arduino → ESP32 Dev Module")
            instructions.append("   (Install ESP32 board support if needed)")
        elif "ESP8266" in microcontroller:
            instructions.append("   Tools → Board → ESP8266 Boards → NodeMCU 1.0")
            instructions.append("   (Install ESP8266 board support if needed)")
        else:
            instructions.append(f"   Tools → Board → {microcontroller}")
        instructions.append("")

        # Upload
        instructions.append("3. Connect & Upload:")
        instructions.append("   • Connect board via USB")
        instructions.append("   • Select correct COM port in Tools → Port")
        instructions.append("   • Click Upload button (→)")
        instructions.append("")

        instructions.append("4. Open Serial Monitor:")
        instructions.append("   • Tools → Serial Monitor")
        instructions.append("   • Set baud rate to 115200")

        return "\n".join(instructions)

    def save_code(self, generated: GeneratedCode, output_dir: Path = None):
        """Save generated code to file"""
        if output_dir is None:
            output_dir = Path("generated_code")

        output_dir.mkdir(parents=True, exist_ok=True)

        # Save .ino file
        code_file = output_dir / generated.filename
        with open(code_file, 'w') as f:
            f.write(generated.code)

        # Save instructions
        instructions_file = output_dir / f"{generated.filename.replace('.ino', '_INSTRUCTIONS.txt')}"
        with open(instructions_file, 'w') as f:
            f.write(generated.upload_instructions)
            f.write("\n\n=== Notes ===\n")
            for note in generated.notes:
                f.write(f"• {note}\n")

        print(f"✓ Saved code to: {code_file}")
        print(f"✓ Saved instructions to: {instructions_file}")

        return code_file


def demo():
    """Demo the Arduino Code Generator"""
    print("="*70)
    print("  ARDUINO CODE GENERATOR - Demo")
    print("="*70)
    print()

    generator = ArduinoCodeGenerator()

    # Example 1: Simple ESP32 + DHT22
    print("Example 1: ESP32 with DHT22 Temperature Sensor")
    print("-"*70)

    connections = [
        PinConnection(component="DHT22", signal="DATA", gpio_pin="4"),
    ]

    generated = generator.generate_for_project(
        microcontroller="ESP32",
        components=["DHT22"],
        connections=connections,
        project_name="esp32_temperature_sensor"
    )

    print("\nGenerated Code Preview:")
    print("="*70)
    print(generated.code)
    print("="*70)

    print(f"\nFilename: {generated.filename}")
    print(f"Libraries needed: {', '.join(generated.libraries_needed)}")
    print()

    # Save it
    code_file = generator.save_code(generated)

    print()
    print("="*70)
    print("  Example 2: ESP8266 DHT22 Web Server")
    print("="*70)
    print()

    connections2 = [
        PinConnection(component="DHT22", signal="DATA", gpio_pin="5"),
    ]

    generated2 = generator.generate_for_project(
        microcontroller="ESP8266",
        components=["DHT22"],
        connections=connections2,
        project_name="esp8266_temp_web_server",
        features=["wifi", "web_server"]
    )

    print("\nGenerated Code Preview (first 40 lines):")
    print("="*70)
    lines = generated2.code.split('\n')
    for line in lines[:40]:
        print(line)
    print("...")
    print("="*70)

    code_file2 = generator.save_code(generated2)

    print()
    print("="*70)
    print("✓ Arduino Code Generator Demo Complete!")
    print("="*70)
    print()
    print(f"Generated {2} working Arduino projects")
    print("Upload to your microcontroller and test!")
    print("="*70)


if __name__ == '__main__':
    demo()
