"""ESPHome YAML stub from graph pin map — pin-true, no flash claim."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional

from ..graph_pin_map import extract_pins_from_graph


def _gpio_line(pin_num: Any) -> Optional[str]:
    if pin_num is None:
        return None
    try:
        n = int(pin_num)
    except (TypeError, ValueError):
        return None
    return f"GPIO{n}"


def build_esphome_stub(
    *,
    build_id: str,
    build_graph: Mapping[str, Any] | None = None,
    pins: Mapping[str, Any] | None = None,
    project_name: str = "hardware_splicer",
) -> Dict[str, Any]:
    pin_map = dict(pins or {})
    if build_graph and not pin_map.get("sourced_from_graph"):
        pin_map = extract_pins_from_graph(build_graph)

    substitutions: List[str] = []
    gpio_blocks: List[str] = []

    mapping = [
        ("soil", "soil_moisture", "ADC"),
        ("pump", "pump_enable", "OUTPUT"),
        ("fan", "fan_enable", "OUTPUT"),
        ("relay", "relay", "OUTPUT"),
        ("dht", "dht_data", "INPUT"),
        ("servo_pan", "servo_pan", "OUTPUT"),
        ("servo_tilt", "servo_tilt", "OUTPUT"),
        ("in1", "motor_in1", "OUTPUT"),
        ("in2", "motor_in2", "OUTPUT"),
        ("in3", "motor_in3", "OUTPUT"),
        ("in4", "motor_in4", "OUTPUT"),
        ("step", "stepper_step", "OUTPUT"),
        ("dir", "stepper_dir", "OUTPUT"),
    ]
    used = 0
    for key, name, mode in mapping:
        gpio = _gpio_line(pin_map.get(key))
        if not gpio:
            continue
        used += 1
        substitutions.append(f"  pin_{name}: \"{gpio}\"")
        if mode == "ADC":
            gpio_blocks.append(
                f"""  - platform: adc
    pin: ${{pin_{name}}}
    name: "{name}"
    attenuation: 12db
    update_interval: 2s"""
            )
        else:
            gpio_blocks.append(
                f"""  - platform: gpio
    pin: ${{pin_{name}}}
    name: "{name}"
    id: {name}"""
            )

    yaml_lines = [
        f"# ESPHome stub for {build_id} — generated by Hardware-Splicer",
        "# Pin numbers match compiled build_graph when sourced_from_graph=true.",
        "# Not a flash-ready product firmware — verify board/variant before upload.",
        "",
        "substitutions:",
        f"  device_name: \"{project_name or build_id}\"",
    ]
    yaml_lines.extend(substitutions or ["  # no control pins extracted"])
    yaml_lines.extend(
        [
            "",
            "esphome:",
            "  name: ${device_name}",
            "",
            "esp32:",
            "  board: esp32dev",
            "  framework:",
            "    type: arduino",
            "",
            "logger:",
            "",
            "api:",
            "ota:",
            "",
        ]
    )
    if gpio_blocks:
        # Split sensors vs outputs heuristically
        sensors = [b for b in gpio_blocks if "platform: adc" in b or "dht" in b]
        switches = [b for b in gpio_blocks if b not in sensors]
        if sensors:
            yaml_lines.append("sensor:")
            for block in sensors:
                yaml_lines.append(block)
            yaml_lines.append("")
        if switches:
            yaml_lines.append("switch:")
            for block in switches:
                yaml_lines.append(block)
            yaml_lines.append("")
    else:
        yaml_lines.append("# No GPIO assignments extracted — see BRINGUP_CARD.md")
        yaml_lines.append("")

    body = "\n".join(yaml_lines)
    return {
        "schema_version": "hardware_splicer.esphome_stub.v1",
        "build_id": build_id,
        "filename": "esphome_stub.yaml",
        "source": body,
        "pin_count": used,
        "pins": pin_map,
        "sourced_from_graph": bool(pin_map.get("sourced_from_graph")),
        "claim_boundary": "YAML pin stub only — not authorized as flash/production firmware.",
    }


def write_esphome_stub(
    *,
    build_id: str,
    out_dir: str | Path,
    build_graph: Mapping[str, Any] | None = None,
    pins: Mapping[str, Any] | None = None,
    project_name: str = "hardware_splicer",
) -> Dict[str, Any]:
    payload = build_esphome_stub(
        build_id=build_id,
        build_graph=build_graph,
        pins=pins,
        project_name=project_name,
    )
    target = Path(out_dir)
    fw = target / "firmware"
    fw.mkdir(parents=True, exist_ok=True)
    yaml_path = fw / str(payload["filename"])
    yaml_path.write_text(str(payload["source"]), encoding="utf-8")
    meta_path = fw / "ESPHOME_STUB.json"
    meta_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return {
        "ok": True,
        "skipped": False,
        "id": "esphome",
        "path": str(yaml_path),
        "meta_path": str(meta_path),
        "pin_count": payload["pin_count"],
        "sourced_from_graph": payload["sourced_from_graph"],
    }
