"""Canonical OSS integration catalog for API + docs."""

from __future__ import annotations

from typing import Any, Dict, List

OSS_CATALOG: List[Dict[str, Any]] = [
    {
        "id": "kicanvas",
        "layer": "viewer",
        "name": "KiCanvas",
        "url": "https://github.com/theacodes/kicanvas",
        "license": "MIT",
        "status": "wired",
        "priority": "P0",
        "hook": "splice-ui Design tab + POST /v1/build-files/content",
        "claim": "In-browser KiCad schematic/PCB preview without KiCad install",
    },
    {
        "id": "circuit-json",
        "layer": "interchange",
        "name": "circuit-json / tscircuit",
        "url": "https://github.com/tscircuit/circuit-json",
        "license": "MIT",
        "status": "wired",
        "priority": "P0",
        "hook": "circuit_json_import.py + POST /v1/netlist-compile + artifact export",
        "claim": "Web-native circuit interchange into the compile spine",
    },
    {
        "id": "compose-canvas",
        "layer": "editor",
        "name": "Canvas compose API",
        "url": "https://github.com/Spectating101/hardware-splicer",
        "license": "Apache-2.0",
        "status": "wired",
        "priority": "P0",
        "hook": "POST /v1/compose-canvas + Interface lab",
        "claim": "Module graph editor input on the same engine as Circuit.AI",
    },
    {
        "id": "kicad-cli",
        "layer": "truth",
        "name": "KiCad 9 CLI",
        "url": "https://www.kicad.org/",
        "license": "GPL-3.0",
        "status": "core",
        "priority": "core",
        "hook": "kicad_cli_drc.py, ERC, Gerber export in build_compilation/",
        "claim": "Authoritative DRC/ERC/fab export — never replaced",
    },
    {
        "id": "freerouting",
        "layer": "autoroute",
        "name": "FreeRouting",
        "url": "https://github.com/freerouting/freerouting",
        "license": "GPL-3.0",
        "status": "opt_in",
        "priority": "P1",
        "hook": "freerouting_bridge.py + POST /v1/build-files/autoroute (engine=freerouting)",
        "claim": "Optional carrier autoroute — never default-on in product copy",
    },
    {
        "id": "tscircuit-autorouter",
        "layer": "autoroute",
        "name": "tscircuit capacity-autorouter",
        "url": "https://github.com/tscircuit/tscircuit-autorouter",
        "license": "MIT",
        "status": "opt_in",
        "priority": "P1",
        "hook": "tscircuit_autorouter_bridge.py + POST /v1/build-files/autoroute engine=tscircuit",
        "claim": "Optional MIT autoroute from circuit-json — skips when Node package absent",
    },
    {
        "id": "kicad-mcp",
        "layer": "sidecar",
        "name": "KiCad MCP servers",
        "url": "https://github.com/mixelpixx/KiCAD-MCP-Server",
        "license": "varies",
        "status": "partial",
        "priority": "P1",
        "hook": "scripts/kicad_mcp_dev_profile.sh + POST /v1/build-files/recheck",
        "claim": "Human KiCad edit → DRC/ERC recheck + package refresh (MCP optional)",
    },
    {
        "id": "kibot",
        "layer": "artifacts",
        "name": "KiBot",
        "url": "https://github.com/INTI-CMNB/KiBot",
        "license": "GPL-3.0",
        "status": "reference",
        "priority": "P1",
        "hook": "kibot_reference.py + POST /v1/build-files/fab-manifest",
        "claim": "Fab artifact coverage vs KiBot reference — compare, not vendored",
    },
    {
        "id": "ibom",
        "layer": "artifacts",
        "name": "InteractiveHtmlBom",
        "url": "https://github.com/openscopeproject/InteractiveHtmlBom",
        "license": "MIT",
        "status": "wired",
        "priority": "P1",
        "hook": "ibom_bridge.py + package oss_export_bundle / export-views",
        "claim": "Best-effort interactive HTML BOM when CLI installed — never hard-fails compile",
    },
    {
        "id": "pcbdraw",
        "layer": "artifacts",
        "name": "PcbDraw",
        "url": "https://github.com/yaqwsx/PcbDraw",
        "license": "MIT",
        "status": "wired",
        "priority": "P1",
        "hook": "pcbdraw_bridge.py + package oss_export_bundle / export-views",
        "claim": "Best-effort board SVG for bring-up docs when pcbdraw on PATH",
    },
    {
        "id": "kikit",
        "layer": "fab",
        "name": "KiKit",
        "url": "https://github.com/yaqwsx/KiKit",
        "license": "MIT",
        "status": "opt_in",
        "priority": "P1",
        "hook": "kikit_bridge.py + POST /v1/build-files/kikit-fab",
        "claim": "Opt-in manufacturer fab preset export — skips when kikit absent",
    },
    {
        "id": "jlc-api",
        "layer": "supply",
        "name": "JLCPCB / LCSC API",
        "url": "https://github.com/i2cjak/jlcpcb_api",
        "license": "MIT",
        "status": "partial",
        "priority": "P1",
        "hook": "jlcsearch_client.py + HARDWARE_SPLICER_JLC_ENRICH (CPL-shaped fields)",
        "claim": "Opt-in BOM stock/price enrich + designator/footprint CPL shape",
    },
    {
        "id": "easyeda2kicad",
        "layer": "supply",
        "name": "easyeda2kicad",
        "url": "https://github.com/uPesy/easyeda2kicad.py",
        "license": "MIT",
        "status": "opt_in",
        "priority": "P1",
        "hook": "easyeda2kicad_bridge.py + POST /v1/build-files/lcsc-lib",
        "claim": "Opt-in LCSC→KiCad symbol/footprint/3D into exports/lcsc_lib/",
    },
    {
        "id": "esphome",
        "layer": "firmware",
        "name": "ESPHome export",
        "url": "https://github.com/esphome/esphome",
        "license": "GPL-3.0",
        "status": "wired",
        "priority": "P2",
        "hook": "esphome_export.py → firmware/esphome_stub.yaml from graph pins",
        "claim": "Pin-true YAML stub only — not flash/production authorization",
    },
    {
        "id": "nopscadlib",
        "layer": "mech",
        "name": "NopSCADlib",
        "url": "https://github.com/nophead/NopSCADlib",
        "license": "GPL-3.0",
        "status": "reference",
        "priority": "P2",
        "hook": "MECHANISM_PACK.oss_mech_refs — vitamins/manual pattern reference",
        "claim": "Referenced for mecha pack depth — not vendored this pass",
    },
    {
        "id": "build123d",
        "layer": "mech",
        "name": "build123d",
        "url": "https://github.com/gumyr/build123d",
        "license": "Apache-2.0",
        "status": "reference",
        "priority": "P2",
        "hook": "MECHANISM_PACK.oss_mech_refs — optional parametric CAD",
        "claim": "Optional CAD backend reference — no hard STL dep",
    },
    {
        "id": "skidl",
        "layer": "code-capture",
        "name": "SKiDL",
        "url": "https://github.com/devbisme/skidl",
        "license": "MIT",
        "status": "wired",
        "priority": "P2",
        "hook": "KiCad netlist ingest via POST /v1/netlist-compile (kicad_netlist_text)",
        "claim": "Python netlist → compile spine (import path, not UI editor)",
    },
    {
        "id": "atopile",
        "layer": "code-capture",
        "name": "atopile",
        "url": "https://github.com/atopile/atopile",
        "license": "MIT",
        "status": "partial",
        "priority": "P2",
        "hook": "KiCad netlist export → kicad_netlist_text + docs/ATOPILE_IMPORT.md",
        "claim": "Code-defined boards via KiCad netlist export into compile spine",
    },
    {
        "id": "schematic-ai",
        "layer": "intake",
        "name": "Schematic AI (SINA / pcbGPT)",
        "url": "https://arxiv.org/abs/2607.01609",
        "license": "research",
        "status": "planned",
        "priority": "P3",
        "hook": "Intake adapter → netlist-compile + gates",
        "claim": "Image/NL schematic draft intake — not product UI yet",
    },
]


def integration_catalog() -> Dict[str, Any]:
    wired = [row for row in OSS_CATALOG if row["status"] in {"wired", "core", "opt_in", "partial"}]
    return {
        "ok": True,
        "schema_version": "hardware_splicer.oss_catalog.v1",
        "thesis": "Engine is under-interfaced, not under-powered — embed OSS layers, own gates/package truth.",
        "integrations": OSS_CATALOG,
        "wired_count": len(wired),
        "total_count": len(OSS_CATALOG),
    }
