"""Canonical external-capability catalog for API, UI, and product claims.

The catalog is intentionally outcome-oriented.  A project appearing here does not
mean that Hardware Splicer vendors or automatically executes it.  Each row states
what is available today, what the operator receives, and the maximum authority the
external result can acquire inside Hardware Splicer.
"""

from __future__ import annotations

from typing import Any, Dict, List


OSS_CATALOG: List[Dict[str, Any]] = [
    {
        "id": "kicanvas",
        "layer": "inspect",
        "name": "KiCanvas",
        "url": "https://github.com/theacodes/kicanvas",
        "license": "MIT",
        "status": "wired",
        "priority": "P0",
        "hook": "Design tab + POST /v1/build-files/content",
        "claim": "Inspect generated KiCad schematics and boards in the browser without installing KiCad.",
        "user_value": "Reviewers can open the design immediately.",
        "delivery": "embedded_viewer",
        "authority_ceiling": "observed",
        "runtime": "browser",
    },
    {
        "id": "kicad-cli",
        "layer": "verify",
        "name": "KiCad CLI",
        "url": "https://www.kicad.org/",
        "license": "GPL-3.0",
        "status": "core",
        "priority": "core",
        "hook": "ERC, DRC, PDF/SVG, Gerber and drill exports",
        "claim": "Run authoritative KiCad checks and produce fabrication artifacts from the same build.",
        "user_value": "A design handoff includes machine-generated checks, not only screenshots.",
        "delivery": "core_runtime",
        "authority_ceiling": "verified",
        "runtime": "local_cli",
    },
    {
        "id": "circuit-json",
        "layer": "interchange",
        "name": "Circuit JSON / tscircuit",
        "url": "https://github.com/tscircuit/circuit-json",
        "license": "MIT",
        "status": "partial",
        "priority": "P0",
        "hook": "circuit_json_import.py + netlist compile + artifact export",
        "claim": "Exchange a supported electrical subset with web-native circuit tools and agent pipelines.",
        "user_value": "External editors and renderers can feed the compile spine without becoming project authority.",
        "delivery": "subset_adapter",
        "authority_ceiling": "proposed",
        "runtime": "in_process",
        "limitations": [
            "Current importer covers a constrained source-component and schematic-trace subset.",
            "Full upstream PCB, CAD, warning and simulation interoperability is not claimed yet.",
        ],
    },
    {
        "id": "kicad-happy",
        "layer": "review",
        "name": "kicad-happy",
        "url": "https://github.com/aklofas/kicad-happy",
        "license": "MIT",
        "status": "planned",
        "priority": "P0",
        "hook": "Issue #15 read-only evidence adapter",
        "claim": "Add deterministic schematic, PCB and Gerber review findings with confidence and provenance.",
        "user_value": "The release packet can explain power, protection, thermal, EMC, BOM and DFM risks.",
        "delivery": "external_read_only_adapter",
        "authority_ceiling": "observed",
        "runtime": "bounded_subprocess",
    },
    {
        "id": "build123d-agentcad",
        "layer": "mechanical",
        "name": "build123d / agentcad",
        "url": "https://github.com/jdilla1277/agentcad",
        "license": "Apache-2.0",
        "status": "planned",
        "priority": "P0",
        "hook": "STEP-first mechanical adapter after isolated CAD worker",
        "claim": "Generate measurable STEP geometry, previews, spec checks and revision-to-revision diffs.",
        "user_value": "Enclosures and fixtures become inspectable engineering artifacts rather than opaque STL files.",
        "delivery": "external_cad_adapter",
        "authority_ceiling": "proposed",
        "runtime": "isolated_worker",
    },
    {
        "id": "cad-skills",
        "layer": "mechanical",
        "name": "CAD Skills",
        "url": "https://github.com/earthtojake/text-to-cad",
        "license": "MIT",
        "status": "documented",
        "priority": "P1",
        "hook": "Codex/Claude skill sidecar; STEP, STL, GLB, DXF and fabrication handoff",
        "claim": "Give coding agents a repeatable CAD, preview, slicing and fabrication workflow.",
        "user_value": "Operators can continue a Hardware Splicer project in their preferred coding agent.",
        "delivery": "agent_skill_sidecar",
        "authority_ceiling": "proposed",
        "runtime": "operator_agent",
    },
    {
        "id": "atopile",
        "layer": "electrical-authoring",
        "name": "atopile",
        "url": "https://github.com/atopile/atopile",
        "license": "MIT",
        "status": "partial",
        "priority": "P1",
        "hook": "KiCad netlist export → netlist compile + ATOPILE_IMPORT.md",
        "claim": "Accept code-defined electronics from a constraint-oriented electrical compiler.",
        "user_value": "Advanced users can author reusable circuits without Hardware Splicer rebuilding an ECAD language.",
        "delivery": "file_interchange",
        "authority_ceiling": "proposed",
        "runtime": "external_cli",
    },
    {
        "id": "konnect",
        "layer": "live-edit",
        "name": "Konnect",
        "url": "https://github.com/mixelpixx/Konnect",
        "license": "AGPL-3.0 / commercial",
        "status": "documented",
        "priority": "P2",
        "hook": "User-installed KiCad 10 MCP sidecar; save then recheck in Hardware Splicer",
        "claim": "Optionally let an AI assistant modify an open KiCad session through the official IPC API.",
        "user_value": "A human can supervise live edits and return the result to the evidence and release workflow.",
        "delivery": "licensed_sidecar",
        "authority_ceiling": "proposed",
        "runtime": "external_mcp",
        "limitations": ["Not vendored because of the AGPL/commercial license boundary."],
    },
    {
        "id": "freerouting",
        "layer": "route",
        "name": "FreeRouting",
        "url": "https://github.com/freerouting/freerouting",
        "license": "GPL-3.0",
        "status": "opt_in",
        "priority": "P1",
        "hook": "POST /v1/build-files/autoroute with explicit confirmation",
        "claim": "Run an optional carrier-board autoroute and return the result for review and DRC.",
        "user_value": "Simple boards can reach a reviewable routed proposal faster.",
        "delivery": "confirmed_subprocess",
        "authority_ceiling": "proposed",
        "runtime": "external_cli",
    },
    {
        "id": "tscircuit-autorouter",
        "layer": "route",
        "name": "tscircuit capacity autorouter",
        "url": "https://github.com/tscircuit/tscircuit-autorouter",
        "license": "MIT",
        "status": "opt_in",
        "priority": "P1",
        "hook": "POST /v1/build-files/autoroute engine=tscircuit",
        "claim": "Route supported Circuit JSON boards when the optional Node package is installed.",
        "user_value": "A permissively licensed routing option remains available for compatible projects.",
        "delivery": "confirmed_subprocess",
        "authority_ceiling": "proposed",
        "runtime": "external_cli",
    },
    {
        "id": "ibom-pcbdraw",
        "layer": "communicate",
        "name": "InteractiveHtmlBom / PcbDraw",
        "url": "https://github.com/openscopeproject/InteractiveHtmlBom",
        "license": "MIT",
        "status": "wired",
        "priority": "P1",
        "hook": "oss_export_bundle + export views",
        "claim": "Produce assembly-friendly HTML BOM and board drawings when the optional CLIs are installed.",
        "user_value": "Builders receive visual placement and assembly references rather than raw CAD alone.",
        "delivery": "best_effort_export",
        "authority_ceiling": "observed",
        "runtime": "external_cli",
    },
    {
        "id": "kikit",
        "layer": "manufacture",
        "name": "KiKit",
        "url": "https://github.com/yaqwsx/KiKit",
        "license": "MIT",
        "status": "opt_in",
        "priority": "P1",
        "hook": "POST /v1/build-files/kikit-fab with explicit confirmation",
        "claim": "Generate manufacturer-oriented fabrication outputs without making the optional tool a compile dependency.",
        "user_value": "The same reviewed project can be repackaged for a selected fabrication workflow.",
        "delivery": "confirmed_subprocess",
        "authority_ceiling": "observed",
        "runtime": "external_cli",
    },
    {
        "id": "jlc-lcsc",
        "layer": "source",
        "name": "JLCPCB / LCSC tooling",
        "url": "https://github.com/i2cjak/jlcpcb_api",
        "license": "MIT",
        "status": "partial",
        "priority": "P1",
        "hook": "BOM enrichment + easyeda2kicad opt-in library import",
        "claim": "Add optional stock, pricing and library hints while retaining the original BOM evidence.",
        "user_value": "A reviewer can see whether a design is plausibly sourceable before handoff.",
        "delivery": "optional_enrichment",
        "authority_ceiling": "observed",
        "runtime": "external_api_or_cli",
    },
    {
        "id": "partcad",
        "layer": "product-package",
        "name": "PartCAD",
        "url": "https://github.com/partcad/partcad",
        "license": "Apache-2.0",
        "status": "reference",
        "priority": "P3",
        "hook": "Future package/assembly interchange after identity mapping",
        "claim": "Exchange broader part, assembly and manufacturing-package information after revision ownership is defined.",
        "user_value": "Hardware Splicer projects can eventually participate in a larger product lifecycle toolchain.",
        "delivery": "future_interchange",
        "authority_ceiling": "proposed",
        "runtime": "external_cli",
    },
    {
        "id": "esphome",
        "layer": "firmware",
        "name": "ESPHome export",
        "url": "https://github.com/esphome/esphome",
        "license": "GPL-3.0",
        "status": "wired",
        "priority": "P2",
        "hook": "firmware/esphome_stub.yaml from graph pins",
        "claim": "Emit a pin-aligned firmware starting point from the reviewed hardware graph.",
        "user_value": "Firmware bring-up begins with the same pin assignments as the hardware package.",
        "delivery": "generated_stub",
        "authority_ceiling": "proposed",
        "runtime": "in_process",
    },
]


CAPABILITY_WORKFLOWS: List[Dict[str, Any]] = [
    {
        "id": "reviewable-board",
        "title": "Reviewable board package",
        "promise": "Turn an electrical proposal into files a second person can inspect and challenge.",
        "steps": ["compose_or_import", "kicad_compile", "erc_drc", "browser_preview", "bom_and_views"],
        "integrations": ["circuit-json", "atopile", "kicad-cli", "kicanvas", "ibom-pcbdraw"],
        "deliverables": ["KiCad project", "DRC/ERC evidence", "BOM", "browser preview", "human-readable views"],
        "release_state": "available",
    },
    {
        "id": "engineering-review",
        "title": "Engineering review packet",
        "promise": "Explain why the design may fail before fabrication, with traceable findings.",
        "steps": ["compile", "deterministic_analysis", "finding_mapping", "human_disposition"],
        "integrations": ["kicad-cli", "kicad-happy"],
        "deliverables": ["structured findings", "confidence and provenance", "review dispositions", "casefile"],
        "release_state": "adapter_planned",
    },
    {
        "id": "mechanical-handoff",
        "title": "Mechanical fit and enclosure handoff",
        "promise": "Produce measurable geometry and visual revision evidence from board constraints.",
        "steps": ["board_geometry", "cad_proposal", "measure", "preview", "human_review"],
        "integrations": ["build123d-agentcad", "cad-skills"],
        "deliverables": ["STEP", "STL/GLB derivatives", "dimension report", "geometry diff"],
        "release_state": "worker_foundation_in_progress",
    },
    {
        "id": "fabrication-handoff",
        "title": "Fabrication and assembly handoff",
        "promise": "Package reviewed design outputs for sourcing, fabrication and bench work.",
        "steps": ["release_review", "fab_export", "sourcing_enrichment", "assembly_views", "package"],
        "integrations": ["kicad-cli", "kikit", "jlc-lcsc", "ibom-pcbdraw"],
        "deliverables": ["Gerbers and drills", "BOM/CPL", "assembly views", "PROJECT_PACKAGE"],
        "release_state": "partial",
    },
]


STATUS_WEIGHTS = {
    "core": 1.0,
    "wired": 1.0,
    "opt_in": 0.8,
    "partial": 0.5,
    "documented": 0.25,
    "reference": 0.1,
    "planned": 0.0,
}


def integration_catalog() -> Dict[str, Any]:
    active = [row for row in OSS_CATALOG if row["status"] in {"wired", "core", "opt_in", "partial"}]
    outcome_score = round(
        100 * sum(STATUS_WEIGHTS[row["status"]] for row in OSS_CATALOG) / max(len(OSS_CATALOG), 1)
    )
    layers: Dict[str, int] = {}
    for row in OSS_CATALOG:
        layers[row["layer"]] = layers.get(row["layer"], 0) + 1
    return {
        "ok": True,
        "schema_version": "hardware_splicer.oss_catalog.v2",
        "thesis": (
            "Use specialist OSS engines for authoring, analysis, rendering and export; "
            "Hardware Splicer owns project identity, evidence, review and release authority."
        ),
        "integrations": OSS_CATALOG,
        "workflows": CAPABILITY_WORKFLOWS,
        "wired_count": len(active),
        "total_count": len(OSS_CATALOG),
        "outcome_readiness_score": outcome_score,
        "layer_counts": layers,
        "status_legend": {
            "core": "required product runtime",
            "wired": "callable in the product today",
            "opt_in": "callable after explicit operator confirmation",
            "partial": "bounded subset or optional enrichment",
            "documented": "supported sidecar workflow; not product-executed",
            "reference": "architecture/interchange reference only",
            "planned": "accepted design direction; adapter not implemented",
        },
    }
