"""Canonical OSS integration catalog for API + docs."""

from __future__ import annotations

from typing import Any, Dict, List

OSS_CATALOG: List[Dict[str, Any]] = [
    {
        "id": "kicanvas",
        "layer": "viewer",
        "name": "KiCanvas",
        "url": "https://github.com/theacodes/kicanvas",
        "license": "MIT",
        "status": "wired",
        "priority": "P0",
        "hook": "splice-ui Design tab + POST /v1/build-files/content",
        "claim": "In-browser KiCad schematic/PCB preview without KiCad install",
    },
    {
        "id": "circuit-json",
        "layer": "interchange",
        "name": "circuit-json / tscircuit",
        "url": "https://github.com/tscircuit/circuit-json",
        "license": "MIT",
        "status": "wired",
        "priority": "P0",
        "hook": "circuit_json_import.py + POST /v1/netlist-compile + artifact export",
        "claim": "Web-native circuit interchange into the compile spine",
    },
    {
        "id": "compose-canvas",
        "layer": "editor",
        "name": "Canvas compose API",
        "url": "https://github.com/Spectating101/hardware-splicer",
        "license": "Apache-2.0",
        "status": "wired",
        "priority": "P0",
        "hook": "POST /v1/compose-canvas + Interface lab",
        "claim": "Module graph editor input on the same engine as Circuit.AI",
    },
    {
        "id": "kicad-cli",
        "layer": "truth",
        "name": "KiCad 9 CLI",
        "url": "https://www.kicad.org/",
        "license": "GPL-3.0",
        "status": "core",
        "priority": "core",
        "hook": "kicad_cli_drc.py, ERC, Gerber export in build_compilation/",
        "claim": "Authoritative DRC/ERC/fab export — never replaced",
    },
    {
        "id": "freerouting",
        "layer": "autoroute",
        "name": "FreeRouting",
        "url": "https://github.com/freerouting/freerouting",
        "license": "GPL-3.0",
        "status": "opt_in",
        "priority": "P1",
        "hook": "freerouting_bridge.py + POST /v1/build-files/autoroute",
        "claim": "Optional carrier autoroute — never default-on in product copy",
    },
    {
        "id": "kicad-mcp",
        "layer": "sidecar",
        "name": "KiCad MCP servers",
        "url": "https://github.com/mixelpixx/KiCAD-MCP-Server",
        "license": "varies",
        "status": "documented",
        "priority": "P1",
        "hook": "docs/KICAD_MCP_SIDECAR.md — human edits in KiCad, HS re-compiles",
        "claim": "Live KiCad session sidecar; not a hard runtime dependency",
    },
    {
        "id": "kibot",
        "layer": "artifacts",
        "name": "KiBot",
        "url": "https://github.com/INTI-CMNB/KiBot",
        "license": "GPL-3.0",
        "status": "reference",
        "priority": "P1",
        "hook": "kibot_reference.py + POST /v1/build-files/fab-manifest",
        "claim": "Fab artifact coverage vs KiBot reference — compare, not vendored",
    },
    {
        "id": "jlc-api",
        "layer": "supply",
        "name": "JLCPCB / LCSC API",
        "url": "https://github.com/i2cjak/jlcpcb_api",
        "license": "MIT",
        "status": "partial",
        "priority": "P1",
        "hook": "jlcsearch_client.py + HARDWARE_SPLICER_JLC_ENRICH",
        "claim": "Opt-in BOM stock/price enrich on salvage BOM",
    },
    {
        "id": "skidl",
        "layer": "code-capture",
        "name": "SKiDL",
        "url": "https://github.com/devbisme/skidl",
        "license": "MIT",
        "status": "wired",
        "priority": "P2",
        "hook": "KiCad netlist ingest via POST /v1/netlist-compile (kicad_netlist_text)",
        "claim": "Python netlist → compile spine (import path, not UI editor)",
    },
    {
        "id": "atopile",
        "layer": "code-capture",
        "name": "atopile",
        "url": "https://github.com/atopile/atopile",
        "license": "MIT",
        "status": "partial",
        "priority": "P2",
        "hook": "KiCad netlist export → kicad_netlist_text + docs/ATOPILE_IMPORT.md",
        "claim": "Code-defined boards via KiCad netlist export into compile spine",
    },
    {
        "id": "schematic-ai",
        "layer": "intake",
        "name": "Schematic AI (SINA / pcbGPT)",
        "url": "https://arxiv.org/abs/2607.01609",
        "license": "research",
        "status": "planned",
        "priority": "P3",
        "hook": "Intake adapter → netlist-compile + gates",
        "claim": "Image/NL schematic draft intake — not product UI yet",
    },
]


def integration_catalog() -> Dict[str, Any]:
    wired = [row for row in OSS_CATALOG if row["status"] in {"wired", "core", "opt_in", "partial"}]
    return {
        "ok": True,
        "schema_version": "hardware_splicer.oss_catalog.v1",
        "thesis": "Engine is under-interfaced, not under-powered — embed OSS layers, own gates/package truth.",
        "integrations": OSS_CATALOG,
        "wired_count": len(wired),
        "total_count": len(OSS_CATALOG),
    }
