from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Mapping

from .base import BackendResult, BackendStatus, executable_version, run_command_backend


MANIFEST_SCHEMA = "hardware_splicer.firmware_manifest.v1"


def _pin_defines(bindings: Mapping[str, Any]) -> str:
    lines = ["#pragma once", "", "// Generated by Hardware Splicer from verified interface contracts."]
    for name, raw in sorted(bindings.items()):
        if isinstance(raw, Mapping):
            value = raw.get("gpio")
        else:
            value = raw
        if value is None:
            continue
        macro = "HS_PIN_" + "".join(c if c.isalnum() else "_" for c in str(name).upper())
        lines.append(f"#define {macro} {int(value)}")
    lines.append("")
    return "\n".join(lines)


def write_platformio_project(
    manifest: Mapping[str, Any],
    out_dir: str | Path,
) -> BackendResult:
    target = manifest.get("target") or {}
    interfaces = manifest.get("interfaces") or {}
    if not bool(manifest.get("firmware_authorized")):
        return BackendResult(
            backend="platformio",
            status=BackendStatus.BLOCKED,
            diagnostics=["firmware_authorized is false; interface evidence is incomplete"],
        )
    board = str(target.get("board") or "").strip()
    platform = str(target.get("platform") or "").strip()
    framework = str(target.get("framework") or "arduino").strip()
    if not board or not platform:
        return BackendResult(
            backend="platformio",
            status=BackendStatus.BLOCKED,
            diagnostics=["target.platform and target.board are required"],
        )

    root = Path(out_dir)
    src = root / "src"
    include = root / "include"
    src.mkdir(parents=True, exist_ok=True)
    include.mkdir(parents=True, exist_ok=True)

    bindings: Dict[str, Any] = {}
    for interface in interfaces.values() if isinstance(interfaces, Mapping) else []:
        if not isinstance(interface, Mapping):
            continue
        for name, binding in (interface.get("bindings") or {}).items():
            bindings[str(name)] = binding

    (root / "platformio.ini").write_text(
        "\n".join(
            [
                f"[env:{board}]",
                f"platform = {platform}",
                f"board = {board}",
                f"framework = {framework}",
                "monitor_speed = 115200",
                "",
            ]
        ),
        encoding="utf-8",
    )
    (include / "generated_interfaces.h").write_text(_pin_defines(bindings), encoding="utf-8")
    (src / "main.cpp").write_text(
        "\n".join(
            [
                "#include <Arduino.h>",
                '#include "generated_interfaces.h"',
                "",
                "void setup() {",
                "  Serial.begin(115200);",
                '  Serial.println("Hardware Splicer verified firmware scaffold");',
                "}",
                "",
                "void loop() {",
                "  delay(1000);",
                "}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    manifest_path = root / "hardware_splicer_firmware_manifest.json"
    manifest_path.write_text(json.dumps(dict(manifest), indent=2), encoding="utf-8")
    return BackendResult(
        backend="platformio",
        status=BackendStatus.SUCCESS,
        inputs=[str(manifest_path)],
        outputs=[
            str(root / "platformio.ini"),
            str(include / "generated_interfaces.h"),
            str(src / "main.cpp"),
        ],
        version=executable_version("platformio"),
    )


def run_platformio_build(project_dir: str | Path) -> BackendResult:
    root = Path(project_dir)
    return run_command_backend(
        backend="platformio",
        command=["platformio", "run"],
        cwd=root,
        inputs=[str(root / "platformio.ini")],
        expected_outputs=[".pio"],
        version=executable_version("platformio"),
    )
