import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  Activity,
  ArrowRight,
  BadgeCheck,
  Boxes,
  CircuitBoard,
  Gauge,
  Hammer,
  PackageCheck,
  Play,
  Ruler,
  ShieldCheck,
  Wrench,
  Zap,
} from 'lucide-react';
import { demoProjects } from './sample-data.js';
import './styles.css';

const levelLabels = {
  control_safety_project_package: 'Control-safety package',
  simulation_bench_project_package: 'Simulation/bench package',
  field_validated_project_package: 'Field-validated package',
  production_ready_project_package: 'Production-ready package',
};

const iconMap = {
  circuit: CircuitBoard,
  mechanical: Hammer,
  robotics_actuation: Wrench,
  robotics_simulation: Activity,
  robotics_platform: Gauge,
  mechatronics: Boxes,
};

function App() {
  const [selectedId, setSelectedId] = useState(demoProjects[0].id);
  const [runCount, setRunCount] = useState(0);
  const selected = useMemo(() => demoProjects.find((project) => project.id === selectedId) || demoProjects[0], [selectedId]);

  return (
    <main className="app-shell">
      <aside className="sidebar">
        <div className="brand">
          <div className="brand-mark"><PackageCheck size={20} /></div>
          <div>
            <strong>Hardware-Splicer</strong>
            <span>authority workbench</span>
          </div>
        </div>

        <div className="project-list">
          {demoProjects.map((project) => (
            <button
              className={`project-button ${project.id === selected.id ? 'active' : ''}`}
              key={project.id}
              onClick={() => setSelectedId(project.id)}
            >
              <span>{project.name}</span>
              <small>{project.archetype}</small>
            </button>
          ))}
        </div>

        <div className="sidebar-note">
          <ShieldCheck size={18} />
          <span>Demo data is generated by the backend intake runner, not hand-entered UI state.</span>
        </div>
      </aside>

      <section className="workspace">
        <header className="topbar">
          <div>
            <h1>Hardware-Splicer Authority</h1>
            <p>{selected.goal}</p>
          </div>
          <div className="topbar-actions">
            <span className="status-chip">{runCount ? `demo run ${runCount}` : selected.claimable ? 'claimable package' : 'blocked package'}</span>
            <button className="primary-action" onClick={() => setRunCount((count) => count + 1)}><Play size={16} /> Run intake</button>
          </div>
        </header>

        <section className="pipeline" aria-label="Hardware-Splicer pipeline">
          {['User brief', 'Planned scenario', 'Compile bundle', 'Authority packet'].map((step, index) => (
            <React.Fragment key={step}>
              <div className="pipeline-step">
                <span>{index + 1}</span>
                <strong>{step}</strong>
              </div>
              {index < 3 && <ArrowRight className="pipeline-arrow" size={18} />}
            </React.Fragment>
          ))}
        </section>

        <section className="hero-grid">
          <AuthorityCard project={selected} />
          <MarginsCard project={selected} />
          <UpgradePanel project={selected} />
        </section>

        <section className="subsystems">
          {selected.subsystems.map((subsystem) => (
            <SubsystemCard key={subsystem.id} subsystem={subsystem} />
          ))}
        </section>

        <section className="lower-grid">
          <EvidencePanel project={selected} />
          <ArtifactTable project={selected} />
        </section>
      </section>
    </main>
  );
}

function AuthorityCard({ project }) {
  const score = Math.round(project.authorityScore * 100);
  return (
    <article className="panel authority-panel">
      <div className="panel-label"><BadgeCheck size={16} /> Project authority</div>
      <div className="score-row">
        <div className="score-ring" style={{ '--score': `${score}%` }}>
          <span>{score}</span>
        </div>
        <div>
          <h2>{levelLabels[project.level] || project.level}</h2>
          <p>{project.claimBoundary}</p>
        </div>
      </div>
      <div className="metric-strip">
        <Metric label="Planning" value={`${Math.round(project.planningConfidence * 100)}%`} />
        <Metric label="Simulation" value={project.simulationReady ? 'ready' : 'blocked'} tone={project.simulationReady ? 'good' : 'warn'} />
        <Metric label="Release" value={project.releaseReady ? 'ready' : 'open'} tone={project.releaseReady ? 'good' : 'warn'} />
      </div>
    </article>
  );
}

function MarginsCard({ project }) {
  return (
    <article className="panel margins-panel">
      <div className="panel-label"><Zap size={16} /> Deterministic margins</div>
      <div className="margin-list">
        {project.margins.map((item) => (
          <div className="margin-row" key={item.label}>
            <div>
              <strong>{item.value}</strong>
              <span>{item.label}</span>
            </div>
            <div className="bar"><span style={{ width: item.width }} /></div>
          </div>
        ))}
      </div>
    </article>
  );
}

function UpgradePanel({ project }) {
  return (
    <article className="panel upgrade-panel">
      <div className="panel-label"><Ruler size={16} /> Upgrade plan</div>
      <h2>{levelLabels[project.nextLevel] || project.nextLevel}</h2>
      <div className="evidence-list">
        {project.evidenceRequests.map((request) => (
          <div className="evidence-item" key={request.id}>
            <span>{request.label}</span>
            <small>{request.unlocks}</small>
          </div>
        ))}
      </div>
    </article>
  );
}

function SubsystemCard({ subsystem }) {
  const Icon = iconMap[subsystem.id] || Boxes;
  return (
    <article className="panel subsystem-card">
      <div className="subsystem-head">
        <Icon size={18} />
        <strong>{subsystem.label}</strong>
      </div>
      <span className={`level-pill ${subsystem.ready ? 'ready' : 'open'}`}>{subsystem.ready ? 'ready' : 'open'}</span>
      <p>{subsystem.level}</p>
    </article>
  );
}

function EvidencePanel({ project }) {
  return (
    <article className="panel">
      <div className="panel-label"><ShieldCheck size={16} /> Evidence ledger</div>
      <div className="ledger">
        {project.missingInfo.map((item) => (
          <div className="ledger-row" key={item}>
            <span>{item}</span>
            <strong>needed</strong>
          </div>
        ))}
        {project.missingInfo.length === 0 && (
          <div className="ledger-row">
            <span>Evidence bundle</span>
            <strong>closed</strong>
          </div>
        )}
      </div>
    </article>
  );
}

function ArtifactTable({ project }) {
  return (
    <article className="panel artifact-panel">
      <div className="panel-label"><PackageCheck size={16} /> Generated artifacts</div>
      <table>
        <thead>
          <tr>
            <th>Artifact</th>
            <th>Role</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {project.artifacts.map((artifact) => (
            <tr key={artifact.name}>
              <td>{artifact.name}</td>
              <td>{artifact.role}</td>
              <td><span className="table-status">present</span></td>
            </tr>
          ))}
        </tbody>
      </table>
    </article>
  );
}

function Metric({ label, value, tone = 'neutral' }) {
  return (
    <div className={`metric ${tone}`}>
      <span>{label}</span>
      <strong>{value}</strong>
    </div>
  );
}

createRoot(document.getElementById('root')).render(<App />);
