export const demoProjects = [
  {
    id: 'plant',
    name: 'Desk plant watering',
    archetype: 'automatic_watering',
    goal: 'Build a small automatic plant watering device from cheap or salvaged parts. It should read soil moisture and run a mini pump briefly when the plant is dry.',
    level: 'control_safety_project_package',
    authorityScore: 0.44,
    planningConfidence: 0.82,
    claimable: true,
    simulationReady: false,
    releaseReady: false,
    production: {
      score: 0.41,
      band: 'control safety planning',
      gatesPassed: 2,
      gatesTotal: 9,
      gaps: [
        'circuit_release',
        'mechanical_release',
        'robotics_actuation_release',
        'deterministic_simulation',
        'integrated_bench',
        'field_validation',
        'release_review',
      ],
      blockers: [
        'Circuit release evidence is structural/spec-level only.',
        'Measured geometry and controlled bench evidence are not attached.',
        'Integrated bench, field validation, and reviewed release scope are still open.',
      ],
    },
    nextLevel: 'simulation_bench_project_package',
    claimBoundary: 'Control stack and safety case are coherent. Physical evidence is still required before simulation or release authority.',
    missingInfo: ['measured dimensions', 'bench evidence', 'reviewed release scope'],
    margins: [
      { label: 'current margin', value: '1.526x', width: '64%' },
      { label: 'runtime margin', value: '6.098x', width: '92%' },
      { label: 'estimated runtime', value: '365.85 min', width: '86%' },
    ],
    subsystems: [
      { id: 'circuit', label: 'Circuit', level: 'electrical circuit authority', ready: true },
      { id: 'mechanical', label: 'Mechanical', level: 'mechanical candidate', ready: false },
      { id: 'robotics_actuation', label: 'Actuation', level: 'electrical drive matched', ready: true },
      { id: 'robotics_simulation', label: 'Simulation', level: 'physical evidence blocked', ready: false },
      { id: 'robotics_platform', label: 'Platform', level: 'control safety architecture', ready: true },
      { id: 'mechatronics', label: 'Mechatronics', level: 'electrical circuit authority', ready: false },
    ],
    evidenceRequests: [
      { id: 'measurement', label: 'Measured geometry capture', unlocks: 'mechanical load and fit authority' },
      { id: 'mechanical_bench', label: 'Mechanical fit/load bench', unlocks: 'controlled mechanical evidence' },
      { id: 'robotics_bench', label: 'First-motion/current bench', unlocks: 'controlled robotics motion' },
      { id: 'integrated_bench', label: 'Integrated bench capture', unlocks: 'simulation/bench authority' },
      { id: 'release_review', label: 'Reviewed scoped release', unlocks: 'production package claim' },
    ],
    artifacts: [
      { name: 'PROJECT_INTAKE.json', role: 'normalized user brief' },
      { name: 'PLANNED_SCENARIO.json', role: 'generated compile scenario' },
      { name: 'PROJECT_AUTHORITY.json', role: 'frontend authority source' },
      { name: 'AUTHORITY_UPGRADE_PLAN.json', role: 'next evidence requests' },
      { name: 'ROBOTICS_SIMULATION.json', role: 'deterministic margins' },
      { name: 'MECHATRONICS_AUTHORITY.json', role: 'integration trace' },
    ],
  },
  {
    id: 'rover',
    name: 'Salvaged floor rover',
    archetype: 'rover',
    goal: 'Build a small RC rover from an ESP32, two DC gear motors, a front range sensor, and a printed chassis.',
    level: 'control_safety_project_package',
    authorityScore: 0.44,
    planningConfidence: 0.78,
    claimable: true,
    simulationReady: false,
    releaseReady: false,
    production: {
      score: 0.41,
      band: 'control safety planning',
      gatesPassed: 2,
      gatesTotal: 9,
      gaps: [
        'circuit_release',
        'mechanical_release',
        'robotics_actuation_release',
        'deterministic_simulation',
        'integrated_bench',
        'field_validation',
        'release_review',
      ],
      blockers: [
        'Board release and measured chassis geometry are not attached.',
        'Drive margins pass, but simulation release is blocked by evidence gaps.',
        'First-motion bench, field run, and scoped release review remain open.',
      ],
    },
    nextLevel: 'simulation_bench_project_package',
    claimBoundary: 'Drive, control, and safety architecture are coherent. Release is blocked until measurements and bench evidence are attached.',
    missingInfo: ['measured dimensions', 'bench evidence', 'reviewed release scope'],
    margins: [
      { label: 'current margin', value: '1.35x', width: '58%' },
      { label: 'runtime margin', value: '5.928x', width: '90%' },
      { label: 'wheel speed margin', value: '1.664x', width: '70%' },
      { label: 'tractive force margin', value: '4.437x', width: '88%' },
    ],
    subsystems: [
      { id: 'circuit', label: 'Circuit', level: 'electrical circuit authority', ready: true },
      { id: 'mechanical', label: 'Mechanical', level: 'reference geometry', ready: false },
      { id: 'robotics_actuation', label: 'Actuation', level: 'electrical drive matched', ready: true },
      { id: 'robotics_simulation', label: 'Simulation', level: 'physical evidence blocked', ready: false },
      { id: 'robotics_platform', label: 'Platform', level: 'control safety architecture', ready: true },
      { id: 'mechatronics', label: 'Mechatronics', level: 'electrical circuit authority', ready: false },
    ],
    evidenceRequests: [
      { id: 'measurement', label: 'Measured chassis geometry', unlocks: 'mechanical and drive-base authority' },
      { id: 'motion_bench', label: 'First-motion/current bench', unlocks: 'controlled rover motion' },
      { id: 'integrated_bench', label: 'Integrated drive bench', unlocks: 'simulation/bench authority' },
      { id: 'field_validation', label: 'Marked-boundary run', unlocks: 'field validated authority' },
      { id: 'release_review', label: 'Reviewed scoped release', unlocks: 'production package claim' },
    ],
    artifacts: [
      { name: 'PROJECT_INTAKE.json', role: 'normalized user brief' },
      { name: 'PLANNED_SCENARIO.json', role: 'generated rover scenario' },
      { name: 'PROJECT_AUTHORITY.json', role: 'frontend authority source' },
      { name: 'AUTHORITY_UPGRADE_PLAN.json', role: 'next evidence requests' },
      { name: 'ROBOTICS_SIMULATION.json', role: 'runtime, drive, force margins' },
      { name: 'robotics_platform/drive_base.scad', role: 'generated chassis primitive' },
    ],
  },
];
