"use client";

import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { useWorkspaceStore } from "@/lib/store";
import type { BoardNodeData, ValidationNodeData, ManufacturingNodeData, ManufacturingFile } from "@/lib/node-types";
import { ValidationDrawer } from "./validation-drawer";
import { StructureViewer } from "@/components/workspace/structure-viewer";
import { healthLabel, generateBoardInsights } from "@/lib/jarvis";
import { cn } from "@/lib/utils";
import { FileCode, FileText, Package, Download, Zap, Info, AlertTriangle, Lightbulb } from "lucide-react";

function scoreColor(score: number) {
  if (score >= 80) return "text-emerald-400";
  if (score >= 50) return "text-amber-400";
  return "text-red-400";
}

function FileRow({ file }: { file: ManufacturingFile }) {
  const Icon = file.type === "gerber" || file.type === "drill" ? FileCode : FileText;
  const color =
    file.type === "gerber" || file.type === "drill"
      ? "text-purple-400"
      : file.type === "bom"
        ? "text-cyan-400"
        : "text-white/50";
  return (
    <div className="flex items-center gap-2 py-1.5 border-b border-white/5 last:border-0">
      <Icon size={12} className={color} />
      <span className="text-xs text-white/70 font-mono truncate flex-1">{file.name}</span>
    </div>
  );
}

interface BoardDrawerProps {
  nodeId: string;
  data: BoardNodeData;
  defaultTab?: string;
}

export function BoardDrawer({ nodeId, data, defaultTab = "overview" }: BoardDrawerProps) {
  const { nodes, edges } = useWorkspaceStore();

  const validationEdge = edges.find((e) => e.source === nodeId);
  const validationNode = validationEdge
    ? nodes.find((n) => n.id === validationEdge.target && n.kind === "validation")
    : null;
  const validationData = validationNode?.data as ValidationNodeData | undefined;

  const mfgNode = (() => {
    if (!validationNode) return null;
    const e = edges.find((ed) => ed.source === validationNode.id);
    return e ? nodes.find((n) => n.id === e.target && n.kind === "manufacturing") : null;
  })();
  const mfgData = mfgNode?.data as ManufacturingNodeData | undefined;

  const activeIssueCount = validationData
    ? validationData.issues.filter((i) => !i.acknowledged).length
    : 0;

  function handleDownloadManifest() {
    if (!mfgData?.files) return;
    const lines = [
      `Manufacturing Package: ${mfgData.packageName}`,
      `Generated by Circuit.AI`,
      "",
      "Files:",
      ...mfgData.files.map((f) => `  ${f.name}`),
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${mfgData.packageName}_manifest.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function handleDownloadBom() {
    if (!data.components || data.components.length === 0) return;
    const rows = [
      ["Reference", "Value", "Layer"].join(","),
      ...data.components.map((c) => [c.ref, c.value, c.layer].join(",")),
    ];
    const blob = new Blob([rows.join("\n")], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${data.boardName}_bom.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }

  // Group components by value for BOM
  const bomGroups = (() => {
    if (!data.components || data.components.length === 0) return [];
    const map = new Map<string, { value: string; refs: string[]; layer: string }>();
    data.components.forEach((c) => {
      const key = `${c.value}__${c.layer}`;
      if (!map.has(key)) map.set(key, { value: c.value || "—", refs: [], layer: c.layer });
      map.get(key)!.refs.push(c.ref);
    });
    return Array.from(map.values()).sort((a, b) => b.refs.length - a.refs.length);
  })();

  return (
    <Tabs defaultValue={defaultTab} className="flex flex-col h-full">
      <TabsList>
        <TabsTrigger value="overview">Overview</TabsTrigger>
        <TabsTrigger value="issues">Issues</TabsTrigger>
        <TabsTrigger value="structure">Structure</TabsTrigger>
        <TabsTrigger value="parts">Parts</TabsTrigger>
        <TabsTrigger value="manufacture">Manufacture</TabsTrigger>
      </TabsList>

      {/* Overview */}
      <TabsContent value="overview" className="p-4 flex flex-col gap-4">
        <div className="grid grid-cols-3 gap-2">
          <div className="rounded-xl bg-white/5 border border-white/10 p-3">
            <p className="text-2xl font-bold text-white">{data.componentCount}</p>
            <p className="text-xs text-white/40 mt-0.5">Components</p>
          </div>
          <div className="rounded-xl bg-white/5 border border-white/10 p-3">
            <p className="text-2xl font-bold text-white">{data.layerCount}</p>
            <p className="text-xs text-white/40 mt-0.5">Layers</p>
          </div>
          {data.netCount != null && data.netCount > 0 && (
            <div className="rounded-xl bg-white/5 border border-white/10 p-3">
              <p className="text-2xl font-bold text-white">{data.netCount}</p>
              <p className="text-xs text-white/40 mt-0.5">Nets</p>
            </div>
          )}
        </div>

        {validationData ? (
          <div className="rounded-xl border border-white/10 bg-white/3 p-3 flex items-center gap-3">
            <div
              className={cn(
                "w-10 h-10 rounded-xl border-2 flex items-center justify-center font-bold text-sm",
                scoreColor(validationData.healthScore),
                validationData.healthScore >= 80 ? "border-emerald-500/40"
                  : validationData.healthScore >= 50 ? "border-amber-500/40"
                  : "border-red-500/40"
              )}
            >
              {validationData.healthScore}
            </div>
            <div>
              <p className={cn("text-sm font-medium", scoreColor(validationData.healthScore))}>
                {healthLabel(validationData.healthScore)}
              </p>
              <p className="text-xs text-white/30">
                {activeIssueCount === 0 ? "No active issues" : `${activeIssueCount} active issue${activeIssueCount === 1 ? "" : "s"}`}
              </p>
            </div>
          </div>
        ) : (
          <div className="rounded-xl border border-white/10 bg-white/3 p-3">
            <p className="text-sm text-white/40">Validation not yet run</p>
            <p className="text-xs text-white/25 mt-1">
              Say <span className="text-cyan-400/60 font-mono">validate</span> in the command bar or click &ldquo;Check issues&rdquo; on the node.
            </p>
          </div>
        )}

        <div className="flex gap-2 flex-wrap">
          <Badge variant="info">{data.layerCount}-layer PCB</Badge>
          <Badge variant="default">KiCad</Badge>
          {mfgData?.status === "done" && <Badge variant="success">Mfg Ready</Badge>}
        </div>

        {/* JARVIS board insights */}
        {(() => {
          const insights = generateBoardInsights(
            data.componentCount,
            data.layerCount,
            data.netCount,
            validationData?.healthScore
          );
          if (insights.length === 0) return null;
          return (
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-1.5">
                <Zap size={11} className="text-cyan-400/60" />
                <span className="text-[10px] text-white/40 uppercase tracking-widest font-semibold">JARVIS Insights</span>
              </div>
              {insights.map((ins, i) => {
                const Icon = ins.level === "warn" ? AlertTriangle : ins.level === "tip" ? Lightbulb : Info;
                const colors = ins.level === "warn"
                  ? "border-amber-700/30 bg-amber-950/10"
                  : ins.level === "tip"
                    ? "border-cyan-700/25 bg-cyan-950/10"
                    : "border-white/10 bg-white/3";
                const iconColor = ins.level === "warn" ? "text-amber-400/70" : ins.level === "tip" ? "text-cyan-400/70" : "text-white/30";
                return (
                  <div key={i} className={cn("rounded-xl border p-2.5 flex gap-2", colors)}>
                    <Icon size={12} className={cn("flex-shrink-0 mt-0.5", iconColor)} />
                    <div>
                      <p className="text-[10px] font-semibold text-white/50 uppercase tracking-wide mb-0.5">{ins.label}</p>
                      <p className="text-[11px] text-white/60 leading-relaxed">{ins.body}</p>
                    </div>
                  </div>
                );
              })}
            </div>
          );
        })()}
      </TabsContent>

      {/* Issues */}
      <TabsContent value="issues" className="flex flex-col h-full">
        {validationData ? (
          <ValidationDrawer nodeId={validationNode!.id} data={validationData} defaultTab="issues" />
        ) : (
          <div className="flex-1 flex items-center justify-center p-6">
            <div className="text-center">
              <p className="text-white/40 text-sm">No validation data yet</p>
              <p className="text-white/25 text-xs mt-1">
                Say <span className="text-cyan-400/60 font-mono">validate</span> to run the ERC check.
              </p>
            </div>
          </div>
        )}
      </TabsContent>

      {/* Structure — 2D component placement viewer */}
      <TabsContent value="structure" className="flex flex-col overflow-y-auto">
        <StructureViewer
          components={data.components ?? []}
          layerCount={data.layerCount}
          boardName={data.boardName}
        />
      </TabsContent>

      {/* Parts — BOM grouped by value */}
      <TabsContent value="parts" className="flex flex-col gap-3 p-4 overflow-y-auto">
        {bomGroups.length === 0 ? (
          <div className="flex-1 flex items-center justify-center">
            <div className="text-center">
              <p className="text-white/40 text-sm">No component data available</p>
              <p className="text-white/25 text-xs mt-1">
                Re-drop the .kicad_pcb file so I can read component positions.
              </p>
            </div>
          </div>
        ) : (
          <>
            <div className="flex items-center justify-between">
              <p className="text-xs text-white/40">{data.componentCount} components · {bomGroups.length} unique values</p>
              <button
                onClick={handleDownloadBom}
                className="flex items-center gap-1 text-xs text-cyan-400/60 hover:text-cyan-400 transition-colors"
              >
                <Download size={11} />
                <span>CSV</span>
              </button>
            </div>

            <div className="rounded-xl border border-white/10 overflow-hidden">
              <table className="w-full text-xs">
                <thead>
                  <tr className="border-b border-white/10 bg-white/3">
                    <th className="text-left px-3 py-2 text-white/40 font-medium">Qty</th>
                    <th className="text-left px-3 py-2 text-white/40 font-medium">Value</th>
                    <th className="text-left px-3 py-2 text-white/40 font-medium">References</th>
                    <th className="text-left px-3 py-2 text-white/40 font-medium">Layer</th>
                  </tr>
                </thead>
                <tbody>
                  {bomGroups.map((g, i) => (
                    <tr key={i} className="border-b border-white/5 last:border-0 hover:bg-white/3 transition-colors">
                      <td className="px-3 py-2 text-white/60 font-mono">{g.refs.length}</td>
                      <td className="px-3 py-2 text-white/80">{g.value}</td>
                      <td className="px-3 py-2 text-white/40 font-mono truncate max-w-[100px]">
                        {g.refs.slice(0, 4).join(", ")}{g.refs.length > 4 ? `… +${g.refs.length - 4}` : ""}
                      </td>
                      <td className="px-3 py-2">
                        <span className={cn("text-xs", g.layer === "F.Cu" ? "text-cyan-400/70" : "text-amber-400/70")}>
                          {g.layer === "F.Cu" ? "Front" : "Back"}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </>
        )}
      </TabsContent>

      {/* Manufacture */}
      <TabsContent value="manufacture" className="p-4 flex flex-col gap-4 overflow-y-auto">
        {!mfgData && (
          <div className="rounded-xl border border-white/10 bg-white/3 p-4 text-center">
            <Package size={24} className="text-purple-400/50 mx-auto mb-2" />
            <p className="text-sm text-white/50 font-medium">No package generated yet</p>
            <p className="text-xs text-white/30 mt-1">
              {validationData
                ? validationData.issues.filter((i) => i.severity === "critical" && !i.acknowledged).length > 0
                  ? "Fix critical issues first."
                  : 'Say manufacture in the command bar or click "Package for manufacture →" on the node.'
                : "Run validation first, then generate the manufacturing package."}
            </p>
          </div>
        )}

        {mfgData?.status === "processing" && (
          <div className="rounded-xl border border-purple-500/30 bg-purple-950/20 p-4 text-center">
            <div className="w-6 h-6 border-2 border-purple-500/60 border-t-purple-400 rounded-full animate-spin mx-auto mb-2" />
            <p className="text-sm text-purple-300">Generating manufacturing package…</p>
          </div>
        )}

        {mfgData?.status === "done" && mfgData.files && (
          <>
            <div className="rounded-xl border border-emerald-500/30 bg-emerald-950/10 p-3 flex items-center gap-3">
              <Package size={18} className="text-emerald-400 flex-shrink-0" />
              <div className="flex-1">
                <p className="text-sm font-medium text-emerald-400">Package ready</p>
                <p className="text-xs text-white/30">
                  {mfgData.gerberCount} Gerber/drill files
                  {mfgData.hasBom ? " · BOM" : ""}
                  {mfgData.hasAssembly ? " · Assembly guide" : ""}
                </p>
              </div>
              <button
                onClick={handleDownloadManifest}
                className="flex items-center gap-1 text-xs text-purple-400/60 hover:text-purple-400 transition-colors"
              >
                <Download size={12} />
                <span>Manifest</span>
              </button>
            </div>

            <div className="rounded-xl border border-white/10 bg-white/3 p-3">
              <p className="text-xs text-white/40 uppercase tracking-wide mb-2">Output files</p>
              {mfgData.files.map((f) => (
                <FileRow key={f.name} file={f} />
              ))}
            </div>
          </>
        )}

        {mfgData?.status === "error" && (
          <div className="rounded-xl border border-red-700/40 bg-red-950/20 p-4">
            <p className="text-sm text-red-400 font-medium mb-1">Generation failed</p>
            <p className="text-xs text-white/40">{mfgData.errorMessage}</p>
          </div>
        )}
      </TabsContent>
    </Tabs>
  );
}
