"use client";

import { useEffect, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Package, FileCode, FileText, Download, ExternalLink, ChevronDown, ChevronRight } from "lucide-react";
import { useWorkspaceStore } from "@/lib/store";
import type { BoardNodeData, ValidationNodeData, FileNodeData, ManufacturingNodeData, ManufacturingFile } from "@/lib/node-types";
import { BoardDrawer } from "./board-drawer";
import { ValidationDrawer } from "./validation-drawer";
import { jarvis, fileKindLabel, formatFileSize } from "@/lib/jarvis";
import type { FileKind } from "@/lib/jarvis";
import { Badge } from "@/components/ui/badge";

const kindLabel: Record<string, string> = {
  file: "File",
  board: "PCB Board",
  validation: "Validation Results",
  manufacturing: "Manufacturing Package",
};

function MfgDrawer({ data }: { data: ManufacturingNodeData }) {
  function handleDownloadManifest() {
    if (!data.files) return;
    const lines = [
      `Manufacturing Package: ${data.packageName}`,
      `Generated by Circuit.AI`,
      "",
      "Files:",
      ...data.files.map((f) => `  ${f.name}`),
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${data.packageName}_manifest.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function FileGroup({ title, files, color }: { title: string; files: ManufacturingFile[]; color: string }) {
    const [expanded, setExpanded] = useState(true);
    if (files.length === 0) return null;
    return (
      <div className="rounded-xl border border-white/10 bg-white/3 overflow-hidden">
        <button
          onClick={() => setExpanded((x) => !x)}
          className="w-full flex items-center justify-between px-3 py-2 hover:bg-white/5 transition-colors"
        >
          <span className={`text-xs font-semibold uppercase tracking-wide ${color}`}>{title}</span>
          <div className="flex items-center gap-2">
            <span className="text-[10px] text-white/25">{files.length} file{files.length === 1 ? "" : "s"}</span>
            {expanded ? <ChevronDown size={12} className="text-white/30" /> : <ChevronRight size={12} className="text-white/30" />}
          </div>
        </button>
        {expanded && (
          <div className="px-3 pb-2 border-t border-white/5">
            {files.map((f) => <FileRow key={f.name} file={f} />)}
          </div>
        )}
      </div>
    );
  }

  function FileRow({ file }: { file: ManufacturingFile }) {
    const Icon = file.type === "gerber" || file.type === "drill" ? FileCode : FileText;
    const color =
      file.type === "gerber" || file.type === "drill"
        ? "text-purple-400"
        : file.type === "bom"
          ? "text-cyan-400"
          : "text-white/50";
    return (
      <div className="flex items-center gap-2 py-1.5 border-b border-white/5 last:border-0">
        <Icon size={12} className={color} />
        <span className="text-xs text-white/70 font-mono truncate flex-1">{file.name}</span>
      </div>
    );
  }

  if (data.status === "processing") {
    return (
      <div className="flex-1 flex items-center justify-center p-8">
        <div className="text-center">
          <div className="w-8 h-8 border-2 border-purple-500/60 border-t-purple-400 rounded-full animate-spin mx-auto mb-3" />
          <p className="text-sm text-purple-300">Generating manufacturing package…</p>
        </div>
      </div>
    );
  }

  if (data.status !== "done" || !data.files) {
    return (
      <div className="flex-1 flex items-center justify-center p-8">
        <p className="text-sm text-white/40">No files yet.</p>
      </div>
    );
  }

  const gerberFiles = data.files.filter((f) => f.type === "gerber" || f.type === "drill");
  const bomFiles = data.files.filter((f) => f.type === "bom");
  const assemblyFiles = data.files.filter((f) => f.type === "assembly");

  return (
    <div className="flex flex-col gap-4 p-4 overflow-y-auto">
      {/* Summary banner */}
      <div className="rounded-xl border border-emerald-500/30 bg-emerald-950/10 p-3 flex items-center gap-3">
        <Package size={18} className="text-emerald-400 flex-shrink-0" />
        <div className="flex-1 min-w-0">
          <p className="text-sm font-medium text-emerald-400">Package ready</p>
          <p className="text-xs text-white/30 mt-0.5">
            {data.gerberCount} Gerber/drill files
            {data.hasBom ? " · BOM" : ""}
            {data.hasAssembly ? " · Assembly guide" : ""}
          </p>
        </div>
        <button
          onClick={handleDownloadManifest}
          className="flex items-center gap-1 text-xs text-purple-400/60 hover:text-purple-400 transition-colors"
        >
          <Download size={12} />
          <span>Manifest</span>
        </button>
      </div>

      {/* Grouped file sections */}
      <FileGroup title="Gerber & Drill Files" files={gerberFiles} color="text-purple-400" />
      {bomFiles.length > 0 && <FileGroup title="Bill of Materials" files={bomFiles} color="text-cyan-400" />}
      {assemblyFiles.length > 0 && <FileGroup title="Assembly Guide" files={assemblyFiles} color="text-amber-400" />}

      {/* Fab house guidance */}
      <div className="rounded-xl border border-white/10 bg-white/3 p-3 flex flex-col gap-2">
        <p className="text-xs text-white/40 uppercase tracking-wide font-semibold">Submit to fab</p>
        <p className="text-[11px] text-white/40 leading-relaxed">
          Zip the Gerber/drill files and upload to your preferred PCB manufacturer. Most fabs accept the standard KiCad output directly.
        </p>
        <div className="flex flex-col gap-1.5">
          {[
            { name: "JLCPCB", note: "5 pcs from $2", url: "https://jlcpcb.com" },
            { name: "PCBWay", note: "Assembly + component sourcing", url: "https://www.pcbway.com" },
            { name: "OSH Park", note: "US-made, signature purple solder mask", url: "https://oshpark.com" },
          ].map((fab) => (
            <a
              key={fab.name}
              href={fab.url}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 py-1 px-2 rounded-lg hover:bg-white/5 transition-colors group"
            >
              <ExternalLink size={10} className="text-white/20 group-hover:text-purple-400 flex-shrink-0 transition-colors" />
              <span className="text-xs text-white/60 font-medium group-hover:text-white/80 transition-colors">{fab.name}</span>
              <span className="text-[10px] text-white/25 group-hover:text-white/40 transition-colors">{fab.note}</span>
            </a>
          ))}
        </div>
      </div>
    </div>
  );
}

export function NodeDrawer() {
  const { drawer, closeDrawer, nodes, edges, addJarvisMessage, showJarvisStrip } = useWorkspaceStore();

  const node = drawer ? nodes.find((n) => n.id === drawer.nodeId) : null;
  const prevNodeIdRef = useRef<string | null>(null);

  // Escape key closes drawer
  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") closeDrawer();
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [closeDrawer]);

  // JARVIS narrates when a new node's drawer opens
  useEffect(() => {
    if (!drawer || !node) return;
    if (drawer.nodeId === prevNodeIdRef.current) return; // tab change only — skip
    prevNodeIdRef.current = drawer.nodeId;

    let narration: string | null = null;

    if (node.kind === "board") {
      const d = node.data as BoardNodeData;
      // Find validation node connected to this board
      const valEdge = edges.find((e) => e.source === node.id);
      const valNode = valEdge ? nodes.find((n) => n.id === valEdge.target && n.kind === "validation") : null;
      const valData = valNode?.data as ValidationNodeData | undefined;
      narration = jarvis.drawerOpenedBoard(d.boardName, d.componentCount, d.layerCount, d.netCount, valData?.healthScore, d.boardWidthMm, d.boardHeightMm);
    } else if (node.kind === "validation") {
      const d = node.data as ValidationNodeData;
      const boardNode = nodes.find((n) => n.id === d.sourceBoardNodeId);
      const boardName = boardNode ? (boardNode.data as BoardNodeData).boardName : "the board";
      const activeIssues = d.issues.filter((i) => !i.acknowledged);
      const criticalCount = activeIssues.filter((i) => i.severity === "critical").length;
      narration = jarvis.drawerOpenedValidation(boardName, d.healthScore, activeIssues.length, criticalCount);
    } else if (node.kind === "manufacturing") {
      const d = node.data as ManufacturingNodeData;
      narration = jarvis.drawerOpenedMfg(d.packageName, d.status, d.gerberCount, d.hasBom, d.hasAssembly);
    } else if (node.kind === "file") {
      const d = node.data as FileNodeData;
      narration = jarvis.drawerOpenedFile(d.filename, d.fileKind, d.sizeBytes, d.status === "done");
    }

    if (narration) {
      addJarvisMessage({ role: "jarvis", text: narration, nodeId: node.id });
      showJarvisStrip({ message: narration, nodeId: node.id });
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [drawer?.nodeId]);

  return (
    <AnimatePresence>
      {drawer && node && (
        <motion.aside
          key={drawer.nodeId}
          initial={{ x: "100%" }}
          animate={{ x: 0 }}
          exit={{ x: "100%" }}
          transition={{ type: "spring", stiffness: 320, damping: 32 }}
          className="absolute right-0 top-0 h-full w-[420px] bg-[#0f172a] border-l border-white/10 flex flex-col z-20 overflow-hidden"
        >
          {/* Header */}
          <div className="flex items-center gap-3 px-4 py-3 border-b border-white/10 flex-shrink-0">
            <div className="flex-1 min-w-0">
              <p className="text-xs text-white/40 uppercase tracking-wide">
                {kindLabel[node.kind] ?? node.kind}
              </p>
              <p className="text-sm text-white font-medium truncate mt-0.5">
                {node.kind === "board"
                  ? (node.data as BoardNodeData).boardName
                  : node.kind === "file"
                    ? (node.data as FileNodeData).filename
                    : node.kind === "validation"
                      ? `Health Score: ${(node.data as ValidationNodeData).healthScore}/100`
                      : node.kind === "manufacturing"
                        ? (node.data as ManufacturingNodeData).packageName
                        : node.id}
              </p>
            </div>
            <button
              onClick={closeDrawer}
              className="text-white/30 hover:text-white/70 transition-colors flex-shrink-0"
              aria-label="Close drawer"
            >
              <X size={18} />
            </button>
          </div>

          {/* Body */}
          <div className="flex-1 overflow-hidden flex flex-col">
            {node.kind === "board" && (
              <BoardDrawer
                nodeId={node.id}
                data={node.data as BoardNodeData}
                defaultTab={drawer.tab}
              />
            )}
            {node.kind === "validation" && (
              <ValidationDrawer
                nodeId={node.id}
                data={node.data as ValidationNodeData}
                defaultTab={drawer.tab}
              />
            )}
            {node.kind === "manufacturing" && (
              <MfgDrawer data={node.data as ManufacturingNodeData} />
            )}
            {node.kind === "file" && (() => {
              const d = node.data as FileNodeData;
              const isParsed = d.status === "done";
              return (
                <div className="flex flex-col gap-4 p-4 overflow-y-auto">
                  {/* File identity */}
                  <div className="rounded-xl border border-white/10 bg-white/3 p-4 flex items-start gap-3">
                    <FileText size={22} className="text-white/30 flex-shrink-0 mt-0.5" />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-white/80 break-all leading-snug">{d.filename}</p>
                      <div className="flex items-center gap-2 mt-2">
                        <Badge variant="info">{fileKindLabel(d.fileKind as FileKind)}</Badge>
                        <span className="text-xs text-white/30">{formatFileSize(d.sizeBytes)}</span>
                        {isParsed && <Badge variant="success">Parsed</Badge>}
                      </div>
                    </div>
                  </div>

                  {/* Status guidance */}
                  {isParsed ? (
                    <div className="rounded-xl border border-emerald-600/30 bg-emerald-950/20 p-3">
                      <p className="text-sm text-emerald-400 font-medium mb-1">Board extracted</p>
                      <p className="text-xs text-white/40 leading-relaxed">
                        The circuit structure has been parsed. See the connected Board node for components, layers, and validation.
                      </p>
                    </div>
                  ) : (
                    <div className="rounded-xl border border-cyan-500/20 bg-cyan-950/10 p-3">
                      <p className="text-xs text-white/50 leading-relaxed">
                        Click <span className="text-cyan-400 font-medium">Parse board</span> on the canvas node to extract the circuit structure and begin the validation pipeline.
                      </p>
                    </div>
                  )}

                  {/* What JARVIS will extract */}
                  {!isParsed && d.fileKind === "kicad_pcb" && (
                    <div className="rounded-xl border border-white/[0.07] bg-white/[0.02] p-3">
                      <p className="text-[10px] text-white/40 uppercase tracking-widest font-semibold mb-2">What I&apos;ll extract</p>
                      <ul className="text-xs text-white/45 space-y-1.5 leading-relaxed">
                        <li className="flex items-center gap-2"><span className="w-1 h-1 rounded-full bg-cyan-500/60 flex-shrink-0" />Component count and placement</li>
                        <li className="flex items-center gap-2"><span className="w-1 h-1 rounded-full bg-cyan-500/60 flex-shrink-0" />Layer stack-up (1L, 2L, 4L…)</li>
                        <li className="flex items-center gap-2"><span className="w-1 h-1 rounded-full bg-cyan-500/60 flex-shrink-0" />Net connections and ratsnest</li>
                        <li className="flex items-center gap-2"><span className="w-1 h-1 rounded-full bg-cyan-500/60 flex-shrink-0" />Footprint data for DFM analysis</li>
                      </ul>
                    </div>
                  )}

                  {!isParsed && d.fileKind === "bom_csv" && (
                    <div className="rounded-xl border border-white/[0.07] bg-white/[0.02] p-3">
                      <p className="text-[10px] text-white/40 uppercase tracking-widest font-semibold mb-2">What I&apos;ll extract</p>
                      <ul className="text-xs text-white/45 space-y-1.5 leading-relaxed">
                        <li className="flex items-center gap-2"><span className="w-1 h-1 rounded-full bg-violet-500/60 flex-shrink-0" />Component list and quantities</li>
                        <li className="flex items-center gap-2"><span className="w-1 h-1 rounded-full bg-violet-500/60 flex-shrink-0" />Part numbers and values</li>
                        <li className="flex items-center gap-2"><span className="w-1 h-1 rounded-full bg-violet-500/60 flex-shrink-0" />Sourcing availability check</li>
                      </ul>
                    </div>
                  )}
                </div>
              );
            })()}
          </div>
        </motion.aside>
      )}
    </AnimatePresence>
  );
}
