"use client";

import { useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Package, FileCode, FileText, Download, ExternalLink, ChevronDown, ChevronRight } from "lucide-react";
import { useState } from "react";
import { useWorkspaceStore } from "@/lib/store";
import type { BoardNodeData, ValidationNodeData, FileNodeData, ManufacturingNodeData, ManufacturingFile } from "@/lib/node-types";
import { BoardDrawer } from "./board-drawer";
import { ValidationDrawer } from "./validation-drawer";

const kindLabel: Record<string, string> = {
  file: "File",
  board: "PCB Board",
  validation: "Validation Results",
  manufacturing: "Manufacturing Package",
};

function MfgDrawer({ data }: { data: ManufacturingNodeData }) {
  function handleDownloadManifest() {
    if (!data.files) return;
    const lines = [
      `Manufacturing Package: ${data.packageName}`,
      `Generated by Circuit.AI`,
      "",
      "Files:",
      ...data.files.map((f) => `  ${f.name}`),
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${data.packageName}_manifest.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function FileGroup({ title, files, color }: { title: string; files: ManufacturingFile[]; color: string }) {
    const [expanded, setExpanded] = useState(true);
    if (files.length === 0) return null;
    return (
      <div className="rounded-xl border border-white/10 bg-white/3 overflow-hidden">
        <button
          onClick={() => setExpanded((x) => !x)}
          className="w-full flex items-center justify-between px-3 py-2 hover:bg-white/5 transition-colors"
        >
          <span className={`text-xs font-semibold uppercase tracking-wide ${color}`}>{title}</span>
          <div className="flex items-center gap-2">
            <span className="text-[10px] text-white/25">{files.length} file{files.length === 1 ? "" : "s"}</span>
            {expanded ? <ChevronDown size={12} className="text-white/30" /> : <ChevronRight size={12} className="text-white/30" />}
          </div>
        </button>
        {expanded && (
          <div className="px-3 pb-2 border-t border-white/5">
            {files.map((f) => <FileRow key={f.name} file={f} />)}
          </div>
        )}
      </div>
    );
  }

  function FileRow({ file }: { file: ManufacturingFile }) {
    const Icon = file.type === "gerber" || file.type === "drill" ? FileCode : FileText;
    const color =
      file.type === "gerber" || file.type === "drill"
        ? "text-purple-400"
        : file.type === "bom"
          ? "text-cyan-400"
          : "text-white/50";
    return (
      <div className="flex items-center gap-2 py-1.5 border-b border-white/5 last:border-0">
        <Icon size={12} className={color} />
        <span className="text-xs text-white/70 font-mono truncate flex-1">{file.name}</span>
      </div>
    );
  }

  if (data.status === "processing") {
    return (
      <div className="flex-1 flex items-center justify-center p-8">
        <div className="text-center">
          <div className="w-8 h-8 border-2 border-purple-500/60 border-t-purple-400 rounded-full animate-spin mx-auto mb-3" />
          <p className="text-sm text-purple-300">Generating manufacturing package…</p>
        </div>
      </div>
    );
  }

  if (data.status !== "done" || !data.files) {
    return (
      <div className="flex-1 flex items-center justify-center p-8">
        <p className="text-sm text-white/40">No files yet.</p>
      </div>
    );
  }

  const gerberFiles = data.files.filter((f) => f.type === "gerber" || f.type === "drill");
  const bomFiles = data.files.filter((f) => f.type === "bom");
  const assemblyFiles = data.files.filter((f) => f.type === "assembly");

  return (
    <div className="flex flex-col gap-4 p-4 overflow-y-auto">
      {/* Summary banner */}
      <div className="rounded-xl border border-emerald-500/30 bg-emerald-950/10 p-3 flex items-center gap-3">
        <Package size={18} className="text-emerald-400 flex-shrink-0" />
        <div className="flex-1 min-w-0">
          <p className="text-sm font-medium text-emerald-400">Package ready</p>
          <p className="text-xs text-white/30 mt-0.5">
            {data.gerberCount} Gerber/drill files
            {data.hasBom ? " · BOM" : ""}
            {data.hasAssembly ? " · Assembly guide" : ""}
          </p>
        </div>
        <button
          onClick={handleDownloadManifest}
          className="flex items-center gap-1 text-xs text-purple-400/60 hover:text-purple-400 transition-colors"
        >
          <Download size={12} />
          <span>Manifest</span>
        </button>
      </div>

      {/* Grouped file sections */}
      <FileGroup title="Gerber & Drill Files" files={gerberFiles} color="text-purple-400" />
      {bomFiles.length > 0 && <FileGroup title="Bill of Materials" files={bomFiles} color="text-cyan-400" />}
      {assemblyFiles.length > 0 && <FileGroup title="Assembly Guide" files={assemblyFiles} color="text-amber-400" />}

      {/* Fab house guidance */}
      <div className="rounded-xl border border-white/10 bg-white/3 p-3 flex flex-col gap-2">
        <p className="text-xs text-white/40 uppercase tracking-wide font-semibold">Submit to fab</p>
        <p className="text-[11px] text-white/40 leading-relaxed">
          Upload the Gerber zip to your preferred PCB manufacturer. Most fabs accept the standard KiCad output directly.
        </p>
        <div className="flex flex-col gap-1">
          {[
            { name: "JLCPCB", note: "5 pcs from $2", href: null },
            { name: "PCBWay", note: "assembly + sourcing", href: null },
            { name: "OSH Park", note: "US-made, purple PCBs", href: null },
          ].map((fab) => (
            <div key={fab.name} className="flex items-center gap-2">
              <ExternalLink size={10} className="text-white/20 flex-shrink-0" />
              <span className="text-xs text-white/60 font-medium">{fab.name}</span>
              <span className="text-[10px] text-white/25">{fab.note}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export function NodeDrawer() {
  const { drawer, closeDrawer, nodes } = useWorkspaceStore();

  const node = drawer ? nodes.find((n) => n.id === drawer.nodeId) : null;

  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") closeDrawer();
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [closeDrawer]);

  return (
    <AnimatePresence>
      {drawer && node && (
        <motion.aside
          key={drawer.nodeId}
          initial={{ x: "100%" }}
          animate={{ x: 0 }}
          exit={{ x: "100%" }}
          transition={{ type: "spring", stiffness: 320, damping: 32 }}
          className="absolute right-0 top-0 h-full w-[420px] bg-[#0f172a] border-l border-white/10 flex flex-col z-20 overflow-hidden"
        >
          {/* Header */}
          <div className="flex items-center gap-3 px-4 py-3 border-b border-white/10 flex-shrink-0">
            <div className="flex-1 min-w-0">
              <p className="text-xs text-white/40 uppercase tracking-wide">
                {kindLabel[node.kind] ?? node.kind}
              </p>
              <p className="text-sm text-white font-medium truncate mt-0.5">
                {node.kind === "board"
                  ? (node.data as BoardNodeData).boardName
                  : node.kind === "file"
                    ? (node.data as FileNodeData).filename
                    : node.kind === "validation"
                      ? `Health Score: ${(node.data as ValidationNodeData).healthScore}/100`
                      : node.kind === "manufacturing"
                        ? (node.data as ManufacturingNodeData).packageName
                        : node.id}
              </p>
            </div>
            <button
              onClick={closeDrawer}
              className="text-white/30 hover:text-white/70 transition-colors flex-shrink-0"
              aria-label="Close drawer"
            >
              <X size={18} />
            </button>
          </div>

          {/* Body */}
          <div className="flex-1 overflow-hidden flex flex-col">
            {node.kind === "board" && (
              <BoardDrawer
                nodeId={node.id}
                data={node.data as BoardNodeData}
                defaultTab={drawer.tab}
              />
            )}
            {node.kind === "validation" && (
              <ValidationDrawer
                nodeId={node.id}
                data={node.data as ValidationNodeData}
                defaultTab={drawer.tab}
              />
            )}
            {node.kind === "manufacturing" && (
              <MfgDrawer data={node.data as ManufacturingNodeData} />
            )}
            {node.kind === "file" && (
              <div className="flex-1 flex items-center justify-center p-6">
                <div className="text-center">
                  <p className="text-white/40 text-sm">File details</p>
                  <p className="text-white/25 text-xs mt-1">
                    Parse the board to see more information.
                  </p>
                </div>
              </div>
            )}
          </div>
        </motion.aside>
      )}
    </AnimatePresence>
  );
}
